cur_class = vtkArrowSource
@scall Ptr{vtkArrowSource} vtkArrowSourceNew () _ZN14vtkArrowSource3NewEv "libvtkGraphics"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN14vtkArrowSource8IsTypeOfEPKc "libvtkGraphics"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkArrowSource} SafeDownCast (Ptr{vtkObjectBase},) _ZN14vtkArrowSource12SafeDownCastEP13vtkObjectBase "libvtkGraphics"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkArrowSource} NewInstance () _ZNK14vtkArrowSource11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetTipLength (Float64,)
@vcall 66 Float64 GetTipLengthMinValue ()
@vcall 67 Float64 GetTipLengthMaxValue ()
@vcall 68 Float64 GetTipLength ()
@vcall 69 None SetTipRadius (Float64,)
@vcall 70 Float64 GetTipRadiusMinValue ()
@vcall 71 Float64 GetTipRadiusMaxValue ()
@vcall 72 Float64 GetTipRadius ()
@vcall 73 None SetTipResolution (Int32,)
@vcall 74 Int32 GetTipResolutionMinValue ()
@vcall 75 Int32 GetTipResolutionMaxValue ()
@vcall 76 Int32 GetTipResolution ()
@vcall 77 None SetShaftRadius (Float64,)
@vcall 78 Float64 GetShaftRadiusMinValue ()
@vcall 79 Float64 GetShaftRadiusMaxValue ()
@vcall 80 Float64 GetShaftRadius ()
@vcall 81 None SetShaftResolution (Int32,)
@vcall 82 Int32 GetShaftResolutionMinValue ()
@vcall 83 Int32 GetShaftResolutionMaxValue ()
@vcall 84 Int32 GetShaftResolution ()
@vcall 85 None InvertOn ()
@vcall 86 None InvertOff ()
@vcall 87 None SetInvert (Bool,)
@vcall 88 Bool GetInvert ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkArrowSource_eq (Void,) _ZN14vtkArrowSourceaSERKS_ "libvtkGraphics"
