cur_class = vtkAxisActor2D
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN14vtkAxisActor2D8IsTypeOfEPKc "libvtkRendering"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkAxisActor2D} SafeDownCast (Ptr{vtkObjectBase},) _ZN14vtkAxisActor2D12SafeDownCastEP13vtkObjectBase "libvtkRendering"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkAxisActor2D} NewInstance () _ZNK14vtkAxisActor2D11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@scall Ptr{vtkAxisActor2D} vtkAxisActor2DNew () _ZN14vtkAxisActor2D3NewEv "libvtkRendering"
@vcall 87 Ptr{vtkCoordinate} GetPoint1Coordinate ()
@vcall 88 None SetPoint1 (Ptr{Float64},)
@vcall 89 None SetPoint1 (Float64, Float64)
@vcall 90 Ptr{Float64} GetPoint1 ()
@vcall 91 Ptr{vtkCoordinate} GetPoint2Coordinate ()
@vcall 92 None SetPoint2 (Ptr{Float64},)
@vcall 93 None SetPoint2 (Float64, Float64)
@vcall 94 Ptr{Float64} GetPoint2 ()
@vcall 95 None SetRange (Float64, Float64)
@mcall None SetRange (Ptr{Float64},) _ZN14vtkAxisActor2D8SetRangeEPd "libvtkRendering"
@vcall 96 Ptr{Float64} GetRange ()
@vcall 97 None GetRange (Ptr{Float64},)
@vcall 98 None SetRulerMode (Int32,)
@vcall 99 Int32 GetRulerMode ()
@vcall 100 None RulerModeOn ()
@vcall 101 None RulerModeOff ()
@vcall 102 None SetRulerDistance (Float64,)
@vcall 103 Float64 GetRulerDistanceMinValue ()
@vcall 104 Float64 GetRulerDistanceMaxValue ()
@vcall 105 Float64 GetRulerDistance ()
@vcall 106 None SetNumberOfLabels (Int32,)
@vcall 107 Int32 GetNumberOfLabelsMinValue ()
@vcall 108 Int32 GetNumberOfLabelsMaxValue ()
@vcall 109 Int32 GetNumberOfLabels ()
@vcall 110 None SetLabelFormat (Ptr{Uint8},)
@vcall 111 Ptr{Uint8} GetLabelFormat ()
@vcall 112 None SetAdjustLabels (Int32,)
@vcall 113 Int32 GetAdjustLabels ()
@vcall 114 None AdjustLabelsOn ()
@vcall 115 None AdjustLabelsOff ()
@vcall 116 Ptr{Float64} GetAdjustedRange ()
@vcall 117 None GetAdjustedRange (Void, Void)
@vcall 118 None GetAdjustedRange (Ptr{Float64},)
@vcall 119 Int32 GetAdjustedNumberOfLabels ()
@vcall 120 None SetTitle (Ptr{Uint8},)
@vcall 121 Ptr{Uint8} GetTitle ()
@vcall 122 None SetTitleTextProperty (Ptr{vtkTextProperty},)
@vcall 123 Ptr{vtkTextProperty} GetTitleTextProperty ()
@vcall 124 None SetLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 125 Ptr{vtkTextProperty} GetLabelTextProperty ()
@vcall 126 None SetTickLength (Int32,)
@vcall 127 Int32 GetTickLengthMinValue ()
@vcall 128 Int32 GetTickLengthMaxValue ()
@vcall 129 Int32 GetTickLength ()
@vcall 130 None SetNumberOfMinorTicks (Int32,)
@vcall 131 Int32 GetNumberOfMinorTicksMinValue ()
@vcall 132 Int32 GetNumberOfMinorTicksMaxValue ()
@vcall 133 Int32 GetNumberOfMinorTicks ()
@vcall 134 None SetMinorTickLength (Int32,)
@vcall 135 Int32 GetMinorTickLengthMinValue ()
@vcall 136 Int32 GetMinorTickLengthMaxValue ()
@vcall 137 Int32 GetMinorTickLength ()
@vcall 138 None SetTickOffset (Int32,)
@vcall 139 Int32 GetTickOffsetMinValue ()
@vcall 140 Int32 GetTickOffsetMaxValue ()
@vcall 141 Int32 GetTickOffset ()
@vcall 142 None SetAxisVisibility (Int32,)
@vcall 143 Int32 GetAxisVisibility ()
@vcall 144 None AxisVisibilityOn ()
@vcall 145 None AxisVisibilityOff ()
@vcall 146 None SetTickVisibility (Int32,)
@vcall 147 Int32 GetTickVisibility ()
@vcall 148 None TickVisibilityOn ()
@vcall 149 None TickVisibilityOff ()
@vcall 150 None SetLabelVisibility (Int32,)
@vcall 151 Int32 GetLabelVisibility ()
@vcall 152 None LabelVisibilityOn ()
@vcall 153 None LabelVisibilityOff ()
@vcall 154 None SetTitleVisibility (Int32,)
@vcall 155 Int32 GetTitleVisibility ()
@vcall 156 None TitleVisibilityOn ()
@vcall 157 None TitleVisibilityOff ()
@vcall 158 None SetTitlePosition (Float64,)
@vcall 159 Float64 GetTitlePosition ()
@vcall 160 None SetFontFactor (Float64,)
@vcall 161 Float64 GetFontFactorMinValue ()
@vcall 162 Float64 GetFontFactorMaxValue ()
@vcall 163 Float64 GetFontFactor ()
@vcall 164 None SetLabelFactor (Float64,)
@vcall 165 Float64 GetLabelFactorMinValue ()
@vcall 166 Float64 GetLabelFactorMaxValue ()
@vcall 167 Float64 GetLabelFactor ()
@vcall 54 Int32 RenderOverlay (Ptr{vtkViewport},)
@vcall 51 Int32 RenderOpaqueGeometry (Ptr{vtkViewport},)
@vcall 52 Int32 RenderTranslucentPolygonalGeometry (Ptr{vtkViewport},)
@vcall 59 Int32 HasTranslucentPolygonalGeometry ()
@vcall 60 None ReleaseGraphicsResources (Ptr{vtkWindow},)
@scall None ComputeRange (Ptr{Float64}, Ptr{Float64}, Int32, Void, Void) _ZN14vtkAxisActor2D12ComputeRangeEPdS0_iRiRd "libvtkRendering"
@scall Int32 SetMultipleFontSize (Ptr{vtkViewport}, Ptr{Ptr{vtkTextMapper}}, Int32, Ptr{Int32}, Float64, Ptr{Int32}) _ZN14vtkAxisActor2D19SetMultipleFontSizeEP11vtkViewportPP13vtkTextMapperiPidS5_ "libvtkRendering"
@vcall 168 None SetSizeFontRelativeToAxis (Int32,)
@vcall 169 Int32 GetSizeFontRelativeToAxis ()
@vcall 170 None SizeFontRelativeToAxisOn ()
@vcall 171 None SizeFontRelativeToAxisOff ()
@vcall 42 None ShallowCopy (Ptr{vtkProp},)
@vcall 172 None BuildAxis (Ptr{vtkViewport},)
@scall Float64 ComputeStringOffset (Float64, Float64, Float64) _ZN14vtkAxisActor2D19ComputeStringOffsetEddd "libvtkRendering"
@scall None SetOffsetPosition (Ptr{Float64}, Float64, Int32, Int32, Int32, Ptr{vtkActor2D}) _ZN14vtkAxisActor2D17SetOffsetPositionEPddiiiP10vtkActor2D "libvtkRendering"
@vcall 173 None UpdateAdjustedRange ()
@mcall None vtkAxisActor2D_eq (Void,) _ZN14vtkAxisActor2DaSERKS_ "libvtkRendering"
