cur_class = vtkAbstractCellLocator
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkAbstractCellLocator} NewInstance () _ZNK22vtkAbstractCellLocator11NewInstanceEv "libvtkFiltering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 41 None SetNumberOfCellsPerNode (Int32,)
@vcall 42 Int32 GetNumberOfCellsPerNodeMinValue ()
@vcall 43 Int32 GetNumberOfCellsPerNodeMaxValue ()
@vcall 44 Int32 GetNumberOfCellsPerNode ()
@vcall 45 None SetCacheCellBounds (Int32,)
@vcall 46 Int32 GetCacheCellBounds ()
@vcall 47 None CacheCellBoundsOn ()
@vcall 48 None CacheCellBoundsOff ()
@vcall 49 None SetRetainCellLists (Int32,)
@vcall 50 Int32 GetRetainCellLists ()
@vcall 51 None RetainCellListsOn ()
@vcall 52 None RetainCellListsOff ()
@vcall 53 None SetLazyEvaluation (Int32,)
@vcall 54 Int32 GetLazyEvaluation ()
@vcall 55 None LazyEvaluationOn ()
@vcall 56 None LazyEvaluationOff ()
@vcall 57 None SetUseExistingSearchStructure (Int32,)
@vcall 58 Int32 GetUseExistingSearchStructure ()
@vcall 59 None UseExistingSearchStructureOn ()
@vcall 60 None UseExistingSearchStructureOff ()
@vcall 61 Int32 IntersectWithLine (Ptr{Float64}, Ptr{Float64}, Float64, Void, Ptr{Float64}, Ptr{Float64}, Void)
@vcall 62 Int32 IntersectWithLine (Ptr{Float64}, Ptr{Float64}, Float64, Void, Ptr{Float64}, Ptr{Float64}, Void, Void)
@vcall 63 Int32 IntersectWithLine (Ptr{Float64}, Ptr{Float64}, Float64, Void, Ptr{Float64}, Ptr{Float64}, Void, Void, Ptr{vtkGenericCell})
@vcall 64 Int32 IntersectWithLine (Ptr{Float64}, Ptr{Float64}, Ptr{vtkPoints}, Ptr{vtkIdList})
@vcall 65 None FindClosestPoint (Ptr{Float64}, Ptr{Float64}, Void, Void, Void)
@vcall 66 None FindClosestPoint (Ptr{Float64}, Ptr{Float64}, Ptr{vtkGenericCell}, Void, Void, Void)
@vcall 67 vtkIdType FindClosestPointWithinRadius (Ptr{Float64}, Float64, Ptr{Float64}, Void, Void, Void)
@vcall 68 vtkIdType FindClosestPointWithinRadius (Ptr{Float64}, Float64, Ptr{Float64}, Ptr{vtkGenericCell}, Void, Void, Void)
@vcall 69 vtkIdType FindClosestPointWithinRadius (Ptr{Float64}, Float64, Ptr{Float64}, Ptr{vtkGenericCell}, Void, Void, Void, Void)
@vcall 70 None FindCellsWithinBounds (Ptr{Float64}, Ptr{vtkIdList})
@vcall 71 None FindCellsAlongLine (Ptr{Float64}, Ptr{Float64}, Float64, Ptr{vtkIdList})
@vcall 72 vtkIdType FindCell (Ptr{Float64},)
@vcall 73 vtkIdType FindCell (Ptr{Float64}, Float64, Ptr{vtkGenericCell}, Ptr{Float64}, Ptr{Float64})
@vcall 74 Bool InsideCellBounds (Ptr{Float64}, vtkIdType)
@vcall 75 Bool StoreCellBounds ()
@vcall 76 None FreeCellBounds ()
@mcall None vtkAbstractCellLocator_eq (Void,) _ZN22vtkAbstractCellLocatoraSERKS_ "libvtkFiltering"
