cur_class = vtkByteSwap
@scall Ptr{vtkByteSwap} vtkByteSwapNew () _ZN11vtkByteSwap3NewEv "libvtkCommon"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN11vtkByteSwap8IsTypeOfEPKc "libvtkCommon"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkByteSwap} SafeDownCast (Ptr{vtkObjectBase},) _ZN11vtkByteSwap12SafeDownCastEP13vtkObjectBase "libvtkCommon"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkByteSwap} NewInstance () _ZNK11vtkByteSwap11NewInstanceEv "libvtkCommon"
@scall None SwapLE (Ptr{Float32},) _ZN11vtkByteSwap6SwapLEEPf "libvtkCommon"
@scall None SwapBE (Ptr{Float32},) _ZN11vtkByteSwap6SwapBEEPf "libvtkCommon"
@scall None SwapLERange (Ptr{Float32}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPfx "libvtkCommon"
@scall None SwapBERange (Ptr{Float32}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPfx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Float32}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKfxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Float32}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKfxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Float32}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKfxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Float32}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKfxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Float64},) _ZN11vtkByteSwap6SwapLEEPd "libvtkCommon"
@scall None SwapBE (Ptr{Float64},) _ZN11vtkByteSwap6SwapBEEPd "libvtkCommon"
@scall None SwapLERange (Ptr{Float64}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPdx "libvtkCommon"
@scall None SwapBERange (Ptr{Float64}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPdx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Float64}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKdxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Float64}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKdxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Float64}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKdxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Float64}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKdxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Uint8},) _ZN11vtkByteSwap6SwapLEEPc "libvtkCommon"
@scall None SwapBE (Ptr{Uint8},) _ZN11vtkByteSwap6SwapBEEPc "libvtkCommon"
@scall None SwapLERange (Ptr{Uint8}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPcx "libvtkCommon"
@scall None SwapBERange (Ptr{Uint8}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPcx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKcxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKcxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKcxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKcxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Int16},) _ZN11vtkByteSwap6SwapLEEPs "libvtkCommon"
@scall None SwapBE (Ptr{Int16},) _ZN11vtkByteSwap6SwapBEEPs "libvtkCommon"
@scall None SwapLERange (Ptr{Int16}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPsx "libvtkCommon"
@scall None SwapBERange (Ptr{Int16}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPsx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Int16}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKsxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Int16}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKsxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Int16}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKsxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Int16}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKsxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Int32},) _ZN11vtkByteSwap6SwapLEEPi "libvtkCommon"
@scall None SwapBE (Ptr{Int32},) _ZN11vtkByteSwap6SwapBEEPi "libvtkCommon"
@scall None SwapLERange (Ptr{Int32}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPix "libvtkCommon"
@scall None SwapBERange (Ptr{Int32}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPix "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Int32}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKixP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Int32}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKixP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Int32}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKixPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Int32}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKixPSo "libvtkCommon"
@scall None SwapLE (Ptr{Int64},) _ZN11vtkByteSwap6SwapLEEPl "libvtkCommon"
@scall None SwapBE (Ptr{Int64},) _ZN11vtkByteSwap6SwapBEEPl "libvtkCommon"
@scall None SwapLERange (Ptr{Int64}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPlx "libvtkCommon"
@scall None SwapBERange (Ptr{Int64}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPlx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Int64}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKlxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Int64}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKlxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Int64}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKlxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Int64}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKlxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Uint8},) _ZN11vtkByteSwap6SwapLEEPa "libvtkCommon"
@scall None SwapBE (Ptr{Uint8},) _ZN11vtkByteSwap6SwapBEEPa "libvtkCommon"
@scall None SwapLERange (Ptr{Uint8}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPax "libvtkCommon"
@scall None SwapBERange (Ptr{Uint8}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPax "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKaxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKaxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKaxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKaxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Uint8},) _ZN11vtkByteSwap6SwapLEEPh "libvtkCommon"
@scall None SwapBE (Ptr{Uint8},) _ZN11vtkByteSwap6SwapBEEPh "libvtkCommon"
@scall None SwapLERange (Ptr{Uint8}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPhx "libvtkCommon"
@scall None SwapBERange (Ptr{Uint8}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPhx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKhxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKhxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKhxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Uint8}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKhxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Uint16},) _ZN11vtkByteSwap6SwapLEEPt "libvtkCommon"
@scall None SwapBE (Ptr{Uint16},) _ZN11vtkByteSwap6SwapBEEPt "libvtkCommon"
@scall None SwapLERange (Ptr{Uint16}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPtx "libvtkCommon"
@scall None SwapBERange (Ptr{Uint16}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPtx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Uint16}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKtxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Uint16}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKtxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Uint16}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKtxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Uint16}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKtxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Uint32},) _ZN11vtkByteSwap6SwapLEEPj "libvtkCommon"
@scall None SwapBE (Ptr{Uint32},) _ZN11vtkByteSwap6SwapBEEPj "libvtkCommon"
@scall None SwapLERange (Ptr{Uint32}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPjx "libvtkCommon"
@scall None SwapBERange (Ptr{Uint32}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPjx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Uint32}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKjxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Uint32}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKjxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Uint32}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKjxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Uint32}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKjxPSo "libvtkCommon"
@scall None SwapLE (Ptr{Uint64},) _ZN11vtkByteSwap6SwapLEEPm "libvtkCommon"
@scall None SwapBE (Ptr{Uint64},) _ZN11vtkByteSwap6SwapBEEPm "libvtkCommon"
@scall None SwapLERange (Ptr{Uint64}, vtkIdType) _ZN11vtkByteSwap11SwapLERangeEPmx "libvtkCommon"
@scall None SwapBERange (Ptr{Uint64}, vtkIdType) _ZN11vtkByteSwap11SwapBERangeEPmx "libvtkCommon"
@scall Bool SwapLERangeWrite (Ptr{Uint64}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapLERangeWriteEPKmxP8_IO_FILE "libvtkCommon"
@scall Bool SwapBERangeWrite (Ptr{Uint64}, vtkIdType, Ptr{FILE}) _ZN11vtkByteSwap16SwapBERangeWriteEPKmxP8_IO_FILE "libvtkCommon"
@scall None SwapLERangeWrite (Ptr{Uint64}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapLERangeWriteEPKmxPSo "libvtkCommon"
@scall None SwapBERangeWrite (Ptr{Uint64}, vtkIdType, Ptr{ostream}) _ZN11vtkByteSwap16SwapBERangeWriteEPKmxPSo "libvtkCommon"
@scall None Swap2LE (Ptr{None},) _ZN11vtkByteSwap7Swap2LEEPv "libvtkCommon"
@scall None Swap4LE (Ptr{None},) _ZN11vtkByteSwap7Swap4LEEPv "libvtkCommon"
@scall None Swap8LE (Ptr{None},) _ZN11vtkByteSwap7Swap8LEEPv "libvtkCommon"
@scall None Swap2LERange (Ptr{None}, Int32) _ZN11vtkByteSwap12Swap2LERangeEPvi "libvtkCommon"
@scall None Swap4LERange (Ptr{None}, Int32) _ZN11vtkByteSwap12Swap4LERangeEPvi "libvtkCommon"
@scall None Swap8LERange (Ptr{None}, Int32) _ZN11vtkByteSwap12Swap8LERangeEPvi "libvtkCommon"
@scall Bool SwapWrite2LERange (Ptr{None}, Int32, Ptr{FILE}) _ZN11vtkByteSwap17SwapWrite2LERangeEPKviP8_IO_FILE "libvtkCommon"
@scall Bool SwapWrite4LERange (Ptr{None}, Int32, Ptr{FILE}) _ZN11vtkByteSwap17SwapWrite4LERangeEPKviP8_IO_FILE "libvtkCommon"
@scall Bool SwapWrite8LERange (Ptr{None}, Int32, Ptr{FILE}) _ZN11vtkByteSwap17SwapWrite8LERangeEPKviP8_IO_FILE "libvtkCommon"
@scall None SwapWrite2LERange (Ptr{None}, Int32, Ptr{ostream}) _ZN11vtkByteSwap17SwapWrite2LERangeEPKviPSo "libvtkCommon"
@scall None SwapWrite4LERange (Ptr{None}, Int32, Ptr{ostream}) _ZN11vtkByteSwap17SwapWrite4LERangeEPKviPSo "libvtkCommon"
@scall None SwapWrite8LERange (Ptr{None}, Int32, Ptr{ostream}) _ZN11vtkByteSwap17SwapWrite8LERangeEPKviPSo "libvtkCommon"
@scall None Swap2BE (Ptr{None},) _ZN11vtkByteSwap7Swap2BEEPv "libvtkCommon"
@scall None Swap4BE (Ptr{None},) _ZN11vtkByteSwap7Swap4BEEPv "libvtkCommon"
@scall None Swap8BE (Ptr{None},) _ZN11vtkByteSwap7Swap8BEEPv "libvtkCommon"
@scall None Swap2BERange (Ptr{None}, Int32) _ZN11vtkByteSwap12Swap2BERangeEPvi "libvtkCommon"
@scall None Swap4BERange (Ptr{None}, Int32) _ZN11vtkByteSwap12Swap4BERangeEPvi "libvtkCommon"
@scall None Swap8BERange (Ptr{None}, Int32) _ZN11vtkByteSwap12Swap8BERangeEPvi "libvtkCommon"
@scall Bool SwapWrite2BERange (Ptr{None}, Int32, Ptr{FILE}) _ZN11vtkByteSwap17SwapWrite2BERangeEPKviP8_IO_FILE "libvtkCommon"
@scall Bool SwapWrite4BERange (Ptr{None}, Int32, Ptr{FILE}) _ZN11vtkByteSwap17SwapWrite4BERangeEPKviP8_IO_FILE "libvtkCommon"
@scall Bool SwapWrite8BERange (Ptr{None}, Int32, Ptr{FILE}) _ZN11vtkByteSwap17SwapWrite8BERangeEPKviP8_IO_FILE "libvtkCommon"
@scall None SwapWrite2BERange (Ptr{None}, Int32, Ptr{ostream}) _ZN11vtkByteSwap17SwapWrite2BERangeEPKviPSo "libvtkCommon"
@scall None SwapWrite4BERange (Ptr{None}, Int32, Ptr{ostream}) _ZN11vtkByteSwap17SwapWrite4BERangeEPKviPSo "libvtkCommon"
@scall None SwapWrite8BERange (Ptr{None}, Int32, Ptr{ostream}) _ZN11vtkByteSwap17SwapWrite8BERangeEPKviPSo "libvtkCommon"
@scall None SwapVoidRange (Ptr{None}, Int32, Int32) _ZN11vtkByteSwap13SwapVoidRangeEPvii "libvtkCommon"
@mcall None vtkByteSwap_eq (Void,) _ZN11vtkByteSwapaSERKS_ "libvtkCommon"
