@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN16vtkContourFilter8IsTypeOfEPKc "libvtkFiltering"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{Void} SafeDownCast (Ptr{Void},) _ZN16vtkContourFilter12SafeDownCastEP13vtkObjectBase "libvtkFiltering"
@vcall 15 Ptr{Void} NewInstanceInternal ()
@vcall 4 None PrintSelf (Void, Void)
@scall Ptr{Void} New () _ZN16vtkContourFilter3NewEv "libvtkFiltering"
@vcall 19 Uint64 GetMTime ()
@vcall 65 None SetComputeNormals (Int32,)
@vcall 66 Int32 GetComputeNormals ()
@vcall 67 None ComputeNormalsOn ()
@vcall 68 None ComputeNormalsOff ()
@vcall 69 None SetComputeGradients (Int32,)
@vcall 70 Int32 GetComputeGradients ()
@vcall 71 None ComputeGradientsOn ()
@vcall 72 None ComputeGradientsOff ()
@vcall 73 None SetComputeScalars (Int32,)
@vcall 74 Int32 GetComputeScalars ()
@vcall 75 None ComputeScalarsOn ()
@vcall 76 None ComputeScalarsOff ()
@vcall 77 None SetUseScalarTree (Int32,)
@vcall 78 Int32 GetUseScalarTree ()
@vcall 79 None UseScalarTreeOn ()
@vcall 80 None UseScalarTreeOff ()
@vcall 81 None SetScalarTree (Ptr{Void},)
@vcall 82 Ptr{Void} GetScalarTree ()
@vcall 83 Ptr{Void} GetLocator ()
@vcall 21 Int32 ProcessRequest (Ptr{Void}, Ptr{Ptr{Void}}, Ptr{Void})
@vcall 14 None ReportReferences (Ptr{Void},)
@vcall 61 Int32 RequestData (Ptr{Void}, Ptr{Ptr{Void}}, Ptr{Void})
@vcall 62 Int32 RequestUpdateExtent (Ptr{Void}, Ptr{Ptr{Void}}, Ptr{Void})
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{Void})
