cur_class = vtkCleanPolyData
@scall Ptr{vtkCleanPolyData} vtkCleanPolyDataNew () _ZN16vtkCleanPolyData3NewEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN16vtkCleanPolyData8IsTypeOfEPKc "libvtkGraphics"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkCleanPolyData} SafeDownCast (Ptr{vtkObjectBase},) _ZN16vtkCleanPolyData12SafeDownCastEP13vtkObjectBase "libvtkGraphics"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkCleanPolyData} NewInstance () _ZNK16vtkCleanPolyData11NewInstanceEv "libvtkGraphics"
@vcall 65 None SetToleranceIsAbsolute (Int32,)
@vcall 66 None ToleranceIsAbsoluteOn ()
@vcall 67 None ToleranceIsAbsoluteOff ()
@vcall 68 Int32 GetToleranceIsAbsolute ()
@vcall 69 None SetTolerance (Float64,)
@vcall 70 Float64 GetToleranceMinValue ()
@vcall 71 Float64 GetToleranceMaxValue ()
@vcall 72 Float64 GetTolerance ()
@vcall 73 None SetAbsoluteTolerance (Float64,)
@vcall 74 Float64 GetAbsoluteToleranceMinValue ()
@vcall 75 Float64 GetAbsoluteToleranceMaxValue ()
@vcall 76 Float64 GetAbsoluteTolerance ()
@vcall 77 None SetConvertLinesToPoints (Int32,)
@vcall 78 None ConvertLinesToPointsOn ()
@vcall 79 None ConvertLinesToPointsOff ()
@vcall 80 Int32 GetConvertLinesToPoints ()
@vcall 81 None SetConvertPolysToLines (Int32,)
@vcall 82 None ConvertPolysToLinesOn ()
@vcall 83 None ConvertPolysToLinesOff ()
@vcall 84 Int32 GetConvertPolysToLines ()
@vcall 85 None SetConvertStripsToPolys (Int32,)
@vcall 86 None ConvertStripsToPolysOn ()
@vcall 87 None ConvertStripsToPolysOff ()
@vcall 88 Int32 GetConvertStripsToPolys ()
@vcall 89 None SetPointMerging (Int32,)
@vcall 90 Int32 GetPointMerging ()
@vcall 91 None PointMergingOn ()
@vcall 92 None PointMergingOff ()
@vcall 93 None SetLocator (Ptr{vtkIncrementalPointLocator},)
@vcall 94 Ptr{vtkIncrementalPointLocator} GetLocator ()
@mcall None CreateDefaultLocator (Ptr{vtkPolyData},) _ZN16vtkCleanPolyData20CreateDefaultLocatorEP11vtkPolyData "libvtkGraphics"
@mcall None ReleaseLocator () _ZN16vtkCleanPolyData14ReleaseLocatorEv "libvtkGraphics"
@vcall 19 Uint64 GetMTime ()
@vcall 95 None OperateOnPoint (Ptr{Float64}, Ptr{Float64})
@vcall 96 None OperateOnBounds (Ptr{Float64}, Ptr{Float64})
@vcall 97 None SetPieceInvariant (Int32,)
@vcall 98 Int32 GetPieceInvariant ()
@vcall 99 None PieceInvariantOn ()
@vcall 100 None PieceInvariantOff ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 60 Int32 RequestInformation (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 62 Int32 RequestUpdateExtent (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkCleanPolyData_eq (Void,) _ZN16vtkCleanPolyDataaSERKS_ "libvtkGraphics"
