cur_class = vtkContext2D
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN12vtkContext2D8IsTypeOfEPKc "libvtkCharts"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkContext2D} SafeDownCast (Ptr{vtkObjectBase},) _ZN12vtkContext2D12SafeDownCastEP13vtkObjectBase "libvtkCharts"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkContext2D} NewInstance () _ZNK12vtkContext2D11NewInstanceEv "libvtkCharts"
@vcall 4 None PrintSelf (Void, vtkIndent)
@scall Ptr{vtkContext2D} vtkContext2DNew () _ZN12vtkContext2D3NewEv "libvtkCharts"
@mcall Bool Begin (Ptr{vtkContextDevice2D},) _ZN12vtkContext2D5BeginEP18vtkContextDevice2D "libvtkCharts"
@vcall 20 Ptr{vtkContextDevice2D} GetDevice ()
@mcall Bool End () _ZN12vtkContext2D3EndEv "libvtkCharts"
@mcall Bool GetBufferIdMode () _ZNK12vtkContext2D15GetBufferIdModeEv "libvtkCharts"
@mcall None BufferIdModeBegin (Ptr{vtkAbstractContextBufferId},) _ZN12vtkContext2D17BufferIdModeBeginEP26vtkAbstractContextBufferId "libvtkCharts"
@mcall None BufferIdModeEnd () _ZN12vtkContext2D15BufferIdModeEndEv "libvtkCharts"
@mcall None DrawLine (Float32, Float32, Float32, Float32) _ZN12vtkContext2D8DrawLineEffff "libvtkCharts"
@mcall None DrawLine (Ptr{Float32},) _ZN12vtkContext2D8DrawLineEPf "libvtkCharts"
@mcall None DrawLine (Ptr{vtkPoints2D},) _ZN12vtkContext2D8DrawLineEP11vtkPoints2D "libvtkCharts"
@mcall None DrawPoly (Ptr{Float32}, Ptr{Float32}, Int32) _ZN12vtkContext2D8DrawPolyEPfS0_i "libvtkCharts"
@mcall None DrawPoly (Ptr{vtkPoints2D},) _ZN12vtkContext2D8DrawPolyEP11vtkPoints2D "libvtkCharts"
@mcall None DrawPoly (Ptr{Float32}, Int32) _ZN12vtkContext2D8DrawPolyEPfi "libvtkCharts"
@mcall None DrawPoly (Ptr{Float32}, Int32, Ptr{Uint8}, Int32) _ZN12vtkContext2D8DrawPolyEPfiPhi "libvtkCharts"
@mcall None DrawPoint (Float32, Float32) _ZN12vtkContext2D9DrawPointEff "libvtkCharts"
@mcall None DrawPoints (Ptr{Float32}, Ptr{Float32}, Int32) _ZN12vtkContext2D10DrawPointsEPfS0_i "libvtkCharts"
@mcall None DrawPoints (Ptr{vtkPoints2D},) _ZN12vtkContext2D10DrawPointsEP11vtkPoints2D "libvtkCharts"
@mcall None DrawPoints (Ptr{Float32}, Int32) _ZN12vtkContext2D10DrawPointsEPfi "libvtkCharts"
@mcall None DrawPointSprites (Ptr{vtkImageData}, Ptr{vtkPoints2D}) _ZN12vtkContext2D16DrawPointSpritesEP12vtkImageDataP11vtkPoints2D "libvtkCharts"
@mcall None DrawPointSprites (Ptr{vtkImageData}, Ptr{vtkPoints2D}, Ptr{vtkUnsignedCharArray}) _ZN12vtkContext2D16DrawPointSpritesEP12vtkImageDataP11vtkPoints2DP20vtkUnsignedCharArray "libvtkCharts"
@mcall None DrawPointSprites (Ptr{vtkImageData}, Ptr{Float32}, Int32, Ptr{Uint8}, Int32) _ZN12vtkContext2D16DrawPointSpritesEP12vtkImageDataPfiPhi "libvtkCharts"
@mcall None DrawPointSprites (Ptr{vtkImageData}, Ptr{Float32}, Int32) _ZN12vtkContext2D16DrawPointSpritesEP12vtkImageDataPfi "libvtkCharts"
@mcall None DrawRect (Float32, Float32, Float32, Float32) _ZN12vtkContext2D8DrawRectEffff "libvtkCharts"
@mcall None DrawQuad (Float32, Float32, Float32, Float32, Float32, Float32, Float32, Float32) _ZN12vtkContext2D8DrawQuadEffffffff "libvtkCharts"
@mcall None DrawQuad (Ptr{Float32},) _ZN12vtkContext2D8DrawQuadEPf "libvtkCharts"
@mcall None DrawQuadStrip (Ptr{vtkPoints2D},) _ZN12vtkContext2D13DrawQuadStripEP11vtkPoints2D "libvtkCharts"
@mcall None DrawQuadStrip (Ptr{Float32}, Int32) _ZN12vtkContext2D13DrawQuadStripEPfi "libvtkCharts"
@mcall None DrawPolygon (Ptr{Float32}, Ptr{Float32}, Int32) _ZN12vtkContext2D11DrawPolygonEPfS0_i "libvtkCharts"
@mcall None DrawPolygon (Ptr{vtkPoints2D},) _ZN12vtkContext2D11DrawPolygonEP11vtkPoints2D "libvtkCharts"
@mcall None DrawPolygon (Ptr{Float32}, Int32) _ZN12vtkContext2D11DrawPolygonEPfi "libvtkCharts"
@mcall None DrawEllipse (Float32, Float32, Float32, Float32) _ZN12vtkContext2D11DrawEllipseEffff "libvtkCharts"
@mcall None DrawWedge (Float32, Float32, Float32, Float32, Float32, Float32) _ZN12vtkContext2D9DrawWedgeEffffff "libvtkCharts"
@mcall None DrawEllipseWedge (Float32, Float32, Float32, Float32, Float32, Float32, Float32, Float32) _ZN12vtkContext2D16DrawEllipseWedgeEffffffff "libvtkCharts"
@mcall None DrawArc (Float32, Float32, Float32, Float32, Float32) _ZN12vtkContext2D7DrawArcEfffff "libvtkCharts"
@mcall None DrawEllipticArc (Float32, Float32, Float32, Float32, Float32, Float32) _ZN12vtkContext2D15DrawEllipticArcEffffff "libvtkCharts"
@mcall None DrawImage (Float32, Float32, Ptr{vtkImageData}) _ZN12vtkContext2D9DrawImageEffP12vtkImageData "libvtkCharts"
@mcall None DrawImage (Float32, Float32, Float32, Ptr{vtkImageData}) _ZN12vtkContext2D9DrawImageEfffP12vtkImageData "libvtkCharts"
@mcall None DrawImage (Void, Ptr{vtkImageData}) _ZN12vtkContext2D9DrawImageERK8vtkRectfP12vtkImageData "libvtkCharts"
@mcall None DrawStringRect (Ptr{vtkPoints2D}, Void) _ZN12vtkContext2D14DrawStringRectEP11vtkPoints2DRK12vtkStdString "libvtkCharts"
@mcall None DrawStringRect (Ptr{vtkPoints2D}, Void) _ZN12vtkContext2D14DrawStringRectEP11vtkPoints2DRK16vtkUnicodeString "libvtkCharts"
@mcall None DrawStringRect (Ptr{vtkPoints2D}, Ptr{Uint8}) _ZN12vtkContext2D14DrawStringRectEP11vtkPoints2DPKc "libvtkCharts"
@mcall None DrawString (Ptr{vtkPoints2D}, Void) _ZN12vtkContext2D10DrawStringEP11vtkPoints2DRK12vtkStdString "libvtkCharts"
@mcall None DrawString (Float32, Float32, Void) _ZN12vtkContext2D10DrawStringEffRK12vtkStdString "libvtkCharts"
@mcall None DrawString (Ptr{vtkPoints2D}, Void) _ZN12vtkContext2D10DrawStringEP11vtkPoints2DRK16vtkUnicodeString "libvtkCharts"
@mcall None DrawString (Float32, Float32, Void) _ZN12vtkContext2D10DrawStringEffRK16vtkUnicodeString "libvtkCharts"
@mcall None DrawString (Ptr{vtkPoints2D}, Ptr{Uint8}) _ZN12vtkContext2D10DrawStringEP11vtkPoints2DPKc "libvtkCharts"
@mcall None DrawString (Float32, Float32, Ptr{Uint8}) _ZN12vtkContext2D10DrawStringEffPKc "libvtkCharts"
@mcall None ComputeStringBounds (Void, Ptr{vtkPoints2D}) _ZN12vtkContext2D19ComputeStringBoundsERK12vtkStdStringP11vtkPoints2D "libvtkCharts"
@mcall None ComputeStringBounds (Void, Ptr{Float32}) _ZN12vtkContext2D19ComputeStringBoundsERK12vtkStdStringPf "libvtkCharts"
@mcall None ComputeStringBounds (Void, Ptr{vtkPoints2D}) _ZN12vtkContext2D19ComputeStringBoundsERK16vtkUnicodeStringP11vtkPoints2D "libvtkCharts"
@mcall None ComputeStringBounds (Void, Ptr{Float32}) _ZN12vtkContext2D19ComputeStringBoundsERK16vtkUnicodeStringPf "libvtkCharts"
@mcall None ComputeStringBounds (Ptr{Uint8}, Ptr{vtkPoints2D}) _ZN12vtkContext2D19ComputeStringBoundsEPKcP11vtkPoints2D "libvtkCharts"
@mcall None ComputeStringBounds (Ptr{Uint8}, Ptr{Float32}) _ZN12vtkContext2D19ComputeStringBoundsEPKcPf "libvtkCharts"
@mcall None ApplyPen (Ptr{vtkPen},) _ZN12vtkContext2D8ApplyPenEP6vtkPen "libvtkCharts"
@mcall Ptr{vtkPen} GetPen () _ZN12vtkContext2D6GetPenEv "libvtkCharts"
@mcall None ApplyBrush (Ptr{vtkBrush},) _ZN12vtkContext2D10ApplyBrushEP8vtkBrush "libvtkCharts"
@mcall Ptr{vtkBrush} GetBrush () _ZN12vtkContext2D8GetBrushEv "libvtkCharts"
@mcall None ApplyTextProp (Ptr{vtkTextProperty},) _ZN12vtkContext2D13ApplyTextPropEP15vtkTextProperty "libvtkCharts"
@mcall Ptr{vtkTextProperty} GetTextProp () _ZN12vtkContext2D11GetTextPropEv "libvtkCharts"
@mcall None SetTransform (Ptr{vtkTransform2D},) _ZN12vtkContext2D12SetTransformEP14vtkTransform2D "libvtkCharts"
@mcall Ptr{vtkTransform2D} GetTransform () _ZN12vtkContext2D12GetTransformEv "libvtkCharts"
@mcall None AppendTransform (Ptr{vtkTransform2D},) _ZN12vtkContext2D15AppendTransformEP14vtkTransform2D "libvtkCharts"
@mcall None PushMatrix () _ZN12vtkContext2D10PushMatrixEv "libvtkCharts"
@mcall None PopMatrix () _ZN12vtkContext2D9PopMatrixEv "libvtkCharts"
@mcall None ApplyId (vtkIdType,) _ZN12vtkContext2D7ApplyIdEx "libvtkCharts"
@scall Int32 FloatToInt (Float32,) _ZN12vtkContext2D10FloatToIntEf "libvtkCharts"
@mcall None vtkContext2D_eq (Void,) _ZN12vtkContext2DaSERKS_ "libvtkCharts"
@mcall vtkVector2f CalculateTextPosition (Ptr{vtkPoints2D},) _ZN12vtkContext2D21CalculateTextPositionEP11vtkPoints2D "libvtkCharts"
