cur_class = vtkHierarchicalGraphPipeline
@scall Ptr{vtkHierarchicalGraphPipeline} vtkHierarchicalGraphPipelineNew () _ZN28vtkHierarchicalGraphPipeline3NewEv "libvtkViews"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN28vtkHierarchicalGraphPipeline8IsTypeOfEPKc "libvtkViews"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkHierarchicalGraphPipeline} SafeDownCast (Ptr{vtkObjectBase},) _ZN28vtkHierarchicalGraphPipeline12SafeDownCastEP13vtkObjectBase "libvtkViews"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkHierarchicalGraphPipeline} NewInstance () _ZNK28vtkHierarchicalGraphPipeline11NewInstanceEv "libvtkViews"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 20 Ptr{vtkActor} GetActor ()
@vcall 21 Ptr{vtkActor2D} GetLabelActor ()
@vcall 22 None SetBundlingStrength (Float64,)
@vcall 23 Float64 GetBundlingStrength ()
@vcall 24 None SetLabelArrayName (Ptr{Uint8},)
@vcall 25 Ptr{Uint8} GetLabelArrayName ()
@vcall 26 None SetLabelVisibility (Bool,)
@vcall 27 Bool GetLabelVisibility ()
@vcall 28 None LabelVisibilityOn ()
@vcall 29 None LabelVisibilityOff ()
@vcall 30 None SetLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 31 Ptr{vtkTextProperty} GetLabelTextProperty ()
@vcall 32 None SetColorArrayName (Ptr{Uint8},)
@vcall 33 Ptr{Uint8} GetColorArrayName ()
@vcall 34 None SetColorEdgesByArray (Bool,)
@vcall 35 Bool GetColorEdgesByArray ()
@vcall 36 None ColorEdgesByArrayOn ()
@vcall 37 None ColorEdgesByArrayOff ()
@vcall 38 None SetVisibility (Bool,)
@vcall 39 Bool GetVisibility ()
@vcall 40 None VisibilityOn ()
@vcall 41 None VisibilityOff ()
@vcall 42 Ptr{vtkSelection} ConvertSelection (Ptr{vtkDataRepresentation}, Ptr{vtkSelection})
@vcall 43 None PrepareInputConnections (Ptr{vtkAlgorithmOutput}, Ptr{vtkAlgorithmOutput}, Ptr{vtkAlgorithmOutput})
@vcall 44 None ApplyViewTheme (Ptr{vtkViewTheme},)
@vcall 45 None SetHoverArrayName (Ptr{Uint8},)
@vcall 46 Ptr{Uint8} GetHoverArrayName ()
@vcall 47 None SetSplineType (Int32,)
@vcall 48 Int32 GetSplineType ()
@mcall None RegisterProgress (Ptr{vtkRenderView},) _ZN28vtkHierarchicalGraphPipeline16RegisterProgressEP13vtkRenderView "libvtkViews"
@vcall 49 None SetColorArrayNameInternal (Ptr{Uint8},)
@vcall 50 Ptr{Uint8} GetColorArrayNameInternal ()
@vcall 51 None SetLabelArrayNameInternal (Ptr{Uint8},)
@vcall 52 Ptr{Uint8} GetLabelArrayNameInternal ()
@mcall None vtkHierarchicalGraphPipeline_eq (Void,) _ZN28vtkHierarchicalGraphPipelineaSERKS_ "libvtkViews"
