cur_class = vtkInteractorStyle
@scall Ptr{vtkInteractorStyle} vtkInteractorStyleNew () _ZN18vtkInteractorStyle3NewEv "libvtkRendering"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN18vtkInteractorStyle8IsTypeOfEPKc "libvtkRendering"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkInteractorStyle} SafeDownCast (Ptr{vtkObjectBase},) _ZN18vtkInteractorStyle12SafeDownCastEP13vtkObjectBase "libvtkRendering"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkInteractorStyle} NewInstance () _ZNK18vtkInteractorStyle11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 21 None SetInteractor (Ptr{vtkRenderWindowInteractor},)
@vcall 20 None SetEnabled (Int32,)
@vcall 40 None SetAutoAdjustCameraClippingRange (Int32,)
@vcall 41 Int32 GetAutoAdjustCameraClippingRangeMinValue ()
@vcall 42 Int32 GetAutoAdjustCameraClippingRangeMaxValue ()
@vcall 43 Int32 GetAutoAdjustCameraClippingRange ()
@vcall 44 None AutoAdjustCameraClippingRangeOn ()
@vcall 45 None AutoAdjustCameraClippingRangeOff ()
@mcall None FindPokedRenderer (Int32, Int32) _ZN18vtkInteractorStyle17FindPokedRendererEii "libvtkRendering"
@vcall 46 Int32 GetState ()
@vcall 47 Int32 GetUseTimers ()
@vcall 48 None SetUseTimers (Int32,)
@vcall 49 None UseTimersOn ()
@vcall 50 None UseTimersOff ()
@vcall 51 None SetTimerDuration (Uint64,)
@vcall 52 Uint64 GetTimerDurationMinValue ()
@vcall 53 Uint64 GetTimerDurationMaxValue ()
@vcall 54 Uint64 GetTimerDuration ()
@vcall 55 None SetHandleObservers (Int32,)
@vcall 56 Int32 GetHandleObservers ()
@vcall 57 None HandleObserversOn ()
@vcall 58 None HandleObserversOff ()
@vcall 59 None OnMouseMove ()
@vcall 60 None OnLeftButtonDown ()
@vcall 61 None OnLeftButtonUp ()
@vcall 62 None OnMiddleButtonDown ()
@vcall 63 None OnMiddleButtonUp ()
@vcall 64 None OnRightButtonDown ()
@vcall 65 None OnRightButtonUp ()
@vcall 66 None OnMouseWheelForward ()
@vcall 67 None OnMouseWheelBackward ()
@vcall 37 None OnChar ()
@vcall 68 None OnKeyDown ()
@vcall 69 None OnKeyUp ()
@vcall 70 None OnKeyPress ()
@vcall 71 None OnKeyRelease ()
@vcall 72 None OnExpose ()
@vcall 73 None OnConfigure ()
@vcall 74 None OnEnter ()
@vcall 75 None OnLeave ()
@vcall 76 None OnTimer ()
@vcall 77 None Rotate ()
@vcall 78 None Spin ()
@vcall 79 None Pan ()
@vcall 80 None Dolly ()
@vcall 81 None Zoom ()
@vcall 82 None UniformScale ()
@vcall 83 None StartState (Int32,)
@vcall 84 None StopState ()
@vcall 85 None StartAnimate ()
@vcall 86 None StopAnimate ()
@vcall 87 None StartRotate ()
@vcall 88 None EndRotate ()
@vcall 89 None StartZoom ()
@vcall 90 None EndZoom ()
@vcall 91 None StartPan ()
@vcall 92 None EndPan ()
@vcall 93 None StartSpin ()
@vcall 94 None EndSpin ()
@vcall 95 None StartDolly ()
@vcall 96 None EndDolly ()
@vcall 97 None StartUniformScale ()
@vcall 98 None EndUniformScale ()
@vcall 99 None StartTimer ()
@vcall 100 None EndTimer ()
@vcall 101 None HighlightProp (Ptr{vtkProp},)
@vcall 102 None HighlightActor2D (Ptr{vtkActor2D},)
@vcall 103 None HighlightProp3D (Ptr{vtkProp3D},)
@vcall 104 None SetPickColor (Float64, Float64, Float64)
@vcall 105 None SetPickColor (Ptr{Float64},)
@vcall 106 Ptr{Float64} GetPickColor ()
@vcall 107 None GetPickColor (Ptr{Float64},)
@vcall 108 None SetMouseWheelMotionFactor (Float64,)
@vcall 109 Float64 GetMouseWheelMotionFactor ()
@vcall 110 Ptr{vtkTDxInteractorStyle} GetTDxStyle ()
@vcall 111 None SetTDxStyle (Ptr{vtkTDxInteractorStyle},)
@mcall None DelegateTDxEvent (Uint64, Ptr{None}) _ZN18vtkInteractorStyle16DelegateTDxEventEmPv "libvtkRendering"
@scall None ProcessEvents (Ptr{vtkObject}, Uint64, Ptr{None}, Ptr{None}) _ZN18vtkInteractorStyle13ProcessEventsEP9vtkObjectmPvS2_ "libvtkRendering"
@mcall None vtkInteractorStyle_eq (Void,) _ZN18vtkInteractorStyleaSERKS_ "libvtkRendering"
