cur_class = vtkImageChangeInformation
@scall Ptr{vtkImageChangeInformation} vtkImageChangeInformationNew () _ZN25vtkImageChangeInformation3NewEv "libvtkImaging"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN25vtkImageChangeInformation8IsTypeOfEPKc "libvtkImaging"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkImageChangeInformation} SafeDownCast (Ptr{vtkObjectBase},) _ZN25vtkImageChangeInformation12SafeDownCastEP13vtkObjectBase "libvtkImaging"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkImageChangeInformation} NewInstance () _ZNK25vtkImageChangeInformation11NewInstanceEv "libvtkImaging"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 71 None SetInformationInput (Ptr{vtkImageData},)
@vcall 72 Ptr{vtkImageData} GetInformationInput ()
@vcall 73 None SetOutputExtentStart (Int32, Int32, Int32)
@vcall 74 None SetOutputExtentStart (Ptr{Int32},)
@vcall 75 Ptr{Int32} GetOutputExtentStart ()
@vcall 76 None GetOutputExtentStart (Void, Void, Void)
@vcall 77 None GetOutputExtentStart (Ptr{Int32},)
@vcall 78 None SetOutputSpacing (Float64, Float64, Float64)
@vcall 79 None SetOutputSpacing (Ptr{Float64},)
@vcall 80 Ptr{Float64} GetOutputSpacing ()
@vcall 81 None GetOutputSpacing (Void, Void, Void)
@vcall 82 None GetOutputSpacing (Ptr{Float64},)
@vcall 83 None SetOutputOrigin (Float64, Float64, Float64)
@vcall 84 None SetOutputOrigin (Ptr{Float64},)
@vcall 85 Ptr{Float64} GetOutputOrigin ()
@vcall 86 None GetOutputOrigin (Void, Void, Void)
@vcall 87 None GetOutputOrigin (Ptr{Float64},)
@vcall 88 None SetCenterImage (Int32,)
@vcall 89 None CenterImageOn ()
@vcall 90 None CenterImageOff ()
@vcall 91 Int32 GetCenterImage ()
@vcall 92 None SetExtentTranslation (Int32, Int32, Int32)
@vcall 93 None SetExtentTranslation (Ptr{Int32},)
@vcall 94 Ptr{Int32} GetExtentTranslation ()
@vcall 95 None GetExtentTranslation (Void, Void, Void)
@vcall 96 None GetExtentTranslation (Ptr{Int32},)
@vcall 97 None SetSpacingScale (Float64, Float64, Float64)
@vcall 98 None SetSpacingScale (Ptr{Float64},)
@vcall 99 Ptr{Float64} GetSpacingScale ()
@vcall 100 None GetSpacingScale (Void, Void, Void)
@vcall 101 None GetSpacingScale (Ptr{Float64},)
@vcall 102 None SetOriginTranslation (Float64, Float64, Float64)
@vcall 103 None SetOriginTranslation (Ptr{Float64},)
@vcall 104 Ptr{Float64} GetOriginTranslation ()
@vcall 105 None GetOriginTranslation (Void, Void, Void)
@vcall 106 None GetOriginTranslation (Ptr{Float64},)
@vcall 107 None SetOriginScale (Float64, Float64, Float64)
@vcall 108 None SetOriginScale (Ptr{Float64},)
@vcall 109 Ptr{Float64} GetOriginScale ()
@vcall 110 None GetOriginScale (Void, Void, Void)
@vcall 111 None GetOriginScale (Ptr{Float64},)
@vcall 63 Int32 RequestUpdateExtent (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 62 Int32 RequestInformation (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 65 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@mcall None vtkImageChangeInformation_eq (Void,) _ZN25vtkImageChangeInformationaSERKS_ "libvtkImaging"
