cur_class = vtkInteractorStyleUser
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkInteractorStyleUser} NewInstance () _ZNK22vtkInteractorStyleUser11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 112 Ptr{Int32} GetLastPos ()
@vcall 113 None GetLastPos (Void, Void)
@vcall 114 None GetLastPos (Ptr{Int32},)
@vcall 115 Ptr{Int32} GetOldPos ()
@vcall 116 None GetOldPos (Void, Void)
@vcall 117 None GetOldPos (Ptr{Int32},)
@vcall 118 Int32 GetShiftKey ()
@vcall 119 Int32 GetCtrlKey ()
@vcall 120 Int32 GetChar ()
@vcall 121 Ptr{Uint8} GetKeySym ()
@vcall 122 Int32 GetButton ()
@vcall 59 None OnMouseMove ()
@vcall 60 None OnLeftButtonDown ()
@vcall 61 None OnLeftButtonUp ()
@vcall 62 None OnMiddleButtonDown ()
@vcall 63 None OnMiddleButtonUp ()
@vcall 64 None OnRightButtonDown ()
@vcall 65 None OnRightButtonUp ()
@vcall 37 None OnChar ()
@vcall 70 None OnKeyPress ()
@vcall 71 None OnKeyRelease ()
@vcall 72 None OnExpose ()
@vcall 73 None OnConfigure ()
@vcall 74 None OnEnter ()
@vcall 75 None OnLeave ()
@vcall 76 None OnTimer ()
@mcall None vtkInteractorStyleUser_eq (Void,) _ZN22vtkInteractorStyleUseraSERKS_ "libvtkRendering"
