cur_class = vtkInteractorStyleImage
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkInteractorStyleImage} NewInstance () _ZNK23vtkInteractorStyleImage11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 115 Ptr{Int32} GetWindowLevelStartPosition ()
@vcall 116 None GetWindowLevelStartPosition (Void, Void)
@vcall 117 None GetWindowLevelStartPosition (Ptr{Int32},)
@vcall 118 Ptr{Int32} GetWindowLevelCurrentPosition ()
@vcall 119 None GetWindowLevelCurrentPosition (Void, Void)
@vcall 120 None GetWindowLevelCurrentPosition (Ptr{Int32},)
@vcall 59 None OnMouseMove ()
@vcall 60 None OnLeftButtonDown ()
@vcall 61 None OnLeftButtonUp ()
@vcall 62 None OnMiddleButtonDown ()
@vcall 63 None OnMiddleButtonUp ()
@vcall 64 None OnRightButtonDown ()
@vcall 65 None OnRightButtonUp ()
@vcall 37 None OnChar ()
@vcall 121 None WindowLevel ()
@vcall 122 None Pick ()
@vcall 123 None Slice ()
@vcall 124 None StartWindowLevel ()
@vcall 125 None EndWindowLevel ()
@vcall 126 None StartPick ()
@vcall 127 None EndPick ()
@vcall 128 None StartSlice ()
@vcall 129 None EndSlice ()
@vcall 130 None SetInteractionMode (Int32,)
@vcall 131 Int32 GetInteractionModeMinValue ()
@vcall 132 Int32 GetInteractionModeMaxValue ()
@vcall 133 Int32 GetInteractionMode ()
@mcall None SetInteractionModeToImage2D () _ZN23vtkInteractorStyleImage27SetInteractionModeToImage2DEv "libvtkRendering"
@mcall None SetInteractionModeToImage3D () _ZN23vtkInteractorStyleImage27SetInteractionModeToImage3DEv "libvtkRendering"
@mcall None SetInteractionModeToImageSlicing () _ZN23vtkInteractorStyleImage32SetInteractionModeToImageSlicingEv "libvtkRendering"
@vcall 134 None SetXViewRightVector (Float64, Float64, Float64)
@vcall 135 None SetXViewRightVector (Ptr{Float64},)
@vcall 136 Ptr{Float64} GetXViewRightVector ()
@vcall 137 None GetXViewRightVector (Void, Void, Void)
@vcall 138 None GetXViewRightVector (Ptr{Float64},)
@vcall 139 None SetXViewUpVector (Float64, Float64, Float64)
@vcall 140 None SetXViewUpVector (Ptr{Float64},)
@vcall 141 Ptr{Float64} GetXViewUpVector ()
@vcall 142 None GetXViewUpVector (Void, Void, Void)
@vcall 143 None GetXViewUpVector (Ptr{Float64},)
@vcall 144 None SetYViewRightVector (Float64, Float64, Float64)
@vcall 145 None SetYViewRightVector (Ptr{Float64},)
@vcall 146 Ptr{Float64} GetYViewRightVector ()
@vcall 147 None GetYViewRightVector (Void, Void, Void)
@vcall 148 None GetYViewRightVector (Ptr{Float64},)
@vcall 149 None SetYViewUpVector (Float64, Float64, Float64)
@vcall 150 None SetYViewUpVector (Ptr{Float64},)
@vcall 151 Ptr{Float64} GetYViewUpVector ()
@vcall 152 None GetYViewUpVector (Void, Void, Void)
@vcall 153 None GetYViewUpVector (Ptr{Float64},)
@vcall 154 None SetZViewRightVector (Float64, Float64, Float64)
@vcall 155 None SetZViewRightVector (Ptr{Float64},)
@vcall 156 Ptr{Float64} GetZViewRightVector ()
@vcall 157 None GetZViewRightVector (Void, Void, Void)
@vcall 158 None GetZViewRightVector (Ptr{Float64},)
@vcall 159 None SetZViewUpVector (Float64, Float64, Float64)
@vcall 160 None SetZViewUpVector (Ptr{Float64},)
@vcall 161 Ptr{Float64} GetZViewUpVector ()
@vcall 162 None GetZViewUpVector (Void, Void, Void)
@vcall 163 None GetZViewUpVector (Ptr{Float64},)
@mcall None SetImageOrientation (Ptr{Float64}, Ptr{Float64}) _ZN23vtkInteractorStyleImage19SetImageOrientationEPKdS1_ "libvtkRendering"
@mcall Ptr{vtkImageProperty} GetCurrentImageProperty () _ZN23vtkInteractorStyleImage23GetCurrentImagePropertyEv "libvtkRendering"
@mcall None SetCurrentImageToNthImage (Int32,) _ZN23vtkInteractorStyleImage25SetCurrentImageToNthImageEi "libvtkRendering"
@mcall None vtkInteractorStyleImage_eq (Void,) _ZN23vtkInteractorStyleImageaSERKS_ "libvtkRendering"
