cur_class = vtkImageReader2
@scall Ptr{vtkImageReader2} vtkImageReader2New () _ZN15vtkImageReader23NewEv "libvtkIO"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN15vtkImageReader28IsTypeOfEPKc "libvtkIO"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkImageReader2} SafeDownCast (Ptr{vtkObjectBase},) _ZN15vtkImageReader212SafeDownCastEP13vtkObjectBase "libvtkIO"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkImageReader2} NewInstance () _ZNK15vtkImageReader211NewInstanceEv "libvtkIO"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 71 None SetFileName (Ptr{Uint8},)
@vcall 72 Ptr{Uint8} GetFileName ()
@vcall 73 None SetFileNames (Ptr{vtkStringArray},)
@vcall 74 Ptr{vtkStringArray} GetFileNames ()
@vcall 75 None SetFilePrefix (Ptr{Uint8},)
@vcall 76 Ptr{Uint8} GetFilePrefix ()
@vcall 77 None SetFilePattern (Ptr{Uint8},)
@vcall 78 Ptr{Uint8} GetFilePattern ()
@vcall 79 None SetDataScalarType (Int32,)
@vcall 80 None SetDataScalarTypeToFloat ()
@vcall 81 None SetDataScalarTypeToDouble ()
@vcall 82 None SetDataScalarTypeToInt ()
@vcall 83 None SetDataScalarTypeToUnsignedInt ()
@vcall 84 None SetDataScalarTypeToShort ()
@vcall 85 None SetDataScalarTypeToUnsignedShort ()
@vcall 86 None SetDataScalarTypeToChar ()
@vcall 87 None SetDataScalarTypeToSignedChar ()
@vcall 88 None SetDataScalarTypeToUnsignedChar ()
@vcall 89 Int32 GetDataScalarType ()
@vcall 90 None SetNumberOfScalarComponents (Int32,)
@vcall 91 Int32 GetNumberOfScalarComponents ()
@vcall 92 None SetDataExtent (Int32, Int32, Int32, Int32, Int32, Int32)
@vcall 93 None SetDataExtent (Ptr{Int32},)
@vcall 94 Ptr{Int32} GetDataExtent ()
@vcall 95 None GetDataExtent (Void, Void, Void, Void, Void, Void)
@vcall 96 None GetDataExtent (Ptr{Int32},)
@vcall 97 None SetFileDimensionality (Int32,)
@mcall Int32 GetFileDimensionality () _ZN15vtkImageReader221GetFileDimensionalityEv "libvtkIO"
@vcall 98 None SetDataSpacing (Float64, Float64, Float64)
@vcall 99 None SetDataSpacing (Ptr{Float64},)
@vcall 100 Ptr{Float64} GetDataSpacing ()
@vcall 101 None GetDataSpacing (Void, Void, Void)
@vcall 102 None GetDataSpacing (Ptr{Float64},)
@vcall 103 None SetDataOrigin (Float64, Float64, Float64)
@vcall 104 None SetDataOrigin (Ptr{Float64},)
@vcall 105 Ptr{Float64} GetDataOrigin ()
@vcall 106 None GetDataOrigin (Void, Void, Void)
@vcall 107 None GetDataOrigin (Ptr{Float64},)
@mcall Uint64 GetHeaderSize () _ZN15vtkImageReader213GetHeaderSizeEv "libvtkIO"
@mcall Uint64 GetHeaderSize (Uint64,) _ZN15vtkImageReader213GetHeaderSizeEm "libvtkIO"
@vcall 108 None SetHeaderSize (Uint64,)
@vcall 109 None SetDataByteOrderToBigEndian ()
@vcall 110 None SetDataByteOrderToLittleEndian ()
@vcall 111 Int32 GetDataByteOrder ()
@vcall 112 None SetDataByteOrder (Int32,)
@vcall 113 Ptr{Uint8} GetDataByteOrderAsString ()
@vcall 114 None SetFileNameSliceOffset (Int32,)
@vcall 115 Int32 GetFileNameSliceOffset ()
@vcall 116 None SetFileNameSliceSpacing (Int32,)
@vcall 117 Int32 GetFileNameSliceSpacing ()
@vcall 118 None SetSwapBytes (Int32,)
@vcall 119 Int32 GetSwapBytes ()
@vcall 120 None SwapBytesOn ()
@vcall 121 None SwapBytesOff ()
@mcall Ptr{ifstream} GetFile () _ZN15vtkImageReader27GetFileEv "libvtkIO"
@vcall 122 Ptr{Uint64} GetDataIncrements ()
@vcall 123 None GetDataIncrements (Ptr{Uint64},)
@vcall 124 Int32 OpenFile ()
@vcall 125 None SeekFile (Int32, Int32, Int32)
@vcall 126 None FileLowerLeftOn ()
@vcall 127 None FileLowerLeftOff ()
@vcall 128 Int32 GetFileLowerLeft ()
@vcall 129 None SetFileLowerLeft (Int32,)
@vcall 130 None ComputeInternalFileName (Int32,)
@vcall 131 Ptr{Uint8} GetInternalFileName ()
@vcall 132 Int32 CanReadFile (Ptr{Uint8},)
@vcall 133 Ptr{Uint8} GetFileExtensions ()
@vcall 134 Ptr{Uint8} GetDescriptiveName ()
@vcall 62 Int32 RequestInformation (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 135 None ExecuteInformation ()
@vcall 66 None ExecuteData (Ptr{vtkDataObject},)
@vcall 136 None ComputeDataIncrements ()
