cur_class = vtkImageResize
@scall Ptr{vtkImageResize} vtkImageResizeNew () _ZN14vtkImageResize3NewEv "libvtkImaging"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN14vtkImageResize8IsTypeOfEPKc "libvtkImaging"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkImageResize} SafeDownCast (Ptr{vtkObjectBase},) _ZN14vtkImageResize12SafeDownCastEP13vtkObjectBase "libvtkImaging"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkImageResize} NewInstance () _ZNK14vtkImageResize11NewInstanceEv "libvtkImaging"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 78 None SetResizeMethod (Int32,)
@vcall 79 Int32 GetResizeMethodMinValue ()
@vcall 80 Int32 GetResizeMethodMaxValue ()
@vcall 81 Int32 GetResizeMethod ()
@mcall None SetResizeMethodToOutputDimensions () _ZN14vtkImageResize33SetResizeMethodToOutputDimensionsEv "libvtkImaging"
@mcall None SetResizeMethodToOutputSpacing () _ZN14vtkImageResize30SetResizeMethodToOutputSpacingEv "libvtkImaging"
@mcall None SetResizeMethodToMagnificationFactors () _ZN14vtkImageResize37SetResizeMethodToMagnificationFactorsEv "libvtkImaging"
@vcall 82 Ptr{Uint8} GetResizeMethodAsString ()
@vcall 83 None SetOutputDimensions (Int32, Int32, Int32)
@vcall 84 None SetOutputDimensions (Ptr{Int32},)
@vcall 85 Ptr{Int32} GetOutputDimensions ()
@vcall 86 None GetOutputDimensions (Void, Void, Void)
@vcall 87 None GetOutputDimensions (Ptr{Int32},)
@vcall 88 None SetOutputSpacing (Float64, Float64, Float64)
@vcall 89 None SetOutputSpacing (Ptr{Float64},)
@vcall 90 Ptr{Float64} GetOutputSpacing ()
@vcall 91 None GetOutputSpacing (Void, Void, Void)
@vcall 92 None GetOutputSpacing (Ptr{Float64},)
@vcall 93 None SetMagnificationFactors (Float64, Float64, Float64)
@vcall 94 None SetMagnificationFactors (Ptr{Float64},)
@vcall 95 Ptr{Float64} GetMagnificationFactors ()
@vcall 96 None GetMagnificationFactors (Void, Void, Void)
@vcall 97 None GetMagnificationFactors (Ptr{Float64},)
@vcall 98 None SetBorder (Int32,)
@vcall 99 None BorderOn ()
@vcall 100 None BorderOff ()
@vcall 101 Int32 GetBorder ()
@vcall 102 None SetCropping (Int32,)
@vcall 103 None CroppingOn ()
@vcall 104 None CroppingOff ()
@vcall 105 Int32 GetCropping ()
@vcall 106 None SetCroppingRegion (Float64, Float64, Float64, Float64, Float64, Float64)
@vcall 107 None SetCroppingRegion (Ptr{Float64},)
@vcall 108 Ptr{Float64} GetCroppingRegion ()
@vcall 109 None GetCroppingRegion (Void, Void, Void, Void, Void, Void)
@vcall 110 None GetCroppingRegion (Ptr{Float64},)
@vcall 111 None SetInterpolate (Int32,)
@vcall 112 None InterpolateOn ()
@vcall 113 None InterpolateOff ()
@vcall 114 Int32 GetInterpolate ()
@vcall 115 None SetInterpolator (Ptr{vtkAbstractImageInterpolator},)
@vcall 116 Ptr{vtkAbstractImageInterpolator} GetInterpolator ()
@vcall 19 Uint64 GetMTime ()
@vcall 117 Ptr{vtkAbstractImageInterpolator} GetInternalInterpolator ()
@vcall 62 Int32 RequestInformation (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 63 Int32 RequestUpdateExtent (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 65 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 71 None ThreadedRequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector}, Ptr{Ptr{Ptr{vtkImageData}}}, Ptr{Ptr{vtkImageData}}, Ptr{Int32}, Int32)
@mcall None vtkImageResize_eq (Void,) _ZN14vtkImageResizeaSERKS_ "libvtkImaging"
