cur_class = vtkMySQLQuery
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN13vtkMySQLQuery8IsTypeOfEPKc "libvtkIO"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkMySQLQuery} SafeDownCast (Ptr{vtkObjectBase},) _ZN13vtkMySQLQuery12SafeDownCastEP13vtkObjectBase "libvtkIO"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkMySQLQuery} NewInstance () _ZNK13vtkMySQLQuery11NewInstanceEv "libvtkIO"
@vcall 4 None PrintSelf (Void, vtkIndent)
@scall Ptr{vtkMySQLQuery} vtkMySQLQueryNew () _ZN13vtkMySQLQuery3NewEv "libvtkIO"
@vcall 33 Bool SetQuery (Ptr{Uint8},)
@vcall 20 Bool Execute ()
@vcall 35 Bool BeginTransaction ()
@vcall 36 Bool CommitTransaction ()
@vcall 37 Bool RollbackTransaction ()
@vcall 21 Int32 GetNumberOfFields ()
@vcall 22 Ptr{Uint8} GetFieldName (Int32,)
@vcall 23 Int32 GetFieldType (Int32,)
@vcall 24 Bool NextRow ()
@vcall 27 Bool HasError ()
@vcall 26 vtkVariant DataValue (vtkIdType,)
@vcall 28 Ptr{Uint8} GetLastErrorText ()
@vcall 39 Bool BindParameter (Int32, Uint8)
@vcall 43 Bool BindParameter (Int32, Uint8)
@vcall 40 Bool BindParameter (Int32, Uint16)
@vcall 44 Bool BindParameter (Int32, Int16)
@vcall 41 Bool BindParameter (Int32, Uint32)
@vcall 45 Bool BindParameter (Int32, Int32)
@vcall 42 Bool BindParameter (Int32, Uint64)
@vcall 46 Bool BindParameter (Int32, Int64)
@vcall 47 Bool BindParameter (Int32, vtkTypeUInt64)
@vcall 48 Bool BindParameter (Int32, vtkTypeInt64)
@vcall 49 Bool BindParameter (Int32, Float32)
@vcall 50 Bool BindParameter (Int32, Float64)
@vcall 51 Bool BindParameter (Int32, Ptr{Uint8})
@vcall 52 Bool BindParameter (Int32, Ptr{Uint8}, size_t)
@vcall 53 Bool BindParameter (Int32, Void)
@vcall 55 Bool BindParameter (Int32, Ptr{None}, size_t)
@vcall 56 Bool ClearParameterBindings ()
@vcall 57 vtkStdString EscapeString (vtkStdString, Bool)
@vcall 58 None SetLastErrorText (Ptr{Uint8},)
@mcall None vtkMySQLQuery_eq (Void,) _ZN13vtkMySQLQueryaSERKS_ "libvtkIO"
