cur_class = vtkMINCImageWriter
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN18vtkMINCImageWriter8IsTypeOfEPKc "libvtkIO"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkMINCImageWriter} SafeDownCast (Ptr{vtkObjectBase},) _ZN18vtkMINCImageWriter12SafeDownCastEP13vtkObjectBase "libvtkIO"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkMINCImageWriter} NewInstance () _ZNK18vtkMINCImageWriter11NewInstanceEv "libvtkIO"
@scall Ptr{vtkMINCImageWriter} vtkMINCImageWriterNew () _ZN18vtkMINCImageWriter3NewEv "libvtkIO"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 85 Ptr{Uint8} GetFileExtensions ()
@vcall 86 Ptr{Uint8} GetDescriptiveName ()
@vcall 71 None SetFileName (Ptr{Uint8},)
@vcall 79 None Write ()
@vcall 87 None SetDirectionCosines (Ptr{vtkMatrix4x4},)
@vcall 88 Ptr{vtkMatrix4x4} GetDirectionCosines ()
@vcall 89 None SetRescaleSlope (Float64,)
@vcall 90 Float64 GetRescaleSlope ()
@vcall 91 None SetRescaleIntercept (Float64,)
@vcall 92 Float64 GetRescaleIntercept ()
@vcall 93 None SetImageAttributes (Ptr{vtkMINCImageAttributes},)
@vcall 94 Ptr{vtkMINCImageAttributes} GetImageAttributes ()
@vcall 95 None SetStrictValidation (Int32,)
@vcall 96 None StrictValidationOn ()
@vcall 97 None StrictValidationOff ()
@vcall 98 Int32 GetStrictValidation ()
@vcall 99 None SetHistoryAddition (Ptr{Uint8},)
@vcall 100 Ptr{Uint8} GetHistoryAddition ()
@vcall 101 Int32 OpenNetCDFFile (Ptr{Uint8}, Void)
@vcall 102 Int32 CloseNetCDFFile (Int32,)
@vcall 103 Int32 IndexFromDimensionName (Ptr{Uint8},)
@vcall 104 None ComputePermutationFromOrientation (Ptr{Int32}, Ptr{Int32})
@vcall 105 Int32 CreateMINCDimensions (Ptr{vtkImageData}, Int32, Ptr{Int32})
@vcall 106 Int32 CreateMINCVariables (Ptr{vtkImageData}, Int32, Ptr{Int32})
@vcall 107 Int32 WriteMINCFileAttributes (Ptr{vtkImageData}, Int32)
@vcall 108 Int32 WriteMINCData (Ptr{vtkImageData}, Int32)
@vcall 109 None FindRescale (Void, Void)
@vcall 110 None FindMINCValidRange (Ptr{Float64},)
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@vcall 62 Int32 RequestInformation (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 63 Int32 RequestUpdateExtent (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 65 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkMINCImageWriter_eq (Void,) _ZN18vtkMINCImageWriteraSERKS_ "libvtkIO"
