cur_class = vtkMath
@scall Ptr{vtkMath} vtkMathNew () _ZN7vtkMath3NewEv "libvtkCommon"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN7vtkMath8IsTypeOfEPKc "libvtkCommon"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkMath} SafeDownCast (Ptr{vtkObjectBase},) _ZN7vtkMath12SafeDownCastEP13vtkObjectBase "libvtkCommon"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkMath} NewInstance () _ZNK7vtkMath11NewInstanceEv "libvtkCommon"
@vcall 4 None PrintSelf (Void, vtkIndent)
@scall Float32 Pi () _ZN7vtkMath2PiEv "libvtkCommon"
@scall Float64 DoubleTwoPi () _ZN7vtkMath11DoubleTwoPiEv "libvtkCommon"
@scall Float64 DoublePi () _ZN7vtkMath8DoublePiEv "libvtkCommon"
@scall Float32 RadiansFromDegrees (Float32,) _ZN7vtkMath18RadiansFromDegreesEf "libvtkCommon"
@scall Float64 RadiansFromDegrees (Float64,) _ZN7vtkMath18RadiansFromDegreesEd "libvtkCommon"
@scall Float32 DegreesFromRadians (Float32,) _ZN7vtkMath18DegreesFromRadiansEf "libvtkCommon"
@scall Float64 DegreesFromRadians (Float64,) _ZN7vtkMath18DegreesFromRadiansEd "libvtkCommon"
@scall Int32 Round (Float32,) _ZN7vtkMath5RoundEf "libvtkCommon"
@scall Int32 Round (Float64,) _ZN7vtkMath5RoundEd "libvtkCommon"
@scall Int32 Floor (Float64,) _ZN7vtkMath5FloorEd "libvtkCommon"
@scall Int32 Ceil (Float64,) _ZN7vtkMath4CeilEd "libvtkCommon"
@scall vtkTypeInt64 Factorial (Int32,) _ZN7vtkMath9FactorialEi "libvtkCommon"
@scall vtkTypeInt64 Binomial (Int32, Int32) _ZN7vtkMath8BinomialEii "libvtkCommon"
@scall Ptr{Int32} BeginCombination (Int32, Int32) _ZN7vtkMath16BeginCombinationEii "libvtkCommon"
@scall Int32 NextCombination (Int32, Int32, Ptr{Int32}) _ZN7vtkMath15NextCombinationEiiPi "libvtkCommon"
@scall None FreeCombination (Ptr{Int32},) _ZN7vtkMath15FreeCombinationEPi "libvtkCommon"
@scall None RandomSeed (Int32,) _ZN7vtkMath10RandomSeedEi "libvtkCommon"
@scall Int32 GetSeed () _ZN7vtkMath7GetSeedEv "libvtkCommon"
@scall Float64 Random () _ZN7vtkMath6RandomEv "libvtkCommon"
@scall Float64 Random (Float64, Float64) _ZN7vtkMath6RandomEdd "libvtkCommon"
@scall Float64 Gaussian () _ZN7vtkMath8GaussianEv "libvtkCommon"
@scall Float64 Gaussian (Float64, Float64) _ZN7vtkMath8GaussianEdd "libvtkCommon"
@scall None Add (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath3AddEPKfS1_Pf "libvtkCommon"
@scall None Add (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath3AddEPKdS1_Pd "libvtkCommon"
@scall None Subtract (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath8SubtractEPKfS1_Pf "libvtkCommon"
@scall None Subtract (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8SubtractEPKdS1_Pd "libvtkCommon"
@scall None MultiplyScalar (Ptr{Float32}, Float32) _ZN7vtkMath14MultiplyScalarEPff "libvtkCommon"
@scall None MultiplyScalar2D (Ptr{Float32}, Float32) _ZN7vtkMath16MultiplyScalar2DEPff "libvtkCommon"
@scall None MultiplyScalar (Ptr{Float64}, Float64) _ZN7vtkMath14MultiplyScalarEPdd "libvtkCommon"
@scall None MultiplyScalar2D (Ptr{Float64}, Float64) _ZN7vtkMath16MultiplyScalar2DEPdd "libvtkCommon"
@scall Float32 Dot (Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath3DotEPKfS1_ "libvtkCommon"
@scall Float64 Dot (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath3DotEPKdS1_ "libvtkCommon"
@scall None Outer (Ptr{Float32}, Ptr{Float32}, Ptr{Void}) _ZN7vtkMath5OuterEPKfS1_PA3_f "libvtkCommon"
@scall None Outer (Ptr{Float64}, Ptr{Float64}, Ptr{Void}) _ZN7vtkMath5OuterEPKdS1_PA3_d "libvtkCommon"
@scall None Cross (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath5CrossEPKfS1_Pf "libvtkCommon"
@scall None Cross (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath5CrossEPKdS1_Pd "libvtkCommon"
@scall Float32 Norm (Ptr{Float32}, Int32) _ZN7vtkMath4NormEPKfi "libvtkCommon"
@scall Float64 Norm (Ptr{Float64}, Int32) _ZN7vtkMath4NormEPKdi "libvtkCommon"
@scall Float32 Norm (Ptr{Float32},) _ZN7vtkMath4NormEPKf "libvtkCommon"
@scall Float64 Norm (Ptr{Float64},) _ZN7vtkMath4NormEPKd "libvtkCommon"
@scall Float32 Normalize (Ptr{Float32},) _ZN7vtkMath9NormalizeEPf "libvtkCommon"
@scall Float64 Normalize (Ptr{Float64},) _ZN7vtkMath9NormalizeEPd "libvtkCommon"
@scall None Perpendiculars (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Float64) _ZN7vtkMath14PerpendicularsEPKdPdS2_d "libvtkCommon"
@scall None Perpendiculars (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}, Float64) _ZN7vtkMath14PerpendicularsEPKfPfS2_d "libvtkCommon"
@scall Bool ProjectVector (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath13ProjectVectorEPKfS1_Pf "libvtkCommon"
@scall Bool ProjectVector (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath13ProjectVectorEPKdS1_Pd "libvtkCommon"
@scall Bool ProjectVector2D (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath15ProjectVector2DEPKfS1_Pf "libvtkCommon"
@scall Bool ProjectVector2D (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath15ProjectVector2DEPKdS1_Pd "libvtkCommon"
@scall Float32 Distance2BetweenPoints (Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath22Distance2BetweenPointsEPKfS1_ "libvtkCommon"
@scall Float64 Distance2BetweenPoints (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath22Distance2BetweenPointsEPKdS1_ "libvtkCommon"
@scall Float64 GaussianAmplitude (Float64, Float64) _ZN7vtkMath17GaussianAmplitudeEdd "libvtkCommon"
@scall Float64 GaussianAmplitude (Float64, Float64, Float64) _ZN7vtkMath17GaussianAmplitudeEddd "libvtkCommon"
@scall Float64 GaussianWeight (Float64, Float64) _ZN7vtkMath14GaussianWeightEdd "libvtkCommon"
@scall Float64 GaussianWeight (Float64, Float64, Float64) _ZN7vtkMath14GaussianWeightEddd "libvtkCommon"
@scall Float32 Dot2D (Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath5Dot2DEPKfS1_ "libvtkCommon"
@scall Float64 Dot2D (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath5Dot2DEPKdS1_ "libvtkCommon"
@scall None Outer2D (Ptr{Float32}, Ptr{Float32}, Ptr{Void}) _ZN7vtkMath7Outer2DEPKfS1_PA2_f "libvtkCommon"
@scall None Outer2D (Ptr{Float64}, Ptr{Float64}, Ptr{Void}) _ZN7vtkMath7Outer2DEPKdS1_PA2_d "libvtkCommon"
@scall Float32 Norm2D (Ptr{Float32},) _ZN7vtkMath6Norm2DEPKf "libvtkCommon"
@scall Float64 Norm2D (Ptr{Float64},) _ZN7vtkMath6Norm2DEPKd "libvtkCommon"
@scall Float32 Normalize2D (Ptr{Float32},) _ZN7vtkMath11Normalize2DEPf "libvtkCommon"
@scall Float64 Normalize2D (Ptr{Float64},) _ZN7vtkMath11Normalize2DEPd "libvtkCommon"
@scall Float32 Determinant2x2 (Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath14Determinant2x2EPKfS1_ "libvtkCommon"
@scall Float64 Determinant2x2 (Float64, Float64, Float64, Float64) _ZN7vtkMath14Determinant2x2Edddd "libvtkCommon"
@scall Float64 Determinant2x2 (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath14Determinant2x2EPKdS1_ "libvtkCommon"
@scall None LUFactor3x3 (Ptr{Void}, Ptr{Int32}) _ZN7vtkMath11LUFactor3x3EPA3_fPi "libvtkCommon"
@scall None LUFactor3x3 (Ptr{Void}, Ptr{Int32}) _ZN7vtkMath11LUFactor3x3EPA3_dPi "libvtkCommon"
@scall None LUSolve3x3 (Ptr{Void}, Ptr{Int32}, Ptr{Float32}) _ZN7vtkMath10LUSolve3x3EPA3_KfPKiPf "libvtkCommon"
@scall None LUSolve3x3 (Ptr{Void}, Ptr{Int32}, Ptr{Float64}) _ZN7vtkMath10LUSolve3x3EPA3_KdPKiPd "libvtkCommon"
@scall None LinearSolve3x3 (Ptr{Void}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath14LinearSolve3x3EPA3_KfPS0_Pf "libvtkCommon"
@scall None LinearSolve3x3 (Ptr{Void}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath14LinearSolve3x3EPA3_KdPS0_Pd "libvtkCommon"
@scall None Multiply3x3 (Ptr{Void}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath11Multiply3x3EPA3_KfPS0_Pf "libvtkCommon"
@scall None Multiply3x3 (Ptr{Void}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath11Multiply3x3EPA3_KdPS0_Pd "libvtkCommon"
@scall None Multiply3x3 (Ptr{Void}, Ptr{Void}, Ptr{Void}) _ZN7vtkMath11Multiply3x3EPA3_KfS2_PA3_f "libvtkCommon"
@scall None Multiply3x3 (Ptr{Void}, Ptr{Void}, Ptr{Void}) _ZN7vtkMath11Multiply3x3EPA3_KdS2_PA3_d "libvtkCommon"
@scall None MultiplyMatrix (Ptr{Ptr{Float64}}, Ptr{Ptr{Float64}}, Uint32, Uint32, Uint32, Uint32, Ptr{Ptr{Float64}}) _ZN7vtkMath14MultiplyMatrixEPPKdS2_jjjjPPd "libvtkCommon"
@scall None Transpose3x3 (Ptr{Void}, Ptr{Void}) _ZN7vtkMath12Transpose3x3EPA3_KfPA3_f "libvtkCommon"
@scall None Transpose3x3 (Ptr{Void}, Ptr{Void}) _ZN7vtkMath12Transpose3x3EPA3_KdPA3_d "libvtkCommon"
@scall None Invert3x3 (Ptr{Void}, Ptr{Void}) _ZN7vtkMath9Invert3x3EPA3_KfPA3_f "libvtkCommon"
@scall None Invert3x3 (Ptr{Void}, Ptr{Void}) _ZN7vtkMath9Invert3x3EPA3_KdPA3_d "libvtkCommon"
@scall None Identity3x3 (Ptr{Void},) _ZN7vtkMath11Identity3x3EPA3_f "libvtkCommon"
@scall None Identity3x3 (Ptr{Void},) _ZN7vtkMath11Identity3x3EPA3_d "libvtkCommon"
@scall Float64 Determinant3x3 (Ptr{Void},) _ZN7vtkMath14Determinant3x3EPA3_f "libvtkCommon"
@scall Float64 Determinant3x3 (Ptr{Void},) _ZN7vtkMath14Determinant3x3EPA3_d "libvtkCommon"
@scall Float32 Determinant3x3 (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath14Determinant3x3EPKfS1_S1_ "libvtkCommon"
@scall Float64 Determinant3x3 (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath14Determinant3x3EPKdS1_S1_ "libvtkCommon"
@scall Float64 Determinant3x3 (Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64) _ZN7vtkMath14Determinant3x3Eddddddddd "libvtkCommon"
@scall None QuaternionToMatrix3x3 (Ptr{Float32}, Ptr{Void}) _ZN7vtkMath21QuaternionToMatrix3x3EPKfPA3_f "libvtkCommon"
@scall None QuaternionToMatrix3x3 (Ptr{Float64}, Ptr{Void}) _ZN7vtkMath21QuaternionToMatrix3x3EPKdPA3_d "libvtkCommon"
@scall None Matrix3x3ToQuaternion (Ptr{Void}, Ptr{Float32}) _ZN7vtkMath21Matrix3x3ToQuaternionEPA3_KfPf "libvtkCommon"
@scall None Matrix3x3ToQuaternion (Ptr{Void}, Ptr{Float64}) _ZN7vtkMath21Matrix3x3ToQuaternionEPA3_KdPd "libvtkCommon"
@scall None MultiplyQuaternion (Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath18MultiplyQuaternionEPKfS1_Pf "libvtkCommon"
@scall None MultiplyQuaternion (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath18MultiplyQuaternionEPKdS1_Pd "libvtkCommon"
@scall None Orthogonalize3x3 (Ptr{Void}, Ptr{Void}) _ZN7vtkMath16Orthogonalize3x3EPA3_KfPA3_f "libvtkCommon"
@scall None Orthogonalize3x3 (Ptr{Void}, Ptr{Void}) _ZN7vtkMath16Orthogonalize3x3EPA3_KdPA3_d "libvtkCommon"
@scall None Diagonalize3x3 (Ptr{Void}, Ptr{Float32}, Ptr{Void}) _ZN7vtkMath14Diagonalize3x3EPA3_KfPfPA3_f "libvtkCommon"
@scall None Diagonalize3x3 (Ptr{Void}, Ptr{Float64}, Ptr{Void}) _ZN7vtkMath14Diagonalize3x3EPA3_KdPdPA3_d "libvtkCommon"
@scall None SingularValueDecomposition3x3 (Ptr{Void}, Ptr{Void}, Ptr{Float32}, Ptr{Void}) _ZN7vtkMath29SingularValueDecomposition3x3EPA3_KfPA3_fPfS4_ "libvtkCommon"
@scall None SingularValueDecomposition3x3 (Ptr{Void}, Ptr{Void}, Ptr{Float64}, Ptr{Void}) _ZN7vtkMath29SingularValueDecomposition3x3EPA3_KdPA3_dPdS4_ "libvtkCommon"
@scall Int32 SolveLinearSystem (Ptr{Ptr{Float64}}, Ptr{Float64}, Int32) _ZN7vtkMath17SolveLinearSystemEPPdS0_i "libvtkCommon"
@scall Int32 InvertMatrix (Ptr{Ptr{Float64}}, Ptr{Ptr{Float64}}, Int32) _ZN7vtkMath12InvertMatrixEPPdS1_i "libvtkCommon"
@scall Int32 InvertMatrix (Ptr{Ptr{Float64}}, Ptr{Ptr{Float64}}, Int32, Ptr{Int32}, Ptr{Float64}) _ZN7vtkMath12InvertMatrixEPPdS1_iPiS0_ "libvtkCommon"
@scall Int32 LUFactorLinearSystem (Ptr{Ptr{Float64}}, Ptr{Int32}, Int32) _ZN7vtkMath20LUFactorLinearSystemEPPdPii "libvtkCommon"
@scall Int32 LUFactorLinearSystem (Ptr{Ptr{Float64}}, Ptr{Int32}, Int32, Ptr{Float64}) _ZN7vtkMath20LUFactorLinearSystemEPPdPiiS0_ "libvtkCommon"
@scall None LUSolveLinearSystem (Ptr{Ptr{Float64}}, Ptr{Int32}, Ptr{Float64}, Int32) _ZN7vtkMath19LUSolveLinearSystemEPPdPiS0_i "libvtkCommon"
@scall Float64 EstimateMatrixCondition (Ptr{Ptr{Float64}}, Int32) _ZN7vtkMath23EstimateMatrixConditionEPPdi "libvtkCommon"
@scall Int32 Jacobi (Ptr{Ptr{Float32}}, Ptr{Float32}, Ptr{Ptr{Float32}}) _ZN7vtkMath6JacobiEPPfS0_S1_ "libvtkCommon"
@scall Int32 Jacobi (Ptr{Ptr{Float64}}, Ptr{Float64}, Ptr{Ptr{Float64}}) _ZN7vtkMath6JacobiEPPdS0_S1_ "libvtkCommon"
@scall Int32 JacobiN (Ptr{Ptr{Float32}}, Int32, Ptr{Float32}, Ptr{Ptr{Float32}}) _ZN7vtkMath7JacobiNEPPfiS0_S1_ "libvtkCommon"
@scall Int32 JacobiN (Ptr{Ptr{Float64}}, Int32, Ptr{Float64}, Ptr{Ptr{Float64}}) _ZN7vtkMath7JacobiNEPPdiS0_S1_ "libvtkCommon"
@scall Ptr{Float64} SolveCubic (Float64, Float64, Float64, Float64) _ZN7vtkMath10SolveCubicEdddd "libvtkCommon"
@scall Ptr{Float64} SolveQuadratic (Float64, Float64, Float64) _ZN7vtkMath14SolveQuadraticEddd "libvtkCommon"
@scall Ptr{Float64} SolveLinear (Float64, Float64) _ZN7vtkMath11SolveLinearEdd "libvtkCommon"
@scall Int32 SolveCubic (Float64, Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Ptr{Int32}) _ZN7vtkMath10SolveCubicEddddPdS0_S0_Pi "libvtkCommon"
@scall Int32 SolveQuadratic (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Int32}) _ZN7vtkMath14SolveQuadraticEdddPdS0_Pi "libvtkCommon"
@scall Int32 SolveQuadratic (Ptr{Float64}, Ptr{Float64}, Ptr{Int32}) _ZN7vtkMath14SolveQuadraticEPdS0_Pi "libvtkCommon"
@scall Int32 SolveLinear (Float64, Float64, Ptr{Float64}, Ptr{Int32}) _ZN7vtkMath11SolveLinearEddPdPi "libvtkCommon"
@scall Int32 SolveHomogeneousLeastSquares (Int32, Ptr{Ptr{Float64}}, Int32, Ptr{Ptr{Float64}}) _ZN7vtkMath28SolveHomogeneousLeastSquaresEiPPdiS1_ "libvtkCommon"
@scall Int32 SolveLeastSquares (Int32, Ptr{Ptr{Float64}}, Int32, Ptr{Ptr{Float64}}, Int32, Ptr{Ptr{Float64}}, Int32) _ZN7vtkMath17SolveLeastSquaresEiPPdiS1_iS1_i "libvtkCommon"
@scall None RGBToHSV (Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath8RGBToHSVEPKfPf "libvtkCommon"
@scall None RGBToHSV (Float32, Float32, Float32, Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath8RGBToHSVEfffPfS0_S0_ "libvtkCommon"
@scall Ptr{Float64} RGBToHSV (Ptr{Float64},) _ZN7vtkMath8RGBToHSVEPKd "libvtkCommon"
@scall Ptr{Float64} RGBToHSV (Float64, Float64, Float64) _ZN7vtkMath8RGBToHSVEddd "libvtkCommon"
@scall None RGBToHSV (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8RGBToHSVEPKdPd "libvtkCommon"
@scall None RGBToHSV (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8RGBToHSVEdddPdS0_S0_ "libvtkCommon"
@scall None HSVToRGB (Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath8HSVToRGBEPKfPf "libvtkCommon"
@scall None HSVToRGB (Float32, Float32, Float32, Ptr{Float32}, Ptr{Float32}, Ptr{Float32}) _ZN7vtkMath8HSVToRGBEfffPfS0_S0_ "libvtkCommon"
@scall Ptr{Float64} HSVToRGB (Ptr{Float64},) _ZN7vtkMath8HSVToRGBEPKd "libvtkCommon"
@scall Ptr{Float64} HSVToRGB (Float64, Float64, Float64) _ZN7vtkMath8HSVToRGBEddd "libvtkCommon"
@scall None HSVToRGB (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8HSVToRGBEPKdPd "libvtkCommon"
@scall None HSVToRGB (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8HSVToRGBEdddPdS0_S0_ "libvtkCommon"
@scall None LabToXYZ (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8LabToXYZEPKdPd "libvtkCommon"
@scall None LabToXYZ (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8LabToXYZEdddPdS0_S0_ "libvtkCommon"
@scall Ptr{Float64} LabToXYZ (Ptr{Float64},) _ZN7vtkMath8LabToXYZEPKd "libvtkCommon"
@scall None XYZToLab (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8XYZToLabEPKdPd "libvtkCommon"
@scall None XYZToLab (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8XYZToLabEdddPdS0_S0_ "libvtkCommon"
@scall Ptr{Float64} XYZToLab (Ptr{Float64},) _ZN7vtkMath8XYZToLabEPKd "libvtkCommon"
@scall None XYZToRGB (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8XYZToRGBEPKdPd "libvtkCommon"
@scall None XYZToRGB (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8XYZToRGBEdddPdS0_S0_ "libvtkCommon"
@scall Ptr{Float64} XYZToRGB (Ptr{Float64},) _ZN7vtkMath8XYZToRGBEPKd "libvtkCommon"
@scall None RGBToXYZ (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8RGBToXYZEPKdPd "libvtkCommon"
@scall None RGBToXYZ (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8RGBToXYZEdddPdS0_S0_ "libvtkCommon"
@scall Ptr{Float64} RGBToXYZ (Ptr{Float64},) _ZN7vtkMath8RGBToXYZEPKd "libvtkCommon"
@scall None RGBToLab (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8RGBToLabEPKdPd "libvtkCommon"
@scall None RGBToLab (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8RGBToLabEdddPdS0_S0_ "libvtkCommon"
@scall Ptr{Float64} RGBToLab (Ptr{Float64},) _ZN7vtkMath8RGBToLabEPKd "libvtkCommon"
@scall None LabToRGB (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8LabToRGBEPKdPd "libvtkCommon"
@scall None LabToRGB (Float64, Float64, Float64, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath8LabToRGBEdddPdS0_S0_ "libvtkCommon"
@scall Ptr{Float64} LabToRGB (Ptr{Float64},) _ZN7vtkMath8LabToRGBEPKd "libvtkCommon"
@scall None UninitializeBounds (Ptr{Float64},) _ZN7vtkMath18UninitializeBoundsEPd "libvtkCommon"
@scall Int32 AreBoundsInitialized (Ptr{Float64},) _ZN7vtkMath20AreBoundsInitializedEPd "libvtkCommon"
@scall None ClampValue (Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath10ClampValueEPdPKd "libvtkCommon"
@scall None ClampValue (Float64, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath10ClampValueEdPKdPd "libvtkCommon"
@scall None ClampValues (Ptr{Float64}, Int32, Ptr{Float64}) _ZN7vtkMath11ClampValuesEPdiPKd "libvtkCommon"
@scall None ClampValues (Ptr{Float64}, Int32, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath11ClampValuesEPKdiS1_Pd "libvtkCommon"
@scall Float64 ClampAndNormalizeValue (Float64, Ptr{Float64}) _ZN7vtkMath22ClampAndNormalizeValueEdPKd "libvtkCommon"
@scall Int32 GetScalarTypeFittingRange (Float64, Float64, Float64, Float64) _ZN7vtkMath25GetScalarTypeFittingRangeEdddd "libvtkCommon"
@scall Int32 GetAdjustedScalarRange (Ptr{vtkDataArray}, Int32, Ptr{Float64}) _ZN7vtkMath22GetAdjustedScalarRangeEP12vtkDataArrayiPd "libvtkCommon"
@scall Int32 ExtentIsWithinOtherExtent (Ptr{Int32}, Ptr{Int32}) _ZN7vtkMath25ExtentIsWithinOtherExtentEPiS0_ "libvtkCommon"
@scall Int32 BoundsIsWithinOtherBounds (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath25BoundsIsWithinOtherBoundsEPdS0_S0_ "libvtkCommon"
@scall Int32 PointIsWithinBounds (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath19PointIsWithinBoundsEPdS0_S0_ "libvtkCommon"
@scall Float64 Solve3PointCircle (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN7vtkMath17Solve3PointCircleEPKdS1_S1_Pd "libvtkCommon"
@scall Float64 Inf () _ZN7vtkMath3InfEv "libvtkCommon"
@scall Float64 NegInf () _ZN7vtkMath6NegInfEv "libvtkCommon"
@scall Float64 Nan () _ZN7vtkMath3NanEv "libvtkCommon"
@scall Int32 IsInf (Float64,) _ZN7vtkMath5IsInfEd "libvtkCommon"
@scall Int32 IsNan (Float64,) _ZN7vtkMath5IsNanEd "libvtkCommon"
@mcall None vtkMath_eq (Void,) _ZN7vtkMathaSERKS_ "libvtkCommon"
