cur_class = vtkMatrix4x4
@scall Ptr{vtkMatrix4x4} vtkMatrix4x4New () _ZN12vtkMatrix4x43NewEv "libvtkCommon"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN12vtkMatrix4x48IsTypeOfEPKc "libvtkCommon"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkMatrix4x4} SafeDownCast (Ptr{vtkObjectBase},) _ZN12vtkMatrix4x412SafeDownCastEP13vtkObjectBase "libvtkCommon"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkMatrix4x4} NewInstance () _ZNK12vtkMatrix4x411NewInstanceEv "libvtkCommon"
@vcall 4 None PrintSelf (Void, vtkIndent)
@mcall None DeepCopy (Ptr{vtkMatrix4x4},) _ZN12vtkMatrix4x48DeepCopyEPKS_ "libvtkCommon"
@scall None DeepCopy (Ptr{Float64}, Ptr{vtkMatrix4x4}) _ZN12vtkMatrix4x48DeepCopyEPdPKS_ "libvtkCommon"
@scall None DeepCopy (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x48DeepCopyEPdPKd "libvtkCommon"
@mcall None DeepCopy (Ptr{Float64},) _ZN12vtkMatrix4x48DeepCopyEPKd "libvtkCommon"
@mcall None Zero () _ZN12vtkMatrix4x44ZeroEv "libvtkCommon"
@scall None Zero (Ptr{Float64},) _ZN12vtkMatrix4x44ZeroEPd "libvtkCommon"
@mcall None Identity () _ZN12vtkMatrix4x48IdentityEv "libvtkCommon"
@scall None Identity (Ptr{Float64},) _ZN12vtkMatrix4x48IdentityEPd "libvtkCommon"
@scall None Invert (Ptr{vtkMatrix4x4}, Ptr{vtkMatrix4x4}) _ZN12vtkMatrix4x46InvertEPKS_PS_ "libvtkCommon"
@mcall None Invert () _ZN12vtkMatrix4x46InvertEv "libvtkCommon"
@scall None Invert (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x46InvertEPKdPd "libvtkCommon"
@scall None Transpose (Ptr{vtkMatrix4x4}, Ptr{vtkMatrix4x4}) _ZN12vtkMatrix4x49TransposeEPKS_PS_ "libvtkCommon"
@mcall None Transpose () _ZN12vtkMatrix4x49TransposeEv "libvtkCommon"
@scall None Transpose (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x49TransposeEPKdPd "libvtkCommon"
@mcall None MultiplyPoint (Ptr{Float32}, Ptr{Float32}) _ZN12vtkMatrix4x413MultiplyPointEPKfPf "libvtkCommon"
@mcall None MultiplyPoint (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x413MultiplyPointEPKdPd "libvtkCommon"
@scall None MultiplyPoint (Ptr{Float64}, Ptr{Float32}, Ptr{Float32}) _ZN12vtkMatrix4x413MultiplyPointEPKdPKfPf "libvtkCommon"
@scall None MultiplyPoint (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x413MultiplyPointEPKdS1_Pd "libvtkCommon"
@mcall Ptr{Float32} MultiplyPoint (Ptr{Float32},) _ZN12vtkMatrix4x413MultiplyPointEPKf "libvtkCommon"
@mcall Ptr{Float32} MultiplyFloatPoint (Ptr{Float32},) _ZN12vtkMatrix4x418MultiplyFloatPointEPKf "libvtkCommon"
@mcall Ptr{Float64} MultiplyDoublePoint (Ptr{Float64},) _ZN12vtkMatrix4x419MultiplyDoublePointEPKd "libvtkCommon"
@scall None Multiply4x4 (Ptr{vtkMatrix4x4}, Ptr{vtkMatrix4x4}, Ptr{vtkMatrix4x4}) _ZN12vtkMatrix4x411Multiply4x4EPKS_S1_PS_ "libvtkCommon"
@scall None Multiply4x4 (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x411Multiply4x4EPKdS1_Pd "libvtkCommon"
@mcall None Adjoint (Ptr{vtkMatrix4x4}, Ptr{vtkMatrix4x4}) _ZN12vtkMatrix4x47AdjointEPKS_PS_ "libvtkCommon"
@scall None Adjoint (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x47AdjointEPKdPd "libvtkCommon"
@mcall Float64 Determinant () _ZN12vtkMatrix4x411DeterminantEv "libvtkCommon"
@scall Float64 Determinant (Ptr{Float64},) _ZN12vtkMatrix4x411DeterminantEPKd "libvtkCommon"
@mcall None SetElement (Int32, Int32, Float64) _ZN12vtkMatrix4x410SetElementEiid "libvtkCommon"
@mcall Float64 GetElement (Int32, Int32) _ZNK12vtkMatrix4x410GetElementEii "libvtkCommon"
@mcall Ptr{Float64} operator[] (Uint32,) _ZN12vtkMatrix4x4ixEj "libvtkCommon"
@mcall Ptr{Float64} operator[] (Uint32,) _ZNK12vtkMatrix4x4ixEj "libvtkCommon"
@mcall None Adjoint (Void, Void) _ZN12vtkMatrix4x47AdjointERS_S0_ "libvtkCommon"
@mcall Float64 Determinant (Void,) _ZN12vtkMatrix4x411DeterminantERS_ "libvtkCommon"
@mcall Float64 Determinant (Ptr{vtkMatrix4x4},) _ZN12vtkMatrix4x411DeterminantEPS_ "libvtkCommon"
@mcall None Invert (Void, Void) _ZN12vtkMatrix4x46InvertERS_S0_ "libvtkCommon"
@mcall None Transpose (Void, Void) _ZN12vtkMatrix4x49TransposeERS_S0_ "libvtkCommon"
@scall None PointMultiply (Ptr{Float64}, Ptr{Float32}, Ptr{Float32}) _ZN12vtkMatrix4x413PointMultiplyEPKdPKfPf "libvtkCommon"
@scall None PointMultiply (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix4x413PointMultiplyEPKdS1_Pd "libvtkCommon"
@mcall None vtkMatrix4x4_eq (Void,) _ZN12vtkMatrix4x4aSERKS_ "libvtkCommon"
