cur_class = vtkMatrix3x3
@scall Ptr{vtkMatrix3x3} vtkMatrix3x3New () _ZN12vtkMatrix3x33NewEv "libvtkCommon"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN12vtkMatrix3x38IsTypeOfEPKc "libvtkCommon"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkMatrix3x3} SafeDownCast (Ptr{vtkObjectBase},) _ZN12vtkMatrix3x312SafeDownCastEP13vtkObjectBase "libvtkCommon"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkMatrix3x3} NewInstance () _ZNK12vtkMatrix3x311NewInstanceEv "libvtkCommon"
@vcall 4 None PrintSelf (Void, vtkIndent)
@mcall None DeepCopy (Ptr{vtkMatrix3x3},) _ZN12vtkMatrix3x38DeepCopyEPS_ "libvtkCommon"
@scall None DeepCopy (Ptr{Float64}, Ptr{vtkMatrix3x3}) _ZN12vtkMatrix3x38DeepCopyEPdPS_ "libvtkCommon"
@scall None DeepCopy (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x38DeepCopyEPdPKd "libvtkCommon"
@mcall None DeepCopy (Ptr{Float64},) _ZN12vtkMatrix3x38DeepCopyEPKd "libvtkCommon"
@mcall None Zero () _ZN12vtkMatrix3x34ZeroEv "libvtkCommon"
@scall None Zero (Ptr{Float64},) _ZN12vtkMatrix3x34ZeroEPd "libvtkCommon"
@mcall None Identity () _ZN12vtkMatrix3x38IdentityEv "libvtkCommon"
@scall None Identity (Ptr{Float64},) _ZN12vtkMatrix3x38IdentityEPd "libvtkCommon"
@scall None Invert (Ptr{vtkMatrix3x3}, Ptr{vtkMatrix3x3}) _ZN12vtkMatrix3x36InvertEPS_S0_ "libvtkCommon"
@mcall None Invert () _ZN12vtkMatrix3x36InvertEv "libvtkCommon"
@scall None Invert (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x36InvertEPKdPd "libvtkCommon"
@scall None Transpose (Ptr{vtkMatrix3x3}, Ptr{vtkMatrix3x3}) _ZN12vtkMatrix3x39TransposeEPS_S0_ "libvtkCommon"
@mcall None Transpose () _ZN12vtkMatrix3x39TransposeEv "libvtkCommon"
@scall None Transpose (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x39TransposeEPKdPd "libvtkCommon"
@mcall None MultiplyPoint (Ptr{Float32}, Ptr{Float32}) _ZN12vtkMatrix3x313MultiplyPointEPKfPf "libvtkCommon"
@mcall None MultiplyPoint (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x313MultiplyPointEPKdPd "libvtkCommon"
@scall None MultiplyPoint (Ptr{Float64}, Ptr{Float32}, Ptr{Float32}) _ZN12vtkMatrix3x313MultiplyPointEPKdPKfPf "libvtkCommon"
@scall None MultiplyPoint (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x313MultiplyPointEPKdS1_Pd "libvtkCommon"
@scall None Multiply3x3 (Ptr{vtkMatrix3x3}, Ptr{vtkMatrix3x3}, Ptr{vtkMatrix3x3}) _ZN12vtkMatrix3x311Multiply3x3EPS_S0_S0_ "libvtkCommon"
@scall None Multiply3x3 (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x311Multiply3x3EPKdS1_Pd "libvtkCommon"
@mcall None Adjoint (Ptr{vtkMatrix3x3}, Ptr{vtkMatrix3x3}) _ZN12vtkMatrix3x37AdjointEPS_S0_ "libvtkCommon"
@scall None Adjoint (Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x37AdjointEPKdPd "libvtkCommon"
@mcall Float64 Determinant () _ZN12vtkMatrix3x311DeterminantEv "libvtkCommon"
@scall Float64 Determinant (Ptr{Float64},) _ZN12vtkMatrix3x311DeterminantEPKd "libvtkCommon"
@mcall None SetElement (Int32, Int32, Float64) _ZN12vtkMatrix3x310SetElementEiid "libvtkCommon"
@mcall Float64 GetElement (Int32, Int32) _ZNK12vtkMatrix3x310GetElementEii "libvtkCommon"
@mcall Ptr{Float64} operator[] (Uint32,) _ZN12vtkMatrix3x3ixEj "libvtkCommon"
@mcall Ptr{Float64} operator[] (Uint32,) _ZNK12vtkMatrix3x3ixEj "libvtkCommon"
@mcall Bool operator== (Void,) _ZN12vtkMatrix3x3eqERKS_ "libvtkCommon"
@mcall Bool operator!= (Void,) _ZN12vtkMatrix3x3neERKS_ "libvtkCommon"
@mcall None Adjoint (Void, Void) _ZN12vtkMatrix3x37AdjointERS_S0_ "libvtkCommon"
@mcall Float64 Determinant (Void,) _ZN12vtkMatrix3x311DeterminantERS_ "libvtkCommon"
@mcall Float64 Determinant (Ptr{vtkMatrix3x3},) _ZN12vtkMatrix3x311DeterminantEPS_ "libvtkCommon"
@mcall None Invert (Void, Void) _ZN12vtkMatrix3x36InvertERS_S0_ "libvtkCommon"
@mcall None Transpose (Void, Void) _ZN12vtkMatrix3x39TransposeERS_S0_ "libvtkCommon"
@scall None PointMultiply (Ptr{Float64}, Ptr{Float32}, Ptr{Float32}) _ZN12vtkMatrix3x313PointMultiplyEPKdPKfPf "libvtkCommon"
@scall None PointMultiply (Ptr{Float64}, Ptr{Float64}, Ptr{Float64}) _ZN12vtkMatrix3x313PointMultiplyEPKdS1_Pd "libvtkCommon"
@mcall Bool IsIdentity () _ZN12vtkMatrix3x310IsIdentityEv "libvtkCommon"
@mcall Ptr{Float64} GetData () _ZN12vtkMatrix3x37GetDataEv "libvtkCommon"
@mcall None vtkMatrix3x3_eq (Void,) _ZN12vtkMatrix3x3aSERKS_ "libvtkCommon"
