cur_class = vtkModelMetadata
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkModelMetadata} NewInstance () _ZNK16vtkModelMetadata11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 20 None PrintGlobalInformation ()
@vcall 21 None PrintLocalInformation ()
@vcall 22 None SetTitle (Ptr{Uint8},)
@mcall Ptr{Uint8} GetTitle () _ZNK16vtkModelMetadata8GetTitleEv "libvtkGraphics"
@mcall None SetInformationLines (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata19SetInformationLinesEiPPc "libvtkGraphics"
@mcall None AddInformationLine (Ptr{Uint8},) _ZN16vtkModelMetadata18AddInformationLineEPc "libvtkGraphics"
@mcall Int32 GetInformationLines (Ptr{Ptr{Ptr{Uint8}}},) _ZNK16vtkModelMetadata19GetInformationLinesEPPPc "libvtkGraphics"
@mcall Int32 GetNumberOfInformationLines () _ZNK16vtkModelMetadata27GetNumberOfInformationLinesEv "libvtkGraphics"
@mcall None SetQARecords (Int32, Ptr{Void}) _ZN16vtkModelMetadata12SetQARecordsEiPA4_Pc "libvtkGraphics"
@mcall None AddQARecord (Ptr{Uint8}, Ptr{Uint8}, Ptr{Uint8}, Ptr{Uint8}) _ZN16vtkModelMetadata11AddQARecordEPcS0_S0_S0_ "libvtkGraphics"
@mcall None GetQARecord (Int32, Ptr{Ptr{Uint8}}, Ptr{Ptr{Uint8}}, Ptr{Ptr{Uint8}}, Ptr{Ptr{Uint8}}) _ZNK16vtkModelMetadata11GetQARecordEiPPcS1_S1_S1_ "libvtkGraphics"
@mcall Int32 GetNumberOfQARecords () _ZNK16vtkModelMetadata20GetNumberOfQARecordsEv "libvtkGraphics"
@vcall 23 None SetTimeStepIndex (Int32,)
@mcall Int32 GetTimeStepIndex () _ZNK16vtkModelMetadata16GetTimeStepIndexEv "libvtkGraphics"
@mcall None SetTimeSteps (Int32, Ptr{Float32}) _ZN16vtkModelMetadata12SetTimeStepsEiPf "libvtkGraphics"
@mcall Int32 GetNumberOfTimeSteps () _ZNK16vtkModelMetadata20GetNumberOfTimeStepsEv "libvtkGraphics"
@mcall Ptr{Float32} GetTimeStepValues () _ZNK16vtkModelMetadata17GetTimeStepValuesEv "libvtkGraphics"
@mcall None SetCoordinateNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata18SetCoordinateNamesEiPPc "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetCoordinateNames () _ZNK16vtkModelMetadata18GetCoordinateNamesEv "libvtkGraphics"
@mcall Int32 GetDimension () _ZNK16vtkModelMetadata12GetDimensionEv "libvtkGraphics"
@vcall 24 None SetNumberOfBlocks (Int32,)
@mcall Int32 GetNumberOfBlocks () _ZNK16vtkModelMetadata17GetNumberOfBlocksEv "libvtkGraphics"
@mcall None SetBlockIds (Ptr{Int32},) _ZN16vtkModelMetadata11SetBlockIdsEPi "libvtkGraphics"
@mcall Ptr{Int32} GetBlockIds () _ZNK16vtkModelMetadata11GetBlockIdsEv "libvtkGraphics"
@mcall None SetBlockElementType (Ptr{Ptr{Uint8}},) _ZN16vtkModelMetadata19SetBlockElementTypeEPPc "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetBlockElementType () _ZNK16vtkModelMetadata19GetBlockElementTypeEv "libvtkGraphics"
@mcall Int32 SetBlockNumberOfElements (Ptr{Int32},) _ZN16vtkModelMetadata24SetBlockNumberOfElementsEPi "libvtkGraphics"
@mcall Ptr{Int32} GetBlockNumberOfElements () _ZNK16vtkModelMetadata24GetBlockNumberOfElementsEv "libvtkGraphics"
@mcall None SetBlockNodesPerElement (Ptr{Int32},) _ZN16vtkModelMetadata23SetBlockNodesPerElementEPi "libvtkGraphics"
@mcall Ptr{Int32} GetBlockNodesPerElement () _ZNK16vtkModelMetadata23GetBlockNodesPerElementEv "libvtkGraphics"
@mcall None SetBlockElementIdList (Ptr{Int32},) _ZN16vtkModelMetadata21SetBlockElementIdListEPi "libvtkGraphics"
@mcall Ptr{Int32} GetBlockElementIdList () _ZNK16vtkModelMetadata21GetBlockElementIdListEv "libvtkGraphics"
@mcall Int32 GetSumElementsPerBlock () _ZNK16vtkModelMetadata22GetSumElementsPerBlockEv "libvtkGraphics"
@mcall Ptr{Int32} GetBlockElementIdListIndex () _ZNK16vtkModelMetadata26GetBlockElementIdListIndexEv "libvtkGraphics"
@mcall Int32 SetBlockNumberOfAttributesPerElement (Ptr{Int32},) _ZN16vtkModelMetadata36SetBlockNumberOfAttributesPerElementEPi "libvtkGraphics"
@mcall Ptr{Int32} GetBlockNumberOfAttributesPerElement () _ZNK16vtkModelMetadata36GetBlockNumberOfAttributesPerElementEv "libvtkGraphics"
@mcall None SetBlockAttributes (Ptr{Float32},) _ZN16vtkModelMetadata18SetBlockAttributesEPf "libvtkGraphics"
@mcall Ptr{Float32} GetBlockAttributes () _ZNK16vtkModelMetadata18GetBlockAttributesEv "libvtkGraphics"
@mcall Int32 GetSizeBlockAttributeArray () _ZNK16vtkModelMetadata26GetSizeBlockAttributeArrayEv "libvtkGraphics"
@mcall Ptr{Int32} GetBlockAttributesIndex () _ZNK16vtkModelMetadata23GetBlockAttributesIndexEv "libvtkGraphics"
@vcall 25 None SetNumberOfNodeSets (Int32,)
@mcall Int32 GetNumberOfNodeSets () _ZNK16vtkModelMetadata19GetNumberOfNodeSetsEv "libvtkGraphics"
@mcall None SetNodeSetIds (Ptr{Int32},) _ZN16vtkModelMetadata13SetNodeSetIdsEPi "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetIds () _ZNK16vtkModelMetadata13GetNodeSetIdsEv "libvtkGraphics"
@mcall Int32 SetNodeSetSize (Ptr{Int32},) _ZN16vtkModelMetadata14SetNodeSetSizeEPi "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetSize () _ZNK16vtkModelMetadata14GetNodeSetSizeEv "libvtkGraphics"
@mcall None SetNodeSetNodeIdList (Ptr{Int32},) _ZN16vtkModelMetadata20SetNodeSetNodeIdListEPi "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetNodeIdList () _ZNK16vtkModelMetadata20GetNodeSetNodeIdListEv "libvtkGraphics"
@mcall Int32 SetNodeSetNumberOfDistributionFactors (Ptr{Int32},) _ZN16vtkModelMetadata37SetNodeSetNumberOfDistributionFactorsEPi "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetNumberOfDistributionFactors () _ZNK16vtkModelMetadata37GetNodeSetNumberOfDistributionFactorsEv "libvtkGraphics"
@mcall None SetNodeSetDistributionFactors (Ptr{Float32},) _ZN16vtkModelMetadata29SetNodeSetDistributionFactorsEPf "libvtkGraphics"
@mcall Ptr{Float32} GetNodeSetDistributionFactors () _ZNK16vtkModelMetadata29GetNodeSetDistributionFactorsEv "libvtkGraphics"
@mcall Int32 GetSumNodesPerNodeSet () _ZNK16vtkModelMetadata21GetSumNodesPerNodeSetEv "libvtkGraphics"
@mcall Int32 GetSumDistFactPerNodeSet () _ZNK16vtkModelMetadata24GetSumDistFactPerNodeSetEv "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetNodeIdListIndex () _ZNK16vtkModelMetadata25GetNodeSetNodeIdListIndexEv "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetDistributionFactorIndex () _ZNK16vtkModelMetadata33GetNodeSetDistributionFactorIndexEv "libvtkGraphics"
@vcall 26 None SetNumberOfSideSets (Int32,)
@mcall Int32 GetNumberOfSideSets () _ZNK16vtkModelMetadata19GetNumberOfSideSetsEv "libvtkGraphics"
@mcall None SetSideSetIds (Ptr{Int32},) _ZN16vtkModelMetadata13SetSideSetIdsEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetIds () _ZNK16vtkModelMetadata13GetSideSetIdsEv "libvtkGraphics"
@mcall Int32 SetSideSetSize (Ptr{Int32},) _ZN16vtkModelMetadata14SetSideSetSizeEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetSize () _ZNK16vtkModelMetadata14GetSideSetSizeEv "libvtkGraphics"
@mcall Int32 SetSideSetNumberOfDistributionFactors (Ptr{Int32},) _ZN16vtkModelMetadata37SetSideSetNumberOfDistributionFactorsEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetNumberOfDistributionFactors () _ZNK16vtkModelMetadata37GetSideSetNumberOfDistributionFactorsEv "libvtkGraphics"
@mcall None SetSideSetElementList (Ptr{Int32},) _ZN16vtkModelMetadata21SetSideSetElementListEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetElementList () _ZNK16vtkModelMetadata21GetSideSetElementListEv "libvtkGraphics"
@mcall None SetSideSetSideList (Ptr{Int32},) _ZN16vtkModelMetadata18SetSideSetSideListEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetSideList () _ZNK16vtkModelMetadata18GetSideSetSideListEv "libvtkGraphics"
@mcall None SetSideSetNumDFPerSide (Ptr{Int32},) _ZN16vtkModelMetadata22SetSideSetNumDFPerSideEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetNumDFPerSide () _ZNK16vtkModelMetadata22GetSideSetNumDFPerSideEv "libvtkGraphics"
@mcall None SetSideSetDistributionFactors (Ptr{Float32},) _ZN16vtkModelMetadata29SetSideSetDistributionFactorsEPf "libvtkGraphics"
@mcall Ptr{Float32} GetSideSetDistributionFactors () _ZNK16vtkModelMetadata29GetSideSetDistributionFactorsEv "libvtkGraphics"
@mcall Int32 GetSumSidesPerSideSet () _ZNK16vtkModelMetadata21GetSumSidesPerSideSetEv "libvtkGraphics"
@mcall Int32 GetSumDistFactPerSideSet () _ZNK16vtkModelMetadata24GetSumDistFactPerSideSetEv "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetListIndex () _ZNK16vtkModelMetadata19GetSideSetListIndexEv "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetDistributionFactorIndex () _ZNK16vtkModelMetadata33GetSideSetDistributionFactorIndexEv "libvtkGraphics"
@mcall Int32 GetNumberOfBlockProperties () _ZNK16vtkModelMetadata26GetNumberOfBlockPropertiesEv "libvtkGraphics"
@mcall None SetBlockPropertyNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata21SetBlockPropertyNamesEiPPc "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetBlockPropertyNames () _ZNK16vtkModelMetadata21GetBlockPropertyNamesEv "libvtkGraphics"
@mcall None SetBlockPropertyValue (Ptr{Int32},) _ZN16vtkModelMetadata21SetBlockPropertyValueEPi "libvtkGraphics"
@mcall Ptr{Int32} GetBlockPropertyValue () _ZNK16vtkModelMetadata21GetBlockPropertyValueEv "libvtkGraphics"
@mcall Int32 GetNumberOfNodeSetProperties () _ZNK16vtkModelMetadata28GetNumberOfNodeSetPropertiesEv "libvtkGraphics"
@mcall None SetNodeSetPropertyNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata23SetNodeSetPropertyNamesEiPPc "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetNodeSetPropertyNames () _ZNK16vtkModelMetadata23GetNodeSetPropertyNamesEv "libvtkGraphics"
@mcall None SetNodeSetPropertyValue (Ptr{Int32},) _ZN16vtkModelMetadata23SetNodeSetPropertyValueEPi "libvtkGraphics"
@mcall Ptr{Int32} GetNodeSetPropertyValue () _ZNK16vtkModelMetadata23GetNodeSetPropertyValueEv "libvtkGraphics"
@mcall Int32 GetNumberOfSideSetProperties () _ZNK16vtkModelMetadata28GetNumberOfSideSetPropertiesEv "libvtkGraphics"
@mcall None SetSideSetPropertyNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata23SetSideSetPropertyNamesEiPPc "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetSideSetPropertyNames () _ZNK16vtkModelMetadata23GetSideSetPropertyNamesEv "libvtkGraphics"
@mcall None SetSideSetPropertyValue (Ptr{Int32},) _ZN16vtkModelMetadata23SetSideSetPropertyValueEPi "libvtkGraphics"
@mcall Ptr{Int32} GetSideSetPropertyValue () _ZNK16vtkModelMetadata23GetSideSetPropertyValueEv "libvtkGraphics"
@mcall Int32 GetNumberOfGlobalVariables () _ZNK16vtkModelMetadata26GetNumberOfGlobalVariablesEv "libvtkGraphics"
@mcall None SetGlobalVariableNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata22SetGlobalVariableNamesEiPPc "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetGlobalVariableNames () _ZNK16vtkModelMetadata22GetGlobalVariableNamesEv "libvtkGraphics"
@mcall None SetGlobalVariableValue (Ptr{Float32},) _ZN16vtkModelMetadata22SetGlobalVariableValueEPf "libvtkGraphics"
@mcall Ptr{Float32} GetGlobalVariableValue () _ZNK16vtkModelMetadata22GetGlobalVariableValueEv "libvtkGraphics"
@mcall None SetElementVariableInfo (Int32, Ptr{Ptr{Uint8}}, Int32, Ptr{Ptr{Uint8}}, Ptr{Int32}, Ptr{Int32}) _ZN16vtkModelMetadata22SetElementVariableInfoEiPPciS1_PiS2_ "libvtkGraphics"
@mcall None SetNodeVariableInfo (Int32, Ptr{Ptr{Uint8}}, Int32, Ptr{Ptr{Uint8}}, Ptr{Int32}, Ptr{Int32}) _ZN16vtkModelMetadata19SetNodeVariableInfoEiPPciS1_PiS2_ "libvtkGraphics"
@mcall None SetElementVariableTruthTable (Ptr{Int32},) _ZN16vtkModelMetadata28SetElementVariableTruthTableEPi "libvtkGraphics"
@mcall Ptr{Int32} GetElementVariableTruthTable () _ZNK16vtkModelMetadata28GetElementVariableTruthTableEv "libvtkGraphics"
@vcall 27 None SetAllVariablesDefinedInAllBlocks (Int32,)
@vcall 28 None AllVariablesDefinedInAllBlocksOn ()
@vcall 29 None AllVariablesDefinedInAllBlocksOff ()
@mcall Int32 GetAllVariablesDefinedInAllBlocks () _ZNK16vtkModelMetadata33GetAllVariablesDefinedInAllBlocksEv "libvtkGraphics"
@mcall Int32 ElementVariableIsDefinedInBlock (Ptr{Uint8}, Int32) _ZN16vtkModelMetadata31ElementVariableIsDefinedInBlockEPci "libvtkGraphics"
@mcall Int32 GetOriginalNumberOfElementVariables () _ZNK16vtkModelMetadata35GetOriginalNumberOfElementVariablesEv "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetOriginalElementVariableNames () _ZNK16vtkModelMetadata31GetOriginalElementVariableNamesEv "libvtkGraphics"
@mcall Int32 GetNumberOfElementVariables () _ZNK16vtkModelMetadata27GetNumberOfElementVariablesEv "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetElementVariableNames () _ZNK16vtkModelMetadata23GetElementVariableNamesEv "libvtkGraphics"
@mcall Ptr{Int32} GetElementVariableNumberOfComponents () _ZNK16vtkModelMetadata36GetElementVariableNumberOfComponentsEv "libvtkGraphics"
@mcall Ptr{Int32} GetMapToOriginalElementVariableNames () _ZNK16vtkModelMetadata36GetMapToOriginalElementVariableNamesEv "libvtkGraphics"
@mcall Int32 GetOriginalNumberOfNodeVariables () _ZNK16vtkModelMetadata32GetOriginalNumberOfNodeVariablesEv "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetOriginalNodeVariableNames () _ZNK16vtkModelMetadata28GetOriginalNodeVariableNamesEv "libvtkGraphics"
@mcall Int32 GetNumberOfNodeVariables () _ZNK16vtkModelMetadata24GetNumberOfNodeVariablesEv "libvtkGraphics"
@mcall Ptr{Ptr{Uint8}} GetNodeVariableNames () _ZNK16vtkModelMetadata20GetNodeVariableNamesEv "libvtkGraphics"
@mcall Ptr{Int32} GetNodeVariableNumberOfComponents () _ZNK16vtkModelMetadata33GetNodeVariableNumberOfComponentsEv "libvtkGraphics"
@mcall Ptr{Int32} GetMapToOriginalNodeVariableNames () _ZNK16vtkModelMetadata33GetMapToOriginalNodeVariableNamesEv "libvtkGraphics"
@mcall Ptr{Uint8} FindOriginalElementVariableName (Ptr{Uint8}, Int32) _ZN16vtkModelMetadata31FindOriginalElementVariableNameEPKci "libvtkGraphics"
@mcall Ptr{Uint8} FindOriginalNodeVariableName (Ptr{Uint8}, Int32) _ZN16vtkModelMetadata28FindOriginalNodeVariableNameEPKci "libvtkGraphics"
@mcall None Pack (Ptr{vtkDataSet},) _ZN16vtkModelMetadata4PackEP10vtkDataSet "libvtkGraphics"
@mcall Int32 Unpack (Ptr{vtkDataSet}, Int32) _ZN16vtkModelMetadata6UnpackEP10vtkDataSeti "libvtkGraphics"
@mcall Int32 AddUGridElementVariable (Ptr{Uint8}, Ptr{Uint8}, Int32) _ZN16vtkModelMetadata23AddUGridElementVariableEPcS0_i "libvtkGraphics"
@mcall Int32 RemoveUGridElementVariable (Ptr{Uint8},) _ZN16vtkModelMetadata26RemoveUGridElementVariableEPc "libvtkGraphics"
@mcall Int32 AddUGridNodeVariable (Ptr{Uint8}, Ptr{Uint8}, Int32) _ZN16vtkModelMetadata20AddUGridNodeVariableEPcS0_i "libvtkGraphics"
@mcall Int32 RemoveUGridNodeVariable (Ptr{Uint8},) _ZN16vtkModelMetadata23RemoveUGridNodeVariableEPc "libvtkGraphics"
@mcall Int32 MergeModelMetadata (Ptr{vtkModelMetadata},) _ZN16vtkModelMetadata18MergeModelMetadataEPKS_ "libvtkGraphics"
@mcall Int32 MergeGlobalInformation (Ptr{vtkModelMetadata},) _ZN16vtkModelMetadata22MergeGlobalInformationEPKS_ "libvtkGraphics"
@mcall Ptr{vtkModelMetadata} ExtractModelMetadata (Ptr{vtkIdTypeArray}, Ptr{vtkDataSet}) _ZN16vtkModelMetadata20ExtractModelMetadataEP14vtkIdTypeArrayP10vtkDataSet "libvtkGraphics"
@mcall Ptr{vtkModelMetadata} ExtractGlobalMetadata () _ZN16vtkModelMetadata21ExtractGlobalMetadataEv "libvtkGraphics"
@mcall None FreeAllGlobalData () _ZN16vtkModelMetadata17FreeAllGlobalDataEv "libvtkGraphics"
@mcall None FreeAllLocalData () _ZN16vtkModelMetadata16FreeAllLocalDataEv "libvtkGraphics"
@mcall None FreeBlockDependentData () _ZN16vtkModelMetadata22FreeBlockDependentDataEv "libvtkGraphics"
@mcall None FreeOriginalElementVariableNames () _ZN16vtkModelMetadata32FreeOriginalElementVariableNamesEv "libvtkGraphics"
@mcall None FreeOriginalNodeVariableNames () _ZN16vtkModelMetadata29FreeOriginalNodeVariableNamesEv "libvtkGraphics"
@mcall None FreeUsedElementVariableNames () _ZN16vtkModelMetadata28FreeUsedElementVariableNamesEv "libvtkGraphics"
@mcall None FreeUsedNodeVariableNames () _ZN16vtkModelMetadata25FreeUsedNodeVariableNamesEv "libvtkGraphics"
@mcall None FreeUsedElementVariables () _ZN16vtkModelMetadata24FreeUsedElementVariablesEv "libvtkGraphics"
@mcall None FreeUsedNodeVariables () _ZN16vtkModelMetadata21FreeUsedNodeVariablesEv "libvtkGraphics"
@mcall None Reset () _ZN16vtkModelMetadata5ResetEv "libvtkGraphics"
@mcall Int32 GetBlockLocalIndex (Int32,) _ZN16vtkModelMetadata18GetBlockLocalIndexEi "libvtkGraphics"
@mcall None InitializeAllMetadata () _ZN16vtkModelMetadata21InitializeAllMetadataEv "libvtkGraphics"
@mcall None InitializeAllIvars () _ZN16vtkModelMetadata18InitializeAllIvarsEv "libvtkGraphics"
@mcall None FreeAllMetadata () _ZN16vtkModelMetadata15FreeAllMetadataEv "libvtkGraphics"
@mcall None FreeAllIvars () _ZN16vtkModelMetadata12FreeAllIvarsEv "libvtkGraphics"
@mcall None FreeQARecords () _ZN16vtkModelMetadata13FreeQARecordsEv "libvtkGraphics"
@mcall Int32 BuildBlockElementIdListIndex () _ZN16vtkModelMetadata28BuildBlockElementIdListIndexEv "libvtkGraphics"
@mcall Int32 BuildBlockAttributesIndex () _ZN16vtkModelMetadata25BuildBlockAttributesIndexEv "libvtkGraphics"
@mcall Int32 BuildNodeSetNodeIdListIndex () _ZN16vtkModelMetadata27BuildNodeSetNodeIdListIndexEv "libvtkGraphics"
@mcall Int32 BuildNodeSetDistributionFactorIndex () _ZN16vtkModelMetadata35BuildNodeSetDistributionFactorIndexEv "libvtkGraphics"
@mcall Int32 BuildSideSetListIndex () _ZN16vtkModelMetadata21BuildSideSetListIndexEv "libvtkGraphics"
@mcall Int32 BuildSideSetDistributionFactorIndex () _ZN16vtkModelMetadata35BuildSideSetDistributionFactorIndexEv "libvtkGraphics"
@mcall Int32 InitializeFromSizeArray (Ptr{vtkIntArray}, Void, Void) _ZN16vtkModelMetadata23InitializeFromSizeArrayEP11vtkIntArrayRiS2_ "libvtkGraphics"
@mcall Ptr{vtkIntArray} PackSizeArray (Int32, Int32) _ZN16vtkModelMetadata13PackSizeArrayEii "libvtkGraphics"
@mcall Int32 InitializeFromIntArray (Ptr{vtkModelMetadata}, Ptr{vtkIntArray}) _ZN16vtkModelMetadata22InitializeFromIntArrayEPS_P11vtkIntArray "libvtkGraphics"
@mcall Ptr{vtkIntArray} PackIntArray () _ZN16vtkModelMetadata12PackIntArrayEv "libvtkGraphics"
@mcall Int32 InitializeFromCharArray (Ptr{vtkModelMetadata}, Ptr{vtkCharArray}, Int32, Int32) _ZN16vtkModelMetadata23InitializeFromCharArrayEPS_P12vtkCharArrayii "libvtkGraphics"
@mcall Ptr{vtkCharArray} PackCharArray (Int32, Int32) _ZN16vtkModelMetadata13PackCharArrayEii "libvtkGraphics"
@mcall Int32 InitializeFromFloatArray (Ptr{vtkFloatArray},) _ZN16vtkModelMetadata24InitializeFromFloatArrayEP13vtkFloatArray "libvtkGraphics"
@mcall Ptr{vtkFloatArray} PackFloatArray () _ZN16vtkModelMetadata14PackFloatArrayEv "libvtkGraphics"
@mcall Int32 MergeIdLists (Int32, Ptr{Int32}, Ptr{Int32}, Int32, Ptr{Float32}, Ptr{Int32}, Int32, Ptr{Int32}, Ptr{Int32}, Int32, Ptr{Float32}, Ptr{Int32}, Int32, Ptr{Ptr{Int32}}, Ptr{Ptr{Int32}}, Ptr{Int32}, Ptr{Ptr{Float32}}, Ptr{Ptr{Int32}}, Ptr{Int32}) _ZN16vtkModelMetadata12MergeIdListsEiPiS0_iPfS0_iS0_S0_iS1_S0_iPS0_S2_S0_PS1_S2_S0_ "libvtkGraphics"
@mcall Int32 AppendFloatLists (Int32, Ptr{Float32}, Ptr{Int32}, Int32, Ptr{Float32}, Ptr{Int32}, Int32, Ptr{Ptr{Float32}}, Ptr{Ptr{Int32}}, Ptr{Int32}) _ZN16vtkModelMetadata16AppendFloatListsEiPfPiiS0_S1_iPS0_PS1_S1_ "libvtkGraphics"
@mcall Int32 AppendIntegerLists (Int32, Ptr{Int32}, Ptr{Int32}, Int32, Ptr{Int32}, Ptr{Int32}, Int32, Ptr{Ptr{Int32}}, Ptr{Ptr{Int32}}, Ptr{Int32}) _ZN16vtkModelMetadata18AppendIntegerListsEiPiS0_iS0_S0_iPS0_S1_S0_ "libvtkGraphics"
@mcall None ExtractCellsFromBlockData (Ptr{vtkModelMetadataSTLCloak}, Ptr{vtkModelMetadata}) _ZN16vtkModelMetadata25ExtractCellsFromBlockDataEP24vtkModelMetadataSTLCloakPS_ "libvtkGraphics"
@mcall None ExtractNodesFromNodeSetData (Ptr{vtkModelMetadataSTLCloak}, Ptr{vtkModelMetadata}) _ZN16vtkModelMetadata27ExtractNodesFromNodeSetDataEP24vtkModelMetadataSTLCloakPS_ "libvtkGraphics"
@mcall None ExtractSidesFromSideSetData (Ptr{vtkModelMetadataSTLCloak}, Ptr{vtkModelMetadata}) _ZN16vtkModelMetadata27ExtractSidesFromSideSetDataEP24vtkModelMetadataSTLCloakPS_ "libvtkGraphics"
@mcall None ShowFloats (Ptr{Uint8}, Int32, Ptr{Float32}) _ZN16vtkModelMetadata10ShowFloatsEPKciPf "libvtkGraphics"
@mcall None ShowLines (Ptr{Uint8}, Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata9ShowLinesEPKciPPc "libvtkGraphics"
@mcall None ShowIntArray (Ptr{Uint8}, Int32, Int32, Ptr{Int32}) _ZN16vtkModelMetadata12ShowIntArrayEPKciiPi "libvtkGraphics"
@mcall None ShowInts (Ptr{Uint8}, Int32, Ptr{Int32}) _ZN16vtkModelMetadata8ShowIntsEPKciPi "libvtkGraphics"
@mcall None ShowListsOfInts (Ptr{Uint8}, Ptr{Int32}, Int32, Ptr{Int32}, Int32, Int32) _ZN16vtkModelMetadata15ShowListsOfIntsEPKcPiiS2_ii "libvtkGraphics"
@mcall None ShowListsOfFloats (Ptr{Uint8}, Ptr{Float32}, Int32, Ptr{Int32}, Int32, Int32) _ZN16vtkModelMetadata17ShowListsOfFloatsEPKcPfiPiii "libvtkGraphics"
@mcall None SetOriginalElementVariableNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata31SetOriginalElementVariableNamesEiPPc "libvtkGraphics"
@mcall None SetElementVariableNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata23SetElementVariableNamesEiPPc "libvtkGraphics"
@mcall None SetElementVariableNumberOfComponents (Ptr{Int32},) _ZN16vtkModelMetadata36SetElementVariableNumberOfComponentsEPi "libvtkGraphics"
@mcall None SetMapToOriginalElementVariableNames (Ptr{Int32},) _ZN16vtkModelMetadata36SetMapToOriginalElementVariableNamesEPi "libvtkGraphics"
@mcall None SetOriginalNodeVariableNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata28SetOriginalNodeVariableNamesEiPPc "libvtkGraphics"
@mcall None SetNodeVariableNames (Int32, Ptr{Ptr{Uint8}}) _ZN16vtkModelMetadata20SetNodeVariableNamesEiPPc "libvtkGraphics"
@mcall None SetNodeVariableNumberOfComponents (Ptr{Int32},) _ZN16vtkModelMetadata33SetNodeVariableNumberOfComponentsEPi "libvtkGraphics"
@mcall None SetMapToOriginalNodeVariableNames (Ptr{Int32},) _ZN16vtkModelMetadata33SetMapToOriginalNodeVariableNamesEPi "libvtkGraphics"
@mcall Int32 CalculateMaximumLengths (Void, Void) _ZN16vtkModelMetadata23CalculateMaximumLengthsERiS0_ "libvtkGraphics"
@mcall None vtkModelMetadata_eq (Void,) _ZN16vtkModelMetadataaSERKS_ "libvtkGraphics"
