cur_class = vtkMaskPoints
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkMaskPoints} NewInstance () _ZNK13vtkMaskPoints11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetOnRatio (Int32,)
@vcall 66 Int32 GetOnRatioMinValue ()
@vcall 67 Int32 GetOnRatioMaxValue ()
@vcall 68 Int32 GetOnRatio ()
@vcall 69 None SetMaximumNumberOfPoints (vtkIdType,)
@vcall 70 vtkIdType GetMaximumNumberOfPointsMinValue ()
@vcall 71 vtkIdType GetMaximumNumberOfPointsMaxValue ()
@vcall 72 vtkIdType GetMaximumNumberOfPoints ()
@vcall 73 None SetOffset (vtkIdType,)
@vcall 74 vtkIdType GetOffsetMinValue ()
@vcall 75 vtkIdType GetOffsetMaxValue ()
@vcall 76 vtkIdType GetOffset ()
@vcall 77 None SetRandomMode (Int32,)
@vcall 78 Int32 GetRandomMode ()
@vcall 79 None RandomModeOn ()
@vcall 80 None RandomModeOff ()
@vcall 81 None SetRandomModeType (Int32,)
@vcall 82 Int32 GetRandomModeTypeMinValue ()
@vcall 83 Int32 GetRandomModeTypeMaxValue ()
@vcall 84 Int32 GetRandomModeType ()
@vcall 85 None SetProportionalMaximumNumberOfPoints (Int32,)
@vcall 86 Int32 GetProportionalMaximumNumberOfPoints ()
@vcall 87 None ProportionalMaximumNumberOfPointsOn ()
@vcall 88 None ProportionalMaximumNumberOfPointsOff ()
@vcall 89 None SetGenerateVertices (Int32,)
@vcall 90 Int32 GetGenerateVertices ()
@vcall 91 None GenerateVerticesOn ()
@vcall 92 None GenerateVerticesOff ()
@vcall 93 None SetSingleVertexPerCell (Int32,)
@vcall 94 Int32 GetSingleVertexPerCell ()
@vcall 95 None SingleVertexPerCellOn ()
@vcall 96 None SingleVertexPerCellOff ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@vcall 97 None InternalScatter (Ptr{Uint64}, Ptr{Uint64}, Int32, Int32)
@vcall 98 None InternalGather (Ptr{Uint64}, Ptr{Uint64}, Int32, Int32)
@vcall 99 Int32 InternalGetNumberOfProcesses ()
@vcall 100 Int32 InternalGetLocalProcessId ()
@vcall 101 None InternalBarrier ()
@mcall Uint64 GetLocalSampleSize (vtkIdType, Int32) _ZN13vtkMaskPoints18GetLocalSampleSizeExi "libvtkGraphics"
@mcall None vtkMaskPoints_eq (Void,) _ZN13vtkMaskPointsaSERKS_ "libvtkGraphics"
