cur_class = vtkOSOpenGLRenderWindow
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkOSOpenGLRenderWindow} NewInstance () _ZNK23vtkOSOpenGLRenderWindow11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 73 None Start ()
@vcall 75 None Frame ()
@vcall 206 None WindowInitialize ()
@vcall 207 None Initialize ()
@vcall 74 None Finalize ()
@vcall 84 None SetFullScreen (Int32,)
@vcall 34 None SetSize (Int32, Int32)
@vcall 35 None SetSize (Ptr{Int32},)
@vcall 36 Ptr{Int32} GetScreenSize ()
@vcall 30 Ptr{Int32} GetPosition ()
@vcall 31 None SetPosition (Int32, Int32)
@vcall 32 None SetPosition (Ptr{Int32},)
@vcall 95 None SetStereoCapableWindow (Int32,)
@vcall 62 None MakeCurrent ()
@vcall 176 Bool IsCurrent ()
@vcall 177 None SetForceMakeCurrent ()
@vcall 178 Ptr{Uint8} ReportCapabilities ()
@vcall 179 Int32 SupportsOpenGL ()
@vcall 180 Int32 IsDirect ()
@vcall 127 None WindowRemap ()
@vcall 23 Ptr{None} GetGenericDisplayId ()
@vcall 24 Ptr{None} GetGenericWindowId ()
@vcall 25 Ptr{None} GetGenericParentId ()
@vcall 26 Ptr{None} GetGenericContext ()
@vcall 27 Ptr{None} GetGenericDrawable ()
@vcall 20 None SetDisplayId (Ptr{None},)
@vcall 22 None SetParentId (Ptr{None},)
@vcall 21 None SetWindowId (Ptr{None},)
@vcall 174 None SetNextWindowId (Ptr{None},)
@vcall 50 None SetWindowName (Ptr{Uint8},)
@vcall 79 None HideCursor ()
@vcall 80 None ShowCursor ()
@vcall 82 None SetCurrentCursor (Int32,)
@vcall 164 Int32 GetEventPending ()
@vcall 28 None SetWindowInfo (Ptr{Uint8},)
@vcall 175 None SetNextWindowInfo (Ptr{Uint8},)
@vcall 29 None SetParentInfo (Ptr{Uint8},)
@vcall 58 None SetOffScreenRendering (Int32,)
@vcall 204 None CreateAWindow ()
@vcall 205 None DestroyWindow ()
@mcall None CreateOffScreenWindow (Int32, Int32) _ZN23vtkOSOpenGLRenderWindow21CreateOffScreenWindowEii "libvtkRendering"
@mcall None DestroyOffScreenWindow () _ZN23vtkOSOpenGLRenderWindow22DestroyOffScreenWindowEv "libvtkRendering"
@mcall None ResizeOffScreenWindow (Int32, Int32) _ZN23vtkOSOpenGLRenderWindow21ResizeOffScreenWindowEii "libvtkRendering"
@mcall None vtkOSOpenGLRenderWindow_eq (Void,) _ZN23vtkOSOpenGLRenderWindowaSERKS_ "libvtkRendering"
