cur_class = vtkProp
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN7vtkProp8IsTypeOfEPKc "libvtkCommon"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkProp} SafeDownCast (Ptr{vtkObjectBase},) _ZN7vtkProp12SafeDownCastEP13vtkObjectBase "libvtkCommon"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkProp} NewInstance () _ZNK7vtkProp11NewInstanceEv "libvtkCommon"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 20 None GetActors (Ptr{vtkPropCollection},)
@vcall 21 None GetActors2D (Ptr{vtkPropCollection},)
@vcall 22 None GetVolumes (Ptr{vtkPropCollection},)
@vcall 23 None SetVisibility (Int32,)
@vcall 24 Int32 GetVisibility ()
@vcall 25 None VisibilityOn ()
@vcall 26 None VisibilityOff ()
@vcall 27 None SetPickable (Int32,)
@vcall 28 Int32 GetPickable ()
@vcall 29 None PickableOn ()
@vcall 30 None PickableOff ()
@vcall 31 None Pick ()
@vcall 32 None SetDragable (Int32,)
@vcall 33 Int32 GetDragable ()
@vcall 34 None DragableOn ()
@vcall 35 None DragableOff ()
@vcall 36 Uint64 GetRedrawMTime ()
@vcall 37 None SetUseBounds (Bool,)
@vcall 38 Bool GetUseBounds ()
@vcall 39 None UseBoundsOn ()
@vcall 40 None UseBoundsOff ()
@vcall 41 Ptr{Float64} GetBounds ()
@vcall 42 None ShallowCopy (Ptr{vtkProp},)
@vcall 43 None InitPathTraversal ()
@vcall 44 Ptr{vtkAssemblyPath} GetNextPath ()
@vcall 45 Int32 GetNumberOfPaths ()
@vcall 46 None PokeMatrix (Ptr{vtkMatrix4x4},)
@vcall 47 Ptr{vtkMatrix4x4} GetMatrix ()
@vcall 48 Ptr{vtkInformation} GetPropertyKeys ()
@vcall 49 None SetPropertyKeys (Ptr{vtkInformation},)
@vcall 50 Bool HasKeys (Ptr{vtkInformation},)
@vcall 51 Int32 RenderOpaqueGeometry (Ptr{vtkViewport},)
@vcall 52 Int32 RenderTranslucentPolygonalGeometry (Ptr{vtkViewport},)
@vcall 53 Int32 RenderVolumetricGeometry (Ptr{vtkViewport},)
@vcall 54 Int32 RenderOverlay (Ptr{vtkViewport},)
@vcall 55 Bool RenderFilteredOpaqueGeometry (Ptr{vtkViewport}, Ptr{vtkInformation})
@vcall 56 Bool RenderFilteredTranslucentPolygonalGeometry (Ptr{vtkViewport}, Ptr{vtkInformation})
@vcall 57 Bool RenderFilteredVolumetricGeometry (Ptr{vtkViewport}, Ptr{vtkInformation})
@vcall 58 Bool RenderFilteredOverlay (Ptr{vtkViewport}, Ptr{vtkInformation})
@vcall 59 Int32 HasTranslucentPolygonalGeometry ()
@vcall 60 None ReleaseGraphicsResources (Ptr{vtkWindow},)
@vcall 61 Float64 GetEstimatedRenderTime (Ptr{vtkViewport},)
@vcall 62 Float64 GetEstimatedRenderTime ()
@vcall 63 None SetEstimatedRenderTime (Float64,)
@vcall 64 None RestoreEstimatedRenderTime ()
@vcall 65 None AddEstimatedRenderTime (Float64, Ptr{vtkViewport})
@vcall 66 None SetAllocatedRenderTime (Float64, Ptr{vtkViewport})
@vcall 67 Float64 GetAllocatedRenderTime ()
@mcall None SetRenderTimeMultiplier (Float64,) _ZN7vtkProp23SetRenderTimeMultiplierEd "libvtkCommon"
@vcall 68 Float64 GetRenderTimeMultiplier ()
@vcall 69 None BuildPaths (Ptr{vtkAssemblyPaths}, Ptr{vtkAssemblyPath})
@vcall 70 Bool GetSupportsSelection ()
@vcall 71 Int32 GetNumberOfConsumers ()
@mcall None AddConsumer (Ptr{vtkObject},) _ZN7vtkProp11AddConsumerEP9vtkObject "libvtkCommon"
@mcall None RemoveConsumer (Ptr{vtkObject},) _ZN7vtkProp14RemoveConsumerEP9vtkObject "libvtkCommon"
@mcall Ptr{vtkObject} GetConsumer (Int32,) _ZN7vtkProp11GetConsumerEi "libvtkCommon"
@mcall Int32 IsConsumer (Ptr{vtkObject},) _ZN7vtkProp10IsConsumerEP9vtkObject "libvtkCommon"
@mcall None vtkProp_eq (Void,) _ZN7vtkPropaSERKS_ "libvtkCommon"
