cur_class = vtkPolyDataNormals
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkPolyDataNormals} NewInstance () _ZNK18vtkPolyDataNormals11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetFeatureAngle (Float64,)
@vcall 66 Float64 GetFeatureAngleMinValue ()
@vcall 67 Float64 GetFeatureAngleMaxValue ()
@vcall 68 Float64 GetFeatureAngle ()
@vcall 69 None SetSplitting (Int32,)
@vcall 70 Int32 GetSplitting ()
@vcall 71 None SplittingOn ()
@vcall 72 None SplittingOff ()
@vcall 73 None SetConsistency (Int32,)
@vcall 74 Int32 GetConsistency ()
@vcall 75 None ConsistencyOn ()
@vcall 76 None ConsistencyOff ()
@vcall 77 None SetAutoOrientNormals (Int32,)
@vcall 78 Int32 GetAutoOrientNormals ()
@vcall 79 None AutoOrientNormalsOn ()
@vcall 80 None AutoOrientNormalsOff ()
@vcall 81 None SetComputePointNormals (Int32,)
@vcall 82 Int32 GetComputePointNormals ()
@vcall 83 None ComputePointNormalsOn ()
@vcall 84 None ComputePointNormalsOff ()
@vcall 85 None SetComputeCellNormals (Int32,)
@vcall 86 Int32 GetComputeCellNormals ()
@vcall 87 None ComputeCellNormalsOn ()
@vcall 88 None ComputeCellNormalsOff ()
@vcall 89 None SetFlipNormals (Int32,)
@vcall 90 Int32 GetFlipNormals ()
@vcall 91 None FlipNormalsOn ()
@vcall 92 None FlipNormalsOff ()
@vcall 93 None SetNonManifoldTraversal (Int32,)
@vcall 94 Int32 GetNonManifoldTraversal ()
@vcall 95 None NonManifoldTraversalOn ()
@vcall 96 None NonManifoldTraversalOff ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None TraverseAndOrder () _ZN18vtkPolyDataNormals16TraverseAndOrderEv "libvtkGraphics"
@mcall None MarkAndSplit (vtkIdType,) _ZN18vtkPolyDataNormals12MarkAndSplitEx "libvtkGraphics"
@mcall None vtkPolyDataNormals_eq (Void,) _ZN18vtkPolyDataNormalsaSERKS_ "libvtkGraphics"
