@scall Ptr{Void} New () _ZN17vtkPolyDataMapper3NewEv "libvtkRendering"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN17vtkPolyDataMapper8IsTypeOfEPKc "libvtkRendering"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{Void} SafeDownCast (Ptr{Void},) _ZN17vtkPolyDataMapper12SafeDownCastEP13vtkObjectBase "libvtkRendering"
@vcall 15 Ptr{Void} NewInstanceInternal ()
@vcall 4 None PrintSelf (Void, Void)
@vcall 101 None RenderPiece (Ptr{Void}, Ptr{Void})
@vcall 67 None Render (Ptr{Void}, Ptr{Void})
@vcall 45 None Update ()
@vcall 102 None SetPiece (Int32,)
@vcall 103 Int32 GetPiece ()
@vcall 104 None SetNumberOfPieces (Int32,)
@vcall 105 Int32 GetNumberOfPieces ()
@vcall 106 None SetNumberOfSubPieces (Int32,)
@vcall 107 Int32 GetNumberOfSubPieces ()
@vcall 108 None SetGhostLevel (Int32,)
@vcall 109 Int32 GetGhostLevel ()
@vcall 63 Ptr{Float64} GetBounds ()
@vcall 64 None GetBounds (Ptr{Float64},)
@vcall 110 None MapDataArrayToVertexAttribute (Ptr{Uint8}, Ptr{Uint8}, Int32, Int32)
@vcall 111 None MapDataArrayToMultiTextureAttribute (Int32, Ptr{Uint8}, Int32, Int32)
@vcall 112 None RemoveVertexAttributeMapping (Ptr{Uint8},)
@vcall 113 None RemoveAllVertexAttributeMappings ()
@vcall 114 None ComputeBounds ()
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{Void})
