cur_class = vtkParametricFunction
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkParametricFunction} NewInstance () _ZNK21vtkParametricFunction11NewInstanceEv "libvtkCommon"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 20 Int32 GetDimension ()
@vcall 21 None Evaluate (Ptr{Float64}, Ptr{Float64}, Ptr{Float64})
@vcall 22 Float64 EvaluateScalar (Ptr{Float64}, Ptr{Float64}, Ptr{Float64})
@vcall 23 None SetMinimumU (Float64,)
@vcall 24 Float64 GetMinimumU ()
@vcall 25 None SetMaximumU (Float64,)
@vcall 26 Float64 GetMaximumU ()
@vcall 27 None SetMinimumV (Float64,)
@vcall 28 Float64 GetMinimumV ()
@vcall 29 None SetMaximumV (Float64,)
@vcall 30 Float64 GetMaximumV ()
@vcall 31 None SetMinimumW (Float64,)
@vcall 32 Float64 GetMinimumW ()
@vcall 33 None SetMaximumW (Float64,)
@vcall 34 Float64 GetMaximumW ()
@vcall 35 None SetJoinU (Int32,)
@vcall 36 Int32 GetJoinU ()
@vcall 37 None JoinUOn ()
@vcall 38 None JoinUOff ()
@vcall 39 None SetJoinV (Int32,)
@vcall 40 Int32 GetJoinV ()
@vcall 41 None JoinVOn ()
@vcall 42 None JoinVOff ()
@vcall 43 None SetTwistU (Int32,)
@vcall 44 Int32 GetTwistU ()
@vcall 45 None TwistUOn ()
@vcall 46 None TwistUOff ()
@vcall 47 None SetTwistV (Int32,)
@vcall 48 Int32 GetTwistV ()
@vcall 49 None TwistVOn ()
@vcall 50 None TwistVOff ()
@vcall 51 None SetClockwiseOrdering (Int32,)
@vcall 52 Int32 GetClockwiseOrdering ()
@vcall 53 None ClockwiseOrderingOn ()
@vcall 54 None ClockwiseOrderingOff ()
@vcall 55 None SetDerivativesAvailable (Int32,)
@vcall 56 Int32 GetDerivativesAvailable ()
@vcall 57 None DerivativesAvailableOn ()
@vcall 58 None DerivativesAvailableOff ()
@mcall None vtkParametricFunction_eq (Void,) _ZN21vtkParametricFunctionaSERKS_ "libvtkCommon"
