cur_class = vtkRenderedTreeAreaRepresentation
@scall Ptr{vtkRenderedTreeAreaRepresentation} vtkRenderedTreeAreaRepresentationNew () _ZN33vtkRenderedTreeAreaRepresentation3NewEv "libvtkViews"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN33vtkRenderedTreeAreaRepresentation8IsTypeOfEPKc "libvtkViews"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkRenderedTreeAreaRepresentation} SafeDownCast (Ptr{vtkObjectBase},) _ZN33vtkRenderedTreeAreaRepresentation12SafeDownCastEP13vtkObjectBase "libvtkViews"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkRenderedTreeAreaRepresentation} NewInstance () _ZNK33vtkRenderedTreeAreaRepresentation11NewInstanceEv "libvtkViews"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 89 None SetLabelRenderMode (Int32,)
@vcall 93 None SetAreaLabelArrayName (Ptr{Uint8},)
@vcall 94 Ptr{Uint8} GetAreaLabelArrayName ()
@vcall 95 None SetAreaSizeArrayName (Ptr{Uint8},)
@vcall 96 Ptr{Uint8} GetAreaSizeArrayName ()
@vcall 97 None SetAreaLabelPriorityArrayName (Ptr{Uint8},)
@vcall 98 Ptr{Uint8} GetAreaLabelPriorityArrayName ()
@vcall 99 None SetGraphEdgeLabelArrayName (Ptr{Uint8},)
@vcall 100 None SetGraphEdgeLabelArrayName (Ptr{Uint8}, Int32)
@vcall 101 Ptr{Uint8} GetGraphEdgeLabelArrayName ()
@vcall 102 Ptr{Uint8} GetGraphEdgeLabelArrayName (Int32,)
@vcall 103 None SetGraphEdgeLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 104 None SetGraphEdgeLabelTextProperty (Ptr{vtkTextProperty}, Int32)
@vcall 105 Ptr{vtkTextProperty} GetGraphEdgeLabelTextProperty ()
@vcall 106 Ptr{vtkTextProperty} GetGraphEdgeLabelTextProperty (Int32,)
@vcall 107 None SetAreaHoverArrayName (Ptr{Uint8},)
@vcall 108 Ptr{Uint8} GetAreaHoverArrayName ()
@vcall 109 None SetAreaLabelVisibility (Bool,)
@vcall 110 Bool GetAreaLabelVisibility ()
@vcall 111 None AreaLabelVisibilityOn ()
@vcall 112 None AreaLabelVisibilityOff ()
@vcall 113 None SetAreaLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 114 Ptr{vtkTextProperty} GetAreaLabelTextProperty ()
@vcall 115 None SetGraphEdgeLabelVisibility (Bool,)
@vcall 116 None SetGraphEdgeLabelVisibility (Bool, Int32)
@vcall 117 Bool GetGraphEdgeLabelVisibility ()
@vcall 118 Bool GetGraphEdgeLabelVisibility (Int32,)
@vcall 119 None GraphEdgeLabelVisibilityOn ()
@vcall 120 None GraphEdgeLabelVisibilityOff ()
@mcall None SetAreaColorArrayName (Ptr{Uint8},) _ZN33vtkRenderedTreeAreaRepresentation21SetAreaColorArrayNameEPKc "libvtkViews"
@mcall Ptr{Uint8} GetAreaColorArrayName () _ZN33vtkRenderedTreeAreaRepresentation21GetAreaColorArrayNameEv "libvtkViews"
@vcall 121 None SetColorAreasByArray (Bool,)
@vcall 122 Bool GetColorAreasByArray ()
@vcall 123 None ColorAreasByArrayOn ()
@vcall 124 None ColorAreasByArrayOff ()
@vcall 125 None SetGraphEdgeColorArrayName (Ptr{Uint8},)
@vcall 126 None SetGraphEdgeColorArrayName (Ptr{Uint8}, Int32)
@vcall 127 Ptr{Uint8} GetGraphEdgeColorArrayName ()
@vcall 128 Ptr{Uint8} GetGraphEdgeColorArrayName (Int32,)
@vcall 129 None SetGraphEdgeColorToSplineFraction ()
@vcall 130 None SetGraphEdgeColorToSplineFraction (Int32,)
@vcall 131 None SetColorGraphEdgesByArray (Bool,)
@vcall 132 None SetColorGraphEdgesByArray (Bool, Int32)
@vcall 133 Bool GetColorGraphEdgesByArray ()
@vcall 134 Bool GetColorGraphEdgesByArray (Int32,)
@vcall 135 None ColorGraphEdgesByArrayOn ()
@vcall 136 None ColorGraphEdgesByArrayOff ()
@vcall 137 None SetGraphHoverArrayName (Ptr{Uint8},)
@vcall 138 None SetGraphHoverArrayName (Ptr{Uint8}, Int32)
@vcall 139 Ptr{Uint8} GetGraphHoverArrayName ()
@vcall 140 Ptr{Uint8} GetGraphHoverArrayName (Int32,)
@vcall 141 None SetShrinkPercentage (Float64,)
@vcall 142 Float64 GetShrinkPercentage ()
@vcall 143 None SetGraphBundlingStrength (Float64,)
@vcall 144 None SetGraphBundlingStrength (Float64, Int32)
@vcall 145 Float64 GetGraphBundlingStrength ()
@vcall 146 Float64 GetGraphBundlingStrength (Int32,)
@vcall 147 None SetGraphSplineType (Int32, Int32)
@vcall 148 Int32 GetGraphSplineType (Int32,)
@vcall 149 None SetAreaLayoutStrategy (Ptr{vtkAreaLayoutStrategy},)
@vcall 150 Ptr{vtkAreaLayoutStrategy} GetAreaLayoutStrategy ()
@vcall 151 None SetAreaToPolyData (Ptr{vtkPolyDataAlgorithm},)
@vcall 152 Ptr{vtkPolyDataAlgorithm} GetAreaToPolyData ()
@vcall 153 None SetUseRectangularCoordinates (Bool,)
@vcall 154 Bool GetUseRectangularCoordinates ()
@vcall 155 None UseRectangularCoordinatesOn ()
@vcall 156 None UseRectangularCoordinatesOff ()
@vcall 157 None SetAreaLabelMapper (Ptr{vtkLabeledDataMapper},)
@vcall 158 Ptr{vtkLabeledDataMapper} GetAreaLabelMapper ()
@vcall 63 None ApplyViewTheme (Ptr{vtkViewTheme},)
@vcall 159 None SetEdgeScalarBarVisibility (Bool,)
@vcall 160 Bool GetEdgeScalarBarVisibility ()
@vcall 86 Bool AddToView (Ptr{vtkView},)
@vcall 87 Bool RemoveFromView (Ptr{vtkView},)
@vcall 83 Ptr{vtkSelection} ConvertSelection (Ptr{vtkView}, Ptr{vtkSelection})
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@vcall 62 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 92 None PrepareForRendering (Ptr{vtkRenderView},)
@mcall Bool ValidIndex (Int32,) _ZN33vtkRenderedTreeAreaRepresentation10ValidIndexEi "libvtkViews"
@mcall None UpdateHoverHighlight (Ptr{vtkView}, Int32, Int32) _ZN33vtkRenderedTreeAreaRepresentation20UpdateHoverHighlightEP7vtkViewii "libvtkViews"
@vcall 91 vtkUnicodeString GetHoverTextInternal (Ptr{vtkSelection},)
@vcall 161 None SetAreaSizeArrayNameInternal (Ptr{Uint8},)
@vcall 162 Ptr{Uint8} GetAreaSizeArrayNameInternal ()
@vcall 163 None SetAreaColorArrayNameInternal (Ptr{Uint8},)
@vcall 164 Ptr{Uint8} GetAreaColorArrayNameInternal ()
@vcall 165 None SetAreaLabelArrayNameInternal (Ptr{Uint8},)
@vcall 166 Ptr{Uint8} GetAreaLabelArrayNameInternal ()
@vcall 167 None SetAreaLabelPriorityArrayNameInternal (Ptr{Uint8},)
@vcall 168 Ptr{Uint8} GetAreaLabelPriorityArrayNameInternal ()
@vcall 169 None SetGraphEdgeColorArrayNameInternal (Ptr{Uint8},)
@vcall 170 Ptr{Uint8} GetGraphEdgeColorArrayNameInternal ()
@vcall 171 Ptr{Uint8} GetAreaHoverTextInternal ()
@vcall 172 None SetAreaHoverTextInternal (Ptr{Uint8},)
@mcall None vtkRenderedTreeAreaRepresentation_eq (Void,) _ZN33vtkRenderedTreeAreaRepresentationaSERKS_ "libvtkViews"
