cur_class = vtkRenderedGraphRepresentation
@scall Ptr{vtkRenderedGraphRepresentation} vtkRenderedGraphRepresentationNew () _ZN30vtkRenderedGraphRepresentation3NewEv "libvtkViews"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN30vtkRenderedGraphRepresentation8IsTypeOfEPKc "libvtkViews"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkRenderedGraphRepresentation} SafeDownCast (Ptr{vtkObjectBase},) _ZN30vtkRenderedGraphRepresentation12SafeDownCastEP13vtkObjectBase "libvtkViews"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkRenderedGraphRepresentation} NewInstance () _ZNK30vtkRenderedGraphRepresentation11NewInstanceEv "libvtkViews"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 93 None SetVertexLabelArrayName (Ptr{Uint8},)
@vcall 94 Ptr{Uint8} GetVertexLabelArrayName ()
@vcall 95 None SetVertexLabelPriorityArrayName (Ptr{Uint8},)
@vcall 96 Ptr{Uint8} GetVertexLabelPriorityArrayName ()
@vcall 97 None SetVertexLabelVisibility (Bool,)
@vcall 98 Bool GetVertexLabelVisibility ()
@vcall 99 None VertexLabelVisibilityOn ()
@vcall 100 None VertexLabelVisibilityOff ()
@vcall 101 None SetVertexLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 102 Ptr{vtkTextProperty} GetVertexLabelTextProperty ()
@vcall 103 None SetVertexHoverArrayName (Ptr{Uint8},)
@vcall 104 Ptr{Uint8} GetVertexHoverArrayName ()
@vcall 105 None SetHideVertexLabelsOnInteraction (Bool,)
@vcall 106 Bool GetHideVertexLabelsOnInteraction ()
@vcall 107 None HideVertexLabelsOnInteractionOn ()
@vcall 108 None HideVertexLabelsOnInteractionOff ()
@vcall 109 None SetEdgeLabelArrayName (Ptr{Uint8},)
@vcall 110 Ptr{Uint8} GetEdgeLabelArrayName ()
@vcall 111 None SetEdgeLabelPriorityArrayName (Ptr{Uint8},)
@vcall 112 Ptr{Uint8} GetEdgeLabelPriorityArrayName ()
@vcall 113 None SetEdgeLabelVisibility (Bool,)
@vcall 114 Bool GetEdgeLabelVisibility ()
@vcall 115 None EdgeLabelVisibilityOn ()
@vcall 116 None EdgeLabelVisibilityOff ()
@vcall 117 None SetEdgeLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 118 Ptr{vtkTextProperty} GetEdgeLabelTextProperty ()
@vcall 119 None SetEdgeHoverArrayName (Ptr{Uint8},)
@vcall 120 Ptr{Uint8} GetEdgeHoverArrayName ()
@vcall 121 None SetHideEdgeLabelsOnInteraction (Bool,)
@vcall 122 Bool GetHideEdgeLabelsOnInteraction ()
@vcall 123 None HideEdgeLabelsOnInteractionOn ()
@vcall 124 None HideEdgeLabelsOnInteractionOff ()
@vcall 125 None SetVertexIconArrayName (Ptr{Uint8},)
@vcall 126 Ptr{Uint8} GetVertexIconArrayName ()
@vcall 127 None SetVertexIconPriorityArrayName (Ptr{Uint8},)
@vcall 128 Ptr{Uint8} GetVertexIconPriorityArrayName ()
@vcall 129 None SetVertexIconVisibility (Bool,)
@vcall 130 Bool GetVertexIconVisibility ()
@vcall 131 None VertexIconVisibilityOn ()
@vcall 132 None VertexIconVisibilityOff ()
@vcall 133 None AddVertexIconType (Ptr{Uint8}, Int32)
@vcall 134 None ClearVertexIconTypes ()
@vcall 135 None SetUseVertexIconTypeMap (Bool,)
@vcall 136 Bool GetUseVertexIconTypeMap ()
@vcall 137 None UseVertexIconTypeMapOn ()
@vcall 138 None UseVertexIconTypeMapOff ()
@vcall 139 None SetVertexIconAlignment (Int32,)
@vcall 140 Int32 GetVertexIconAlignment ()
@vcall 141 None SetVertexSelectedIcon (Int32,)
@vcall 142 Int32 GetVertexSelectedIcon ()
@vcall 143 None SetVertexDefaultIcon (Int32,)
@vcall 144 Int32 GetVertexDefaultIcon ()
@vcall 145 None SetVertexIconSelectionMode (Int32,)
@vcall 146 Int32 GetVertexIconSelectionMode ()
@vcall 147 None SetVertexIconSelectionModeToSelectedIcon ()
@vcall 148 None SetVertexIconSelectionModeToSelectedOffset ()
@vcall 149 None SetVertexIconSelectionModeToAnnotationIcon ()
@vcall 150 None SetVertexIconSelectionModeToIgnoreSelection ()
@vcall 151 None SetEdgeIconArrayName (Ptr{Uint8},)
@vcall 152 Ptr{Uint8} GetEdgeIconArrayName ()
@vcall 153 None SetEdgeIconPriorityArrayName (Ptr{Uint8},)
@vcall 154 Ptr{Uint8} GetEdgeIconPriorityArrayName ()
@vcall 155 None SetEdgeIconVisibility (Bool,)
@vcall 156 Bool GetEdgeIconVisibility ()
@vcall 157 None EdgeIconVisibilityOn ()
@vcall 158 None EdgeIconVisibilityOff ()
@vcall 159 None AddEdgeIconType (Ptr{Uint8}, Int32)
@vcall 160 None ClearEdgeIconTypes ()
@vcall 161 None SetUseEdgeIconTypeMap (Bool,)
@vcall 162 Bool GetUseEdgeIconTypeMap ()
@vcall 163 None UseEdgeIconTypeMapOn ()
@vcall 164 None UseEdgeIconTypeMapOff ()
@vcall 165 None SetEdgeIconAlignment (Int32,)
@vcall 166 Int32 GetEdgeIconAlignment ()
@vcall 167 None SetColorVerticesByArray (Bool,)
@vcall 168 Bool GetColorVerticesByArray ()
@vcall 169 None ColorVerticesByArrayOn ()
@vcall 170 None ColorVerticesByArrayOff ()
@vcall 171 None SetVertexColorArrayName (Ptr{Uint8},)
@vcall 172 Ptr{Uint8} GetVertexColorArrayName ()
@vcall 173 None SetColorEdgesByArray (Bool,)
@vcall 174 Bool GetColorEdgesByArray ()
@vcall 175 None ColorEdgesByArrayOn ()
@vcall 176 None ColorEdgesByArrayOff ()
@vcall 177 None SetEdgeColorArrayName (Ptr{Uint8},)
@vcall 178 Ptr{Uint8} GetEdgeColorArrayName ()
@vcall 179 None SetEnableVerticesByArray (Bool,)
@vcall 180 Bool GetEnableVerticesByArray ()
@vcall 181 None EnableVerticesByArrayOn ()
@vcall 182 None EnableVerticesByArrayOff ()
@vcall 183 None SetEnabledVerticesArrayName (Ptr{Uint8},)
@vcall 184 Ptr{Uint8} GetEnabledVerticesArrayName ()
@vcall 185 None SetEnableEdgesByArray (Bool,)
@vcall 186 Bool GetEnableEdgesByArray ()
@vcall 187 None EnableEdgesByArrayOn ()
@vcall 188 None EnableEdgesByArrayOff ()
@vcall 189 None SetEnabledEdgesArrayName (Ptr{Uint8},)
@vcall 190 Ptr{Uint8} GetEnabledEdgesArrayName ()
@vcall 191 None SetEdgeVisibility (Bool,)
@vcall 192 Bool GetEdgeVisibility ()
@vcall 193 None EdgeVisibilityOn ()
@vcall 194 None EdgeVisibilityOff ()
@mcall None SetEdgeSelection (Bool,) _ZN30vtkRenderedGraphRepresentation16SetEdgeSelectionEb "libvtkViews"
@mcall Bool GetEdgeSelection () _ZN30vtkRenderedGraphRepresentation16GetEdgeSelectionEv "libvtkViews"
@vcall 195 None SetLayoutStrategy (Ptr{vtkGraphLayoutStrategy},)
@vcall 196 Ptr{vtkGraphLayoutStrategy} GetLayoutStrategy ()
@vcall 197 None SetLayoutStrategy (Ptr{Uint8},)
@vcall 198 Ptr{Uint8} GetLayoutStrategyName ()
@mcall None SetLayoutStrategyToRandom () _ZN30vtkRenderedGraphRepresentation25SetLayoutStrategyToRandomEv "libvtkViews"
@mcall None SetLayoutStrategyToForceDirected () _ZN30vtkRenderedGraphRepresentation32SetLayoutStrategyToForceDirectedEv "libvtkViews"
@mcall None SetLayoutStrategyToSimple2D () _ZN30vtkRenderedGraphRepresentation27SetLayoutStrategyToSimple2DEv "libvtkViews"
@mcall None SetLayoutStrategyToClustering2D () _ZN30vtkRenderedGraphRepresentation31SetLayoutStrategyToClustering2DEv "libvtkViews"
@mcall None SetLayoutStrategyToCommunity2D () _ZN30vtkRenderedGraphRepresentation30SetLayoutStrategyToCommunity2DEv "libvtkViews"
@mcall None SetLayoutStrategyToFast2D () _ZN30vtkRenderedGraphRepresentation25SetLayoutStrategyToFast2DEv "libvtkViews"
@mcall None SetLayoutStrategyToPassThrough () _ZN30vtkRenderedGraphRepresentation30SetLayoutStrategyToPassThroughEv "libvtkViews"
@mcall None SetLayoutStrategyToCircular () _ZN30vtkRenderedGraphRepresentation27SetLayoutStrategyToCircularEv "libvtkViews"
@mcall None SetLayoutStrategyToTree () _ZN30vtkRenderedGraphRepresentation23SetLayoutStrategyToTreeEv "libvtkViews"
@mcall None SetLayoutStrategyToCosmicTree () _ZN30vtkRenderedGraphRepresentation29SetLayoutStrategyToCosmicTreeEv "libvtkViews"
@mcall None SetLayoutStrategyToCone () _ZN30vtkRenderedGraphRepresentation23SetLayoutStrategyToConeEv "libvtkViews"
@mcall None SetLayoutStrategyToSpanTree () _ZN30vtkRenderedGraphRepresentation27SetLayoutStrategyToSpanTreeEv "libvtkViews"
@vcall 199 None SetLayoutStrategyToAssignCoordinates (Ptr{Uint8}, Ptr{Uint8}, Ptr{Uint8})
@vcall 200 None SetLayoutStrategyToTree (Bool, Float64, Float64, Float64)
@vcall 201 None SetLayoutStrategyToCosmicTree (Ptr{Uint8}, Bool, Int32, vtkIdType)
@vcall 202 None SetEdgeLayoutStrategy (Ptr{vtkEdgeLayoutStrategy},)
@vcall 203 Ptr{vtkEdgeLayoutStrategy} GetEdgeLayoutStrategy ()
@mcall None SetEdgeLayoutStrategyToArcParallel () _ZN30vtkRenderedGraphRepresentation34SetEdgeLayoutStrategyToArcParallelEv "libvtkViews"
@mcall None SetEdgeLayoutStrategyToPassThrough () _ZN30vtkRenderedGraphRepresentation34SetEdgeLayoutStrategyToPassThroughEv "libvtkViews"
@vcall 204 None SetEdgeLayoutStrategyToGeo (Float64,)
@vcall 205 None SetEdgeLayoutStrategy (Ptr{Uint8},)
@vcall 206 Ptr{Uint8} GetEdgeLayoutStrategyName ()
@vcall 63 None ApplyViewTheme (Ptr{vtkViewTheme},)
@vcall 207 None SetGlyphType (Int32,)
@vcall 208 Int32 GetGlyphType ()
@vcall 209 None SetScaling (Bool,)
@vcall 210 Bool GetScaling ()
@vcall 211 None ScalingOn ()
@vcall 212 None ScalingOff ()
@vcall 213 None SetScalingArrayName (Ptr{Uint8},)
@vcall 214 Ptr{Uint8} GetScalingArrayName ()
@vcall 215 None SetVertexScalarBarVisibility (Bool,)
@vcall 216 Bool GetVertexScalarBarVisibility ()
@vcall 217 None SetEdgeScalarBarVisibility (Bool,)
@vcall 218 Bool GetEdgeScalarBarVisibility ()
@vcall 219 Bool IsLayoutComplete ()
@vcall 220 None UpdateLayout ()
@mcall None ComputeSelectedGraphBounds (Ptr{Float64},) _ZN30vtkRenderedGraphRepresentation26ComputeSelectedGraphBoundsEPd "libvtkViews"
@vcall 86 Bool AddToView (Ptr{vtkView},)
@vcall 87 Bool RemoveFromView (Ptr{vtkView},)
@vcall 92 None PrepareForRendering (Ptr{vtkRenderView},)
@vcall 83 Ptr{vtkSelection} ConvertSelection (Ptr{vtkView}, Ptr{vtkSelection})
@vcall 91 vtkUnicodeString GetHoverTextInternal (Ptr{vtkSelection},)
@vcall 62 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 221 None SetVertexColorArrayNameInternal (Ptr{Uint8},)
@vcall 222 Ptr{Uint8} GetVertexColorArrayNameInternal ()
@vcall 223 None SetEdgeColorArrayNameInternal (Ptr{Uint8},)
@vcall 224 Ptr{Uint8} GetEdgeColorArrayNameInternal ()
@vcall 225 None SetScalingArrayNameInternal (Ptr{Uint8},)
@vcall 226 Ptr{Uint8} GetScalingArrayNameInternal ()
@vcall 227 None SetLayoutStrategyName (Ptr{Uint8},)
@vcall 228 None SetEdgeLayoutStrategyName (Ptr{Uint8},)
@mcall None vtkRenderedGraphRepresentation_eq (Void,) _ZN30vtkRenderedGraphRepresentationaSERKS_ "libvtkViews"
