cur_class = vtkRenderedHierarchyRepresentation
@scall Ptr{vtkRenderedHierarchyRepresentation} vtkRenderedHierarchyRepresentationNew () _ZN34vtkRenderedHierarchyRepresentation3NewEv "libvtkViews"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN34vtkRenderedHierarchyRepresentation8IsTypeOfEPKc "libvtkViews"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkRenderedHierarchyRepresentation} SafeDownCast (Ptr{vtkObjectBase},) _ZN34vtkRenderedHierarchyRepresentation12SafeDownCastEP13vtkObjectBase "libvtkViews"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkRenderedHierarchyRepresentation} NewInstance () _ZNK34vtkRenderedHierarchyRepresentation11NewInstanceEv "libvtkViews"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 229 None SetGraphEdgeLabelArrayName (Ptr{Uint8},)
@vcall 230 None SetGraphEdgeLabelArrayName (Ptr{Uint8}, Int32)
@vcall 231 Ptr{Uint8} GetGraphEdgeLabelArrayName ()
@vcall 232 Ptr{Uint8} GetGraphEdgeLabelArrayName (Int32,)
@vcall 233 None SetGraphEdgeLabelVisibility (Bool,)
@vcall 234 None SetGraphEdgeLabelVisibility (Bool, Int32)
@vcall 235 Bool GetGraphEdgeLabelVisibility ()
@vcall 236 Bool GetGraphEdgeLabelVisibility (Int32,)
@vcall 237 None GraphEdgeLabelVisibilityOn ()
@vcall 238 None GraphEdgeLabelVisibilityOff ()
@vcall 239 None SetGraphEdgeColorArrayName (Ptr{Uint8},)
@vcall 240 None SetGraphEdgeColorArrayName (Ptr{Uint8}, Int32)
@vcall 241 Ptr{Uint8} GetGraphEdgeColorArrayName ()
@vcall 242 Ptr{Uint8} GetGraphEdgeColorArrayName (Int32,)
@vcall 243 None SetColorGraphEdgesByArray (Bool,)
@vcall 244 None SetColorGraphEdgesByArray (Bool, Int32)
@vcall 245 Bool GetColorGraphEdgesByArray ()
@vcall 246 Bool GetColorGraphEdgesByArray (Int32,)
@vcall 247 None ColorGraphEdgesByArrayOn ()
@vcall 248 None ColorGraphEdgesByArrayOff ()
@vcall 249 None SetGraphEdgeColorToSplineFraction ()
@vcall 250 None SetGraphEdgeColorToSplineFraction (Int32,)
@vcall 251 None SetGraphVisibility (Bool,)
@vcall 252 None SetGraphVisibility (Bool, Int32)
@vcall 253 Bool GetGraphVisibility ()
@vcall 254 Bool GetGraphVisibility (Int32,)
@vcall 255 None GraphVisibilityOn ()
@vcall 256 None GraphVisibilityOff ()
@vcall 257 None SetBundlingStrength (Float64,)
@vcall 258 None SetBundlingStrength (Float64, Int32)
@vcall 259 Float64 GetBundlingStrength ()
@vcall 260 Float64 GetBundlingStrength (Int32,)
@vcall 261 None SetGraphSplineType (Int32, Int32)
@vcall 262 Int32 GetGraphSplineType (Int32,)
@vcall 263 None SetGraphEdgeLabelFontSize (Int32,)
@vcall 264 None SetGraphEdgeLabelFontSize (Int32, Int32)
@vcall 265 Int32 GetGraphEdgeLabelFontSize ()
@vcall 266 Int32 GetGraphEdgeLabelFontSize (Int32,)
@vcall 86 Bool AddToView (Ptr{vtkView},)
@vcall 87 Bool RemoveFromView (Ptr{vtkView},)
@mcall Bool ValidIndex (Int32,) _ZN34vtkRenderedHierarchyRepresentation10ValidIndexEi "libvtkViews"
@vcall 83 Ptr{vtkSelection} ConvertSelection (Ptr{vtkView}, Ptr{vtkSelection})
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@vcall 62 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 63 None ApplyViewTheme (Ptr{vtkViewTheme},)
@mcall None vtkRenderedHierarchyRepresentation_eq (Void,) _ZN34vtkRenderedHierarchyRepresentationaSERKS_ "libvtkViews"
