cur_class = vtkResliceCursor
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN16vtkResliceCursor8IsTypeOfEPKc "libvtkGraphics"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkResliceCursor} SafeDownCast (Ptr{vtkObjectBase},) _ZN16vtkResliceCursor12SafeDownCastEP13vtkObjectBase "libvtkGraphics"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkResliceCursor} NewInstance () _ZNK16vtkResliceCursor11NewInstanceEv "libvtkGraphics"
@scall Ptr{vtkResliceCursor} vtkResliceCursorNew () _ZN16vtkResliceCursor3NewEv "libvtkGraphics"
@vcall 20 None SetImage (Ptr{vtkImageData},)
@vcall 21 Ptr{vtkImageData} GetImage ()
@vcall 22 None SetCenter (Float64, Float64, Float64)
@vcall 23 None SetCenter (Ptr{Float64},)
@vcall 24 Ptr{Float64} GetCenter ()
@vcall 25 None GetCenter (Void, Void, Void)
@vcall 26 None GetCenter (Ptr{Float64},)
@vcall 27 None SetThickness (Float64, Float64, Float64)
@vcall 28 None SetThickness (Ptr{Float64},)
@vcall 29 Ptr{Float64} GetThickness ()
@vcall 30 None GetThickness (Void, Void, Void)
@vcall 31 None GetThickness (Ptr{Float64},)
@vcall 32 None SetThickMode (Int32,)
@vcall 33 Int32 GetThickMode ()
@vcall 34 None ThickModeOn ()
@vcall 35 None ThickModeOff ()
@vcall 36 Ptr{vtkPolyData} GetPolyData ()
@vcall 37 Ptr{vtkPolyData} GetCenterlineAxisPolyData (Int32,)
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 38 Ptr{vtkPlane} GetPlane (Int32,)
@vcall 39 None Update ()
@vcall 40 Ptr{Float64} GetXAxis ()
@vcall 41 None GetXAxis (Void, Void, Void)
@vcall 42 None GetXAxis (Ptr{Float64},)
@vcall 43 Ptr{Float64} GetYAxis ()
@vcall 44 None GetYAxis (Void, Void, Void)
@vcall 45 None GetYAxis (Ptr{Float64},)
@vcall 46 Ptr{Float64} GetZAxis ()
@vcall 47 None GetZAxis (Void, Void, Void)
@vcall 48 None GetZAxis (Ptr{Float64},)
@vcall 49 None SetXAxis (Float64, Float64, Float64)
@vcall 50 None SetXAxis (Ptr{Float64},)
@vcall 51 None SetYAxis (Float64, Float64, Float64)
@vcall 52 None SetYAxis (Ptr{Float64},)
@vcall 53 None SetZAxis (Float64, Float64, Float64)
@vcall 54 None SetZAxis (Ptr{Float64},)
@vcall 55 Ptr{Float64} GetAxis (Int32,)
@vcall 56 None SetHole (Int32,)
@vcall 57 Int32 GetHole ()
@vcall 58 None SetHoleWidth (Float64,)
@vcall 59 Float64 GetHoleWidth ()
@vcall 60 None SetHoleWidthInPixels (Float64,)
@vcall 61 Float64 GetHoleWidthInPixels ()
@vcall 19 Uint64 GetMTime ()
@vcall 62 None Reset ()
@vcall 63 None BuildCursorGeometry ()
@vcall 64 None BuildPolyData ()
@vcall 65 None BuildCursorTopology ()
@vcall 66 None BuildCursorTopologyWithHole ()
@vcall 67 None BuildCursorTopologyWithoutHole ()
@vcall 68 None BuildCursorGeometryWithoutHole ()
@vcall 69 None BuildCursorGeometryWithHole ()
@vcall 70 None ComputeAxes ()
@mcall None vtkResliceCursor_eq (Void,) _ZN16vtkResliceCursoraSERKS_ "libvtkGraphics"
