cur_class = vtkRectangularButtonSource
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN26vtkRectangularButtonSource8IsTypeOfEPKc "libvtkGraphics"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkRectangularButtonSource} SafeDownCast (Ptr{vtkObjectBase},) _ZN26vtkRectangularButtonSource12SafeDownCastEP13vtkObjectBase "libvtkGraphics"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkRectangularButtonSource} NewInstance () _ZNK26vtkRectangularButtonSource11NewInstanceEv "libvtkGraphics"
@scall Ptr{vtkRectangularButtonSource} vtkRectangularButtonSourceNew () _ZN26vtkRectangularButtonSource3NewEv "libvtkGraphics"
@vcall 85 None SetWidth (Float64,)
@vcall 86 Float64 GetWidthMinValue ()
@vcall 87 Float64 GetWidthMaxValue ()
@vcall 88 Float64 GetWidth ()
@vcall 89 None SetHeight (Float64,)
@vcall 90 Float64 GetHeightMinValue ()
@vcall 91 Float64 GetHeightMaxValue ()
@vcall 92 Float64 GetHeight ()
@vcall 93 None SetDepth (Float64,)
@vcall 94 Float64 GetDepthMinValue ()
@vcall 95 Float64 GetDepthMaxValue ()
@vcall 96 Float64 GetDepth ()
@vcall 97 None SetBoxRatio (Float64,)
@vcall 98 Float64 GetBoxRatioMinValue ()
@vcall 99 Float64 GetBoxRatioMaxValue ()
@vcall 100 Float64 GetBoxRatio ()
@vcall 101 None SetTextureRatio (Float64,)
@vcall 102 Float64 GetTextureRatioMinValue ()
@vcall 103 Float64 GetTextureRatioMaxValue ()
@vcall 104 Float64 GetTextureRatio ()
@vcall 105 None SetTextureHeightRatio (Float64,)
@vcall 106 Float64 GetTextureHeightRatioMinValue ()
@vcall 107 Float64 GetTextureHeightRatioMaxValue ()
@vcall 108 Float64 GetTextureHeightRatio ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkRectangularButtonSource_eq (Void,) _ZN26vtkRectangularButtonSourceaSERKS_ "libvtkGraphics"
