@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN15vtkSphereSource8IsTypeOfEPKc "libvtkGraphics"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{Void} SafeDownCast (Ptr{Void},) _ZN15vtkSphereSource12SafeDownCastEP13vtkObjectBase "libvtkGraphics"
@vcall 15 Ptr{Void} NewInstanceInternal ()
@mcall Ptr{Void} NewInstance () _ZNK15vtkSphereSource11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, Void)
@scall Ptr{Void} New () _ZN15vtkSphereSource3NewEv "libvtkGraphics"
@vcall 65 None SetRadius (Float64,)
@vcall 66 Float64 GetRadiusMinValue ()
@vcall 67 Float64 GetRadiusMaxValue ()
@vcall 68 Float64 GetRadius ()
@vcall 69 None SetCenter (Float64, Float64, Float64)
@vcall 70 None SetCenter (Ptr{Float64},)
@vcall 71 Ptr{Float64} GetCenter ()
@vcall 72 None GetCenter (Ptr{Float64},)
@vcall 73 None SetThetaResolution (Int32,)
@vcall 74 Int32 GetThetaResolutionMinValue ()
@vcall 75 Int32 GetThetaResolutionMaxValue ()
@vcall 76 Int32 GetThetaResolution ()
@vcall 77 None SetPhiResolution (Int32,)
@vcall 78 Int32 GetPhiResolutionMinValue ()
@vcall 79 Int32 GetPhiResolutionMaxValue ()
@vcall 80 Int32 GetPhiResolution ()
@vcall 81 None SetStartTheta (Float64,)
@vcall 82 Float64 GetStartThetaMinValue ()
@vcall 83 Float64 GetStartThetaMaxValue ()
@vcall 84 Float64 GetStartTheta ()
@vcall 85 None SetEndTheta (Float64,)
@vcall 86 Float64 GetEndThetaMinValue ()
@vcall 87 Float64 GetEndThetaMaxValue ()
@vcall 88 Float64 GetEndTheta ()
@vcall 89 None SetStartPhi (Float64,)
@vcall 90 Float64 GetStartPhiMinValue ()
@vcall 91 Float64 GetStartPhiMaxValue ()
@vcall 92 Float64 GetStartPhi ()
@vcall 93 None SetEndPhi (Float64,)
@vcall 94 Float64 GetEndPhiMinValue ()
@vcall 95 Float64 GetEndPhiMaxValue ()
@vcall 96 Float64 GetEndPhi ()
@vcall 97 None SetLatLongTessellation (Int32,)
@vcall 98 Int32 GetLatLongTessellation ()
@vcall 99 None LatLongTessellationOn ()
@vcall 100 None LatLongTessellationOff ()
@vcall 61 Int32 RequestData (Ptr{Void}, Ptr{Ptr{Void}}, Ptr{Void})
@vcall 60 Int32 RequestInformation (Ptr{Void}, Ptr{Ptr{Void}}, Ptr{Void})
