cur_class = vtkScalarBarActor
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkScalarBarActor} NewInstance () _ZNK17vtkScalarBarActor11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 51 Int32 RenderOpaqueGeometry (Ptr{vtkViewport},)
@vcall 52 Int32 RenderTranslucentPolygonalGeometry (Ptr{vtkViewport},)
@vcall 54 Int32 RenderOverlay (Ptr{vtkViewport},)
@vcall 59 Int32 HasTranslucentPolygonalGeometry ()
@vcall 60 None ReleaseGraphicsResources (Ptr{vtkWindow},)
@vcall 87 None SetLookupTable (Ptr{vtkScalarsToColors},)
@vcall 88 Ptr{vtkScalarsToColors} GetLookupTable ()
@vcall 89 None SetUseOpacity (Int32,)
@vcall 90 Int32 GetUseOpacity ()
@vcall 91 None UseOpacityOn ()
@vcall 92 None UseOpacityOff ()
@vcall 93 None SetMaximumNumberOfColors (Int32,)
@vcall 94 Int32 GetMaximumNumberOfColorsMinValue ()
@vcall 95 Int32 GetMaximumNumberOfColorsMaxValue ()
@vcall 96 Int32 GetMaximumNumberOfColors ()
@vcall 97 None SetNumberOfLabels (Int32,)
@vcall 98 Int32 GetNumberOfLabelsMinValue ()
@vcall 99 Int32 GetNumberOfLabelsMaxValue ()
@vcall 100 Int32 GetNumberOfLabels ()
@vcall 101 None SetOrientation (Int32,)
@vcall 102 Int32 GetOrientationMinValue ()
@vcall 103 Int32 GetOrientationMaxValue ()
@vcall 104 Int32 GetOrientation ()
@mcall None SetOrientationToHorizontal () _ZN17vtkScalarBarActor26SetOrientationToHorizontalEv "libvtkRendering"
@mcall None SetOrientationToVertical () _ZN17vtkScalarBarActor24SetOrientationToVerticalEv "libvtkRendering"
@vcall 105 None SetTitleTextProperty (Ptr{vtkTextProperty},)
@vcall 106 Ptr{vtkTextProperty} GetTitleTextProperty ()
@vcall 107 None SetLabelTextProperty (Ptr{vtkTextProperty},)
@vcall 108 Ptr{vtkTextProperty} GetLabelTextProperty ()
@vcall 109 None SetLabelFormat (Ptr{Uint8},)
@vcall 110 Ptr{Uint8} GetLabelFormat ()
@vcall 111 None SetTitle (Ptr{Uint8},)
@vcall 112 Ptr{Uint8} GetTitle ()
@vcall 113 None SetComponentTitle (Ptr{Uint8},)
@vcall 114 Ptr{Uint8} GetComponentTitle ()
@vcall 42 None ShallowCopy (Ptr{vtkProp},)
@vcall 115 None SetTextureGridWidth (Float64,)
@vcall 116 Float64 GetTextureGridWidth ()
@vcall 117 Ptr{vtkActor2D} GetTextureActor ()
@vcall 118 None SetTextPosition (Int32,)
@vcall 119 Int32 GetTextPositionMinValue ()
@vcall 120 Int32 GetTextPositionMaxValue ()
@vcall 121 Int32 GetTextPosition ()
@vcall 122 None SetTextPositionToPrecedeScalarBar ()
@vcall 123 None SetTextPositionToSucceedScalarBar ()
@vcall 124 None SetMaximumWidthInPixels (Int32,)
@vcall 125 Int32 GetMaximumWidthInPixels ()
@vcall 126 None SetMaximumHeightInPixels (Int32,)
@vcall 127 Int32 GetMaximumHeightInPixels ()
@vcall 128 None SetDrawBackground (Int32,)
@vcall 129 Int32 GetDrawBackground ()
@vcall 130 None DrawBackgroundOn ()
@vcall 131 None DrawBackgroundOff ()
@vcall 132 None SetDrawFrame (Int32,)
@vcall 133 Int32 GetDrawFrame ()
@vcall 134 None DrawFrameOn ()
@vcall 135 None DrawFrameOff ()
@vcall 136 None SetBackgroundProperty (Ptr{vtkProperty2D},)
@vcall 137 Ptr{vtkProperty2D} GetBackgroundProperty ()
@vcall 138 None SetFrameProperty (Ptr{vtkProperty2D},)
@vcall 139 Ptr{vtkProperty2D} GetFrameProperty ()
@vcall 140 None AllocateAndSizeLabels (Ptr{Int32}, Ptr{Int32}, Ptr{vtkViewport}, Ptr{Float64})
@vcall 141 None SizeTitle (Ptr{Int32}, Ptr{Int32}, Ptr{vtkViewport})
@mcall None vtkScalarBarActor_eq (Void,) _ZN17vtkScalarBarActoraSERKS_ "libvtkRendering"
