cur_class = vtkSmoothPolyDataFilter
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkSmoothPolyDataFilter} NewInstance () _ZNK23vtkSmoothPolyDataFilter11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetConvergence (Float64,)
@vcall 66 Float64 GetConvergenceMinValue ()
@vcall 67 Float64 GetConvergenceMaxValue ()
@vcall 68 Float64 GetConvergence ()
@vcall 69 None SetNumberOfIterations (Int32,)
@vcall 70 Int32 GetNumberOfIterationsMinValue ()
@vcall 71 Int32 GetNumberOfIterationsMaxValue ()
@vcall 72 Int32 GetNumberOfIterations ()
@vcall 73 None SetRelaxationFactor (Float64,)
@vcall 74 Float64 GetRelaxationFactor ()
@vcall 75 None SetFeatureEdgeSmoothing (Int32,)
@vcall 76 Int32 GetFeatureEdgeSmoothing ()
@vcall 77 None FeatureEdgeSmoothingOn ()
@vcall 78 None FeatureEdgeSmoothingOff ()
@vcall 79 None SetFeatureAngle (Float64,)
@vcall 80 Float64 GetFeatureAngleMinValue ()
@vcall 81 Float64 GetFeatureAngleMaxValue ()
@vcall 82 Float64 GetFeatureAngle ()
@vcall 83 None SetEdgeAngle (Float64,)
@vcall 84 Float64 GetEdgeAngleMinValue ()
@vcall 85 Float64 GetEdgeAngleMaxValue ()
@vcall 86 Float64 GetEdgeAngle ()
@vcall 87 None SetBoundarySmoothing (Int32,)
@vcall 88 Int32 GetBoundarySmoothing ()
@vcall 89 None BoundarySmoothingOn ()
@vcall 90 None BoundarySmoothingOff ()
@vcall 91 None SetGenerateErrorScalars (Int32,)
@vcall 92 Int32 GetGenerateErrorScalars ()
@vcall 93 None GenerateErrorScalarsOn ()
@vcall 94 None GenerateErrorScalarsOff ()
@vcall 95 None SetGenerateErrorVectors (Int32,)
@vcall 96 Int32 GetGenerateErrorVectors ()
@vcall 97 None GenerateErrorVectorsOn ()
@vcall 98 None GenerateErrorVectorsOff ()
@mcall None SetSource (Ptr{vtkPolyData},) _ZN23vtkSmoothPolyDataFilter9SetSourceEP11vtkPolyData "libvtkGraphics"
@mcall Ptr{vtkPolyData} GetSource () _ZN23vtkSmoothPolyDataFilter9GetSourceEv "libvtkGraphics"
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@mcall None vtkSmoothPolyDataFilter_eq (Void,) _ZN23vtkSmoothPolyDataFilteraSERKS_ "libvtkGraphics"
