cur_class = vtkSectorSource
@scall Ptr{vtkSectorSource} vtkSectorSourceNew () _ZN15vtkSectorSource3NewEv "libvtkGraphics"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN15vtkSectorSource8IsTypeOfEPKc "libvtkGraphics"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkSectorSource} SafeDownCast (Ptr{vtkObjectBase},) _ZN15vtkSectorSource12SafeDownCastEP13vtkObjectBase "libvtkGraphics"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkSectorSource} NewInstance () _ZNK15vtkSectorSource11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetInnerRadius (Float64,)
@vcall 66 Float64 GetInnerRadiusMinValue ()
@vcall 67 Float64 GetInnerRadiusMaxValue ()
@vcall 68 Float64 GetInnerRadius ()
@vcall 69 None SetOuterRadius (Float64,)
@vcall 70 Float64 GetOuterRadiusMinValue ()
@vcall 71 Float64 GetOuterRadiusMaxValue ()
@vcall 72 Float64 GetOuterRadius ()
@vcall 73 None SetZCoord (Float64,)
@vcall 74 Float64 GetZCoordMinValue ()
@vcall 75 Float64 GetZCoordMaxValue ()
@vcall 76 Float64 GetZCoord ()
@vcall 77 None SetRadialResolution (Int32,)
@vcall 78 Int32 GetRadialResolutionMinValue ()
@vcall 79 Int32 GetRadialResolutionMaxValue ()
@vcall 80 Int32 GetRadialResolution ()
@vcall 81 None SetCircumferentialResolution (Int32,)
@vcall 82 Int32 GetCircumferentialResolutionMinValue ()
@vcall 83 Int32 GetCircumferentialResolutionMaxValue ()
@vcall 84 Int32 GetCircumferentialResolution ()
@vcall 85 None SetStartAngle (Float64,)
@vcall 86 Float64 GetStartAngleMinValue ()
@vcall 87 Float64 GetStartAngleMaxValue ()
@vcall 88 Float64 GetStartAngle ()
@vcall 89 None SetEndAngle (Float64,)
@vcall 90 Float64 GetEndAngleMinValue ()
@vcall 91 Float64 GetEndAngleMaxValue ()
@vcall 92 Float64 GetEndAngle ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkSectorSource_eq (Void,) _ZN15vtkSectorSourceaSERKS_ "libvtkGraphics"
