cur_class = vtkTableToPolyData
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkTableToPolyData} NewInstance () _ZNK18vtkTableToPolyData11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetXColumn (Ptr{Uint8},)
@vcall 66 Ptr{Uint8} GetXColumn ()
@vcall 67 None SetXColumnIndex (Int32,)
@vcall 68 Int32 GetXColumnIndexMinValue ()
@vcall 69 Int32 GetXColumnIndexMaxValue ()
@vcall 70 Int32 GetXColumnIndex ()
@vcall 71 None SetXComponent (Int32,)
@vcall 72 Int32 GetXComponentMinValue ()
@vcall 73 Int32 GetXComponentMaxValue ()
@vcall 74 Int32 GetXComponent ()
@vcall 75 None SetYColumn (Ptr{Uint8},)
@vcall 76 Ptr{Uint8} GetYColumn ()
@vcall 77 None SetYColumnIndex (Int32,)
@vcall 78 Int32 GetYColumnIndexMinValue ()
@vcall 79 Int32 GetYColumnIndexMaxValue ()
@vcall 80 Int32 GetYColumnIndex ()
@vcall 81 None SetYComponent (Int32,)
@vcall 82 Int32 GetYComponentMinValue ()
@vcall 83 Int32 GetYComponentMaxValue ()
@vcall 84 Int32 GetYComponent ()
@vcall 85 None SetZColumn (Ptr{Uint8},)
@vcall 86 Ptr{Uint8} GetZColumn ()
@vcall 87 None SetZColumnIndex (Int32,)
@vcall 88 Int32 GetZColumnIndexMinValue ()
@vcall 89 Int32 GetZColumnIndexMaxValue ()
@vcall 90 Int32 GetZColumnIndex ()
@vcall 91 None SetZComponent (Int32,)
@vcall 92 Int32 GetZComponentMinValue ()
@vcall 93 Int32 GetZComponentMaxValue ()
@vcall 94 Int32 GetZComponent ()
@vcall 95 None SetCreate2DPoints (Bool,)
@vcall 96 Bool GetCreate2DPoints ()
@vcall 97 None Create2DPointsOn ()
@vcall 98 None Create2DPointsOff ()
@vcall 99 None SetPreserveCoordinateColumnsAsDataArrays (Bool,)
@vcall 100 Bool GetPreserveCoordinateColumnsAsDataArrays ()
@vcall 101 None PreserveCoordinateColumnsAsDataArraysOn ()
@vcall 102 None PreserveCoordinateColumnsAsDataArraysOff ()
@vcall 51 Int32 FillInputPortInformation (Int32, Ptr{vtkInformation})
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkTableToPolyData_eq (Void,) _ZN18vtkTableToPolyDataaSERKS_ "libvtkGraphics"
