cur_class = vtkTimerLog
@scall Ptr{vtkTimerLog} vtkTimerLogNew () _ZN11vtkTimerLog3NewEv "libvtkCommon"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN11vtkTimerLog8IsTypeOfEPKc "libvtkCommon"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkTimerLog} SafeDownCast (Ptr{vtkObjectBase},) _ZN11vtkTimerLog12SafeDownCastEP13vtkObjectBase "libvtkCommon"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkTimerLog} NewInstance () _ZNK11vtkTimerLog11NewInstanceEv "libvtkCommon"
@vcall 4 None PrintSelf (Void, vtkIndent)
@scall None SetLogging (Int32,) _ZN11vtkTimerLog10SetLoggingEi "libvtkCommon"
@scall Int32 GetLogging () _ZN11vtkTimerLog10GetLoggingEv "libvtkCommon"
@scall None LoggingOn () _ZN11vtkTimerLog9LoggingOnEv "libvtkCommon"
@scall None LoggingOff () _ZN11vtkTimerLog10LoggingOffEv "libvtkCommon"
@scall None SetMaxEntries (Int32,) _ZN11vtkTimerLog13SetMaxEntriesEi "libvtkCommon"
@scall Int32 GetMaxEntries () _ZN11vtkTimerLog13GetMaxEntriesEv "libvtkCommon"
@scall None FormatAndMarkEvent (Ptr{Uint8},) _ZN11vtkTimerLog18FormatAndMarkEventEPKcz "libvtkCommon"
@scall None DumpLog (Ptr{Uint8},) _ZN11vtkTimerLog7DumpLogEPKc "libvtkCommon"
@scall None MarkStartEvent (Ptr{Uint8},) _ZN11vtkTimerLog14MarkStartEventEPKc "libvtkCommon"
@scall None MarkEndEvent (Ptr{Uint8},) _ZN11vtkTimerLog12MarkEndEventEPKc "libvtkCommon"
@scall None DumpLogWithIndents (Ptr{ostream}, Float64) _ZN11vtkTimerLog18DumpLogWithIndentsEPSod "libvtkCommon"
@scall Int32 GetNumberOfEvents () _ZN11vtkTimerLog17GetNumberOfEventsEv "libvtkCommon"
@scall Int32 GetEventIndent (Int32,) _ZN11vtkTimerLog14GetEventIndentEi "libvtkCommon"
@scall Float64 GetEventWallTime (Int32,) _ZN11vtkTimerLog16GetEventWallTimeEi "libvtkCommon"
@scall Ptr{Uint8} GetEventString (Int32,) _ZN11vtkTimerLog14GetEventStringEi "libvtkCommon"
@scall None MarkEvent (Ptr{Uint8},) _ZN11vtkTimerLog9MarkEventEPKc "libvtkCommon"
@scall None ResetLog () _ZN11vtkTimerLog8ResetLogEv "libvtkCommon"
@scall None AllocateLog () _ZN11vtkTimerLog11AllocateLogEv "libvtkCommon"
@scall None CleanupLog () _ZN11vtkTimerLog10CleanupLogEv "libvtkCommon"
@scall Float64 GetUniversalTime () _ZN11vtkTimerLog16GetUniversalTimeEv "libvtkCommon"
@scall Float64 GetCPUTime () _ZN11vtkTimerLog10GetCPUTimeEv "libvtkCommon"
@mcall None StartTimer () _ZN11vtkTimerLog10StartTimerEv "libvtkCommon"
@mcall None StopTimer () _ZN11vtkTimerLog9StopTimerEv "libvtkCommon"
@mcall Float64 GetElapsedTime () _ZN11vtkTimerLog14GetElapsedTimeEv "libvtkCommon"
@scall Float64 GetCurrentTime () _ZN11vtkTimerLog14GetCurrentTimeEv "libvtkCommon"
@scall Ptr{vtkTimerLogEntry} GetEvent (Int32,) _ZN11vtkTimerLog8GetEventEi "libvtkCommon"
@scall None DumpEntry (Void, Int32, Float64, Float64, Int32, Int32, Ptr{Uint8}) _ZN11vtkTimerLog9DumpEntryERSoiddiiPKc "libvtkCommon"
@mcall None vtkTimerLog_eq (Void,) _ZN11vtkTimerLogaSERKS_ "libvtkCommon"
