cur_class = vtkViewTheme
@scall Ptr{vtkViewTheme} vtkViewThemeNew () _ZN12vtkViewTheme3NewEv "libvtkRendering"
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN12vtkViewTheme8IsTypeOfEPKc "libvtkRendering"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkViewTheme} SafeDownCast (Ptr{vtkObjectBase},) _ZN12vtkViewTheme12SafeDownCastEP13vtkObjectBase "libvtkRendering"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkViewTheme} NewInstance () _ZNK12vtkViewTheme11NewInstanceEv "libvtkRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 20 None SetPointSize (Float64,)
@vcall 21 Float64 GetPointSize ()
@vcall 22 None SetLineWidth (Float64,)
@vcall 23 Float64 GetLineWidth ()
@vcall 24 None SetPointColor (Float64, Float64, Float64)
@vcall 25 None SetPointColor (Ptr{Float64},)
@vcall 26 Ptr{Float64} GetPointColor ()
@vcall 27 None GetPointColor (Void, Void, Void)
@vcall 28 None GetPointColor (Ptr{Float64},)
@vcall 29 None SetPointOpacity (Float64,)
@vcall 30 Float64 GetPointOpacity ()
@vcall 31 None SetPointHueRange (Float64, Float64)
@vcall 32 None SetPointHueRange (Ptr{Float64},)
@vcall 33 Ptr{Float64} GetPointHueRange ()
@vcall 34 None GetPointHueRange (Void, Void)
@vcall 35 None GetPointHueRange (Ptr{Float64},)
@vcall 36 None SetPointSaturationRange (Float64, Float64)
@vcall 37 None SetPointSaturationRange (Ptr{Float64},)
@vcall 38 Ptr{Float64} GetPointSaturationRange ()
@vcall 39 None GetPointSaturationRange (Void, Void)
@vcall 40 None GetPointSaturationRange (Ptr{Float64},)
@vcall 41 None SetPointValueRange (Float64, Float64)
@vcall 42 None SetPointValueRange (Ptr{Float64},)
@vcall 43 Ptr{Float64} GetPointValueRange ()
@vcall 44 None GetPointValueRange (Void, Void)
@vcall 45 None GetPointValueRange (Ptr{Float64},)
@vcall 46 None SetPointAlphaRange (Float64, Float64)
@vcall 47 None SetPointAlphaRange (Ptr{Float64},)
@vcall 48 Ptr{Float64} GetPointAlphaRange ()
@vcall 49 None GetPointAlphaRange (Void, Void)
@vcall 50 None GetPointAlphaRange (Ptr{Float64},)
@vcall 51 Ptr{vtkScalarsToColors} GetPointLookupTable ()
@vcall 52 None SetPointLookupTable (Ptr{vtkScalarsToColors},)
@vcall 53 None SetScalePointLookupTable (Bool,)
@vcall 54 Bool GetScalePointLookupTable ()
@vcall 55 None ScalePointLookupTableOn ()
@vcall 56 None ScalePointLookupTableOff ()
@vcall 57 None SetCellColor (Float64, Float64, Float64)
@vcall 58 None SetCellColor (Ptr{Float64},)
@vcall 59 Ptr{Float64} GetCellColor ()
@vcall 60 None GetCellColor (Void, Void, Void)
@vcall 61 None GetCellColor (Ptr{Float64},)
@vcall 62 None SetCellOpacity (Float64,)
@vcall 63 Float64 GetCellOpacity ()
@vcall 64 None SetCellHueRange (Float64, Float64)
@vcall 65 None SetCellHueRange (Ptr{Float64},)
@vcall 66 Ptr{Float64} GetCellHueRange ()
@vcall 67 None GetCellHueRange (Void, Void)
@vcall 68 None GetCellHueRange (Ptr{Float64},)
@vcall 69 None SetCellSaturationRange (Float64, Float64)
@vcall 70 None SetCellSaturationRange (Ptr{Float64},)
@vcall 71 Ptr{Float64} GetCellSaturationRange ()
@vcall 72 None GetCellSaturationRange (Void, Void)
@vcall 73 None GetCellSaturationRange (Ptr{Float64},)
@vcall 74 None SetCellValueRange (Float64, Float64)
@vcall 75 None SetCellValueRange (Ptr{Float64},)
@vcall 76 Ptr{Float64} GetCellValueRange ()
@vcall 77 None GetCellValueRange (Void, Void)
@vcall 78 None GetCellValueRange (Ptr{Float64},)
@vcall 79 None SetCellAlphaRange (Float64, Float64)
@vcall 80 None SetCellAlphaRange (Ptr{Float64},)
@vcall 81 Ptr{Float64} GetCellAlphaRange ()
@vcall 82 None GetCellAlphaRange (Void, Void)
@vcall 83 None GetCellAlphaRange (Ptr{Float64},)
@vcall 84 Ptr{vtkScalarsToColors} GetCellLookupTable ()
@vcall 85 None SetCellLookupTable (Ptr{vtkScalarsToColors},)
@vcall 86 None SetScaleCellLookupTable (Bool,)
@vcall 87 Bool GetScaleCellLookupTable ()
@vcall 88 None ScaleCellLookupTableOn ()
@vcall 89 None ScaleCellLookupTableOff ()
@vcall 90 None SetOutlineColor (Float64, Float64, Float64)
@vcall 91 None SetOutlineColor (Ptr{Float64},)
@vcall 92 Ptr{Float64} GetOutlineColor ()
@vcall 93 None GetOutlineColor (Void, Void, Void)
@vcall 94 None GetOutlineColor (Ptr{Float64},)
@vcall 95 None SetSelectedPointColor (Float64, Float64, Float64)
@vcall 96 None SetSelectedPointColor (Ptr{Float64},)
@vcall 97 Ptr{Float64} GetSelectedPointColor ()
@vcall 98 None GetSelectedPointColor (Void, Void, Void)
@vcall 99 None GetSelectedPointColor (Ptr{Float64},)
@vcall 100 None SetSelectedPointOpacity (Float64,)
@vcall 101 Float64 GetSelectedPointOpacity ()
@vcall 102 None SetSelectedCellColor (Float64, Float64, Float64)
@vcall 103 None SetSelectedCellColor (Ptr{Float64},)
@vcall 104 Ptr{Float64} GetSelectedCellColor ()
@vcall 105 None GetSelectedCellColor (Void, Void, Void)
@vcall 106 None GetSelectedCellColor (Ptr{Float64},)
@vcall 107 None SetSelectedCellOpacity (Float64,)
@vcall 108 Float64 GetSelectedCellOpacity ()
@vcall 109 None SetBackgroundColor (Float64, Float64, Float64)
@vcall 110 None SetBackgroundColor (Ptr{Float64},)
@vcall 111 Ptr{Float64} GetBackgroundColor ()
@vcall 112 None GetBackgroundColor (Void, Void, Void)
@vcall 113 None GetBackgroundColor (Ptr{Float64},)
@vcall 114 None SetBackgroundColor2 (Float64, Float64, Float64)
@vcall 115 None SetBackgroundColor2 (Ptr{Float64},)
@vcall 116 Ptr{Float64} GetBackgroundColor2 ()
@vcall 117 None GetBackgroundColor2 (Void, Void, Void)
@vcall 118 None GetBackgroundColor2 (Ptr{Float64},)
@vcall 119 None SetPointTextProperty (Ptr{vtkTextProperty},)
@vcall 120 Ptr{vtkTextProperty} GetPointTextProperty ()
@vcall 121 None SetCellTextProperty (Ptr{vtkTextProperty},)
@vcall 122 Ptr{vtkTextProperty} GetCellTextProperty ()
@vcall 123 None SetVertexLabelColor (Float64, Float64, Float64)
@vcall 124 None SetVertexLabelColor (Ptr{Float64},)
@vcall 125 Ptr{Float64} GetVertexLabelColor ()
@vcall 126 None GetVertexLabelColor (Void, Void, Void)
@vcall 127 None GetVertexLabelColor (Ptr{Float64},)
@vcall 128 None SetEdgeLabelColor (Float64, Float64, Float64)
@vcall 129 None SetEdgeLabelColor (Ptr{Float64},)
@vcall 130 Ptr{Float64} GetEdgeLabelColor ()
@vcall 131 None GetEdgeLabelColor (Void, Void, Void)
@vcall 132 None GetEdgeLabelColor (Ptr{Float64},)
@scall Ptr{vtkViewTheme} CreateOceanTheme () _ZN12vtkViewTheme16CreateOceanThemeEv "libvtkRendering"
@scall Ptr{vtkViewTheme} CreateMellowTheme () _ZN12vtkViewTheme17CreateMellowThemeEv "libvtkRendering"
@scall Ptr{vtkViewTheme} CreateNeonTheme () _ZN12vtkViewTheme15CreateNeonThemeEv "libvtkRendering"
@mcall Bool LookupMatchesPointTheme (Ptr{vtkScalarsToColors},) _ZN12vtkViewTheme23LookupMatchesPointThemeEP18vtkScalarsToColors "libvtkRendering"
@mcall Bool LookupMatchesCellTheme (Ptr{vtkScalarsToColors},) _ZN12vtkViewTheme22LookupMatchesCellThemeEP18vtkScalarsToColors "libvtkRendering"
@mcall None vtkViewTheme_eq (Void,) _ZN12vtkViewThemeaSERKS_ "libvtkRendering"
