cur_class = vtkVolumeProMapper
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@scall Int32 IsTypeOf (Ptr{Uint8},) _ZN18vtkVolumeProMapper8IsTypeOfEPKc "libvtkVolumeRendering"
@vcall 1 Int32 IsA (Ptr{Uint8},)
@scall Ptr{vtkVolumeProMapper} SafeDownCast (Ptr{vtkObjectBase},) _ZN18vtkVolumeProMapper12SafeDownCastEP13vtkObjectBase "libvtkVolumeRendering"
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkVolumeProMapper} NewInstance () _ZNK18vtkVolumeProMapper11NewInstanceEv "libvtkVolumeRendering"
@vcall 4 None PrintSelf (Void, vtkIndent)
@scall Ptr{vtkVolumeProMapper} vtkVolumeProMapperNew () _ZN18vtkVolumeProMapper3NewEv "libvtkVolumeRendering"
@vcall 79 None Render (Ptr{vtkRenderer}, Ptr{vtkVolume})
@vcall 81 None SetBlendMode (Int32,)
@vcall 99 Int32 GetBlendModeMinValue ()
@vcall 100 Int32 GetBlendModeMaxValue ()
@vcall 82 Int32 GetBlendMode ()
@mcall None SetBlendModeToComposite () _ZN18vtkVolumeProMapper23SetBlendModeToCompositeEv "libvtkVolumeRendering"
@mcall None SetBlendModeToMaximumIntensity () _ZN18vtkVolumeProMapper30SetBlendModeToMaximumIntensityEv "libvtkVolumeRendering"
@mcall None SetBlendModeToMinimumIntensity () _ZN18vtkVolumeProMapper30SetBlendModeToMinimumIntensityEv "libvtkVolumeRendering"
@mcall Ptr{Uint8} GetBlendModeAsString () _ZN18vtkVolumeProMapper20GetBlendModeAsStringEv "libvtkVolumeRendering"
@vcall 101 None SetSubVolume (Int32, Int32, Int32, Int32, Int32, Int32)
@vcall 102 None SetSubVolume (Ptr{Int32},)
@vcall 103 Ptr{Int32} GetSubVolume ()
@vcall 104 None GetSubVolume (Ptr{Int32},)
@vcall 105 None SetCursor (Int32,)
@vcall 106 Int32 GetCursorMinValue ()
@vcall 107 Int32 GetCursorMaxValue ()
@vcall 108 Int32 GetCursor ()
@vcall 109 None CursorOn ()
@vcall 110 None CursorOff ()
@vcall 111 None SetCursorType (Int32,)
@vcall 112 Int32 GetCursorTypeMinValue ()
@vcall 113 Int32 GetCursorTypeMaxValue ()
@vcall 114 Int32 GetCursorType ()
@mcall None SetCursorTypeToCrossHair () _ZN18vtkVolumeProMapper24SetCursorTypeToCrossHairEv "libvtkVolumeRendering"
@mcall None SetCursorTypeToPlane () _ZN18vtkVolumeProMapper20SetCursorTypeToPlaneEv "libvtkVolumeRendering"
@mcall Ptr{Uint8} GetCursorTypeAsString () _ZN18vtkVolumeProMapper21GetCursorTypeAsStringEv "libvtkVolumeRendering"
@vcall 115 None SetCursorPosition (Float64, Float64, Float64)
@vcall 116 None SetCursorPosition (Ptr{Float64},)
@vcall 117 Ptr{Float64} GetCursorPosition ()
@vcall 118 None GetCursorPosition (Ptr{Float64},)
@vcall 119 None SetCursorXAxisColor (Float64, Float64, Float64)
@vcall 120 None SetCursorXAxisColor (Ptr{Float64},)
@vcall 121 Ptr{Float64} GetCursorXAxisColor ()
@vcall 122 None GetCursorXAxisColor (Ptr{Float64},)
@vcall 123 None SetCursorYAxisColor (Float64, Float64, Float64)
@vcall 124 None SetCursorYAxisColor (Ptr{Float64},)
@vcall 125 Ptr{Float64} GetCursorYAxisColor ()
@vcall 126 None GetCursorYAxisColor (Ptr{Float64},)
@vcall 127 None SetCursorZAxisColor (Float64, Float64, Float64)
@vcall 128 None SetCursorZAxisColor (Ptr{Float64},)
@vcall 129 Ptr{Float64} GetCursorZAxisColor ()
@vcall 130 None GetCursorZAxisColor (Ptr{Float64},)
@vcall 131 None SetSuperSampling (Int32,)
@vcall 132 Int32 GetSuperSamplingMinValue ()
@vcall 133 Int32 GetSuperSamplingMaxValue ()
@vcall 134 Int32 GetSuperSampling ()
@vcall 135 None SuperSamplingOn ()
@vcall 136 None SuperSamplingOff ()
@vcall 137 None SetSuperSamplingFactor (Float64, Float64, Float64)
@mcall None SetSuperSamplingFactor (Ptr{Float64},) _ZN18vtkVolumeProMapper22SetSuperSamplingFactorEPd "libvtkVolumeRendering"
@vcall 138 Ptr{Float64} GetSuperSamplingFactor ()
@vcall 139 None GetSuperSamplingFactor (Ptr{Float64},)
@vcall 140 None SetCutPlane (Int32,)
@vcall 141 Int32 GetCutPlaneMinValue ()
@vcall 142 Int32 GetCutPlaneMaxValue ()
@vcall 143 Int32 GetCutPlane ()
@vcall 144 None CutPlaneOn ()
@vcall 145 None CutPlaneOff ()
@vcall 146 None SetCutPlaneEquation (Float64, Float64, Float64, Float64)
@vcall 147 None SetCutPlaneEquation (Ptr{Float64},)
@vcall 148 Ptr{Float64} GetCutPlaneEquation ()
@vcall 149 None GetCutPlaneEquation (Ptr{Float64},)
@vcall 150 None SetCutPlaneThickness (Float64,)
@vcall 151 Float64 GetCutPlaneThicknessMinValue ()
@vcall 152 Float64 GetCutPlaneThicknessMaxValue ()
@vcall 153 Float64 GetCutPlaneThickness ()
@vcall 154 None SetCutPlaneFallOffDistance (Int32,)
@vcall 155 Int32 GetCutPlaneFallOffDistanceMinValue ()
@vcall 156 Int32 GetCutPlaneFallOffDistanceMaxValue ()
@vcall 157 Int32 GetCutPlaneFallOffDistance ()
@vcall 158 None SetGradientOpacityModulation (Int32,)
@vcall 159 Int32 GetGradientOpacityModulationMinValue ()
@vcall 160 Int32 GetGradientOpacityModulationMaxValue ()
@vcall 161 Int32 GetGradientOpacityModulation ()
@vcall 162 None GradientOpacityModulationOn ()
@vcall 163 None GradientOpacityModulationOff ()
@vcall 164 None SetGradientDiffuseModulation (Int32,)
@vcall 165 Int32 GetGradientDiffuseModulationMinValue ()
@vcall 166 Int32 GetGradientDiffuseModulationMaxValue ()
@vcall 167 Int32 GetGradientDiffuseModulation ()
@vcall 168 None GradientDiffuseModulationOn ()
@vcall 169 None GradientDiffuseModulationOff ()
@vcall 170 None SetGradientSpecularModulation (Int32,)
@vcall 171 Int32 GetGradientSpecularModulationMinValue ()
@vcall 172 Int32 GetGradientSpecularModulationMaxValue ()
@vcall 173 Int32 GetGradientSpecularModulation ()
@vcall 174 None GradientSpecularModulationOn ()
@vcall 175 None GradientSpecularModulationOff ()
@vcall 176 Int32 GetNoHardware ()
@vcall 177 Int32 GetWrongVLIVersion ()
@vcall 178 Int32 GetNumberOfBoards ()
@vcall 179 Int32 GetMajorBoardVersion ()
@vcall 180 Int32 GetMinorBoardVersion ()
@vcall 181 Int32 GetAvailableBoardMemory ()
@vcall 182 None GetLockSizesForBoardMemory (Uint32, Ptr{Uint32}, Ptr{Uint32}, Ptr{Uint32})
@vcall 183 None SetIntermixIntersectingGeometry (Int32,)
@vcall 184 Int32 GetIntermixIntersectingGeometryMinValue ()
@vcall 185 Int32 GetIntermixIntersectingGeometryMaxValue ()
@vcall 186 Int32 GetIntermixIntersectingGeometry ()
@vcall 187 None IntermixIntersectingGeometryOn ()
@vcall 188 None IntermixIntersectingGeometryOff ()
@vcall 189 None SetAutoAdjustMipmapLevels (Int32,)
@vcall 190 Int32 GetAutoAdjustMipmapLevelsMinValue ()
@vcall 191 Int32 GetAutoAdjustMipmapLevelsMaxValue ()
@vcall 192 Int32 GetAutoAdjustMipmapLevels ()
@vcall 193 None AutoAdjustMipmapLevelsOn ()
@vcall 194 None AutoAdjustMipmapLevelsOff ()
@vcall 195 None SetMinimumMipmapLevel (Int32,)
@vcall 196 Int32 GetMinimumMipmapLevelMinValue ()
@vcall 197 Int32 GetMinimumMipmapLevelMaxValue ()
@vcall 198 Int32 GetMinimumMipmapLevel ()
@vcall 199 None SetMaximumMipmapLevel (Int32,)
@vcall 200 Int32 GetMaximumMipmapLevelMinValue ()
@vcall 201 Int32 GetMaximumMipmapLevelMaxValue ()
@vcall 202 Int32 GetMaximumMipmapLevel ()
@vcall 203 None SetMipmapLevel (Int32,)
@vcall 204 Int32 GetMipmapLevelMinValue ()
@vcall 205 Int32 GetMipmapLevelMaxValue ()
@vcall 206 Int32 GetMipmapLevel ()
@mcall Int32 StatusOK () _ZN18vtkVolumeProMapper8StatusOKEv "libvtkVolumeRendering"
@mcall None StoreRenderTime (Ptr{vtkRenderer}, Ptr{vtkVolume}, Float32) _ZN18vtkVolumeProMapper15StoreRenderTimeEP11vtkRendererP9vtkVolumef "libvtkVolumeRendering"
@mcall Float32 RetrieveRenderTime (Ptr{vtkRenderer}, Ptr{vtkVolume}) _ZN18vtkVolumeProMapper18RetrieveRenderTimeEP11vtkRendererP9vtkVolume "libvtkVolumeRendering"
@mcall None vtkVolumeProMapper_eq (Void,) _ZN18vtkVolumeProMapperaSERKS_ "libvtkVolumeRendering"
