cur_class = vtkWindowedSincPolyDataFilter
@vcall 0 Ptr{Uint8} GetClassNameInternal ()
@vcall 1 Int32 IsA (Ptr{Uint8},)
@vcall 15 Ptr{vtkObjectBase} NewInstanceInternal ()
@mcall Ptr{vtkWindowedSincPolyDataFilter} NewInstance () _ZNK29vtkWindowedSincPolyDataFilter11NewInstanceEv "libvtkGraphics"
@vcall 4 None PrintSelf (Void, vtkIndent)
@vcall 65 None SetNumberOfIterations (Int32,)
@vcall 66 Int32 GetNumberOfIterationsMinValue ()
@vcall 67 Int32 GetNumberOfIterationsMaxValue ()
@vcall 68 Int32 GetNumberOfIterations ()
@vcall 69 None SetPassBand (Float64,)
@vcall 70 Float64 GetPassBandMinValue ()
@vcall 71 Float64 GetPassBandMaxValue ()
@vcall 72 Float64 GetPassBand ()
@vcall 73 None SetNormalizeCoordinates (Int32,)
@vcall 74 Int32 GetNormalizeCoordinates ()
@vcall 75 None NormalizeCoordinatesOn ()
@vcall 76 None NormalizeCoordinatesOff ()
@vcall 77 None SetFeatureEdgeSmoothing (Int32,)
@vcall 78 Int32 GetFeatureEdgeSmoothing ()
@vcall 79 None FeatureEdgeSmoothingOn ()
@vcall 80 None FeatureEdgeSmoothingOff ()
@vcall 81 None SetFeatureAngle (Float64,)
@vcall 82 Float64 GetFeatureAngleMinValue ()
@vcall 83 Float64 GetFeatureAngleMaxValue ()
@vcall 84 Float64 GetFeatureAngle ()
@vcall 85 None SetEdgeAngle (Float64,)
@vcall 86 Float64 GetEdgeAngleMinValue ()
@vcall 87 Float64 GetEdgeAngleMaxValue ()
@vcall 88 Float64 GetEdgeAngle ()
@vcall 89 None SetBoundarySmoothing (Int32,)
@vcall 90 Int32 GetBoundarySmoothing ()
@vcall 91 None BoundarySmoothingOn ()
@vcall 92 None BoundarySmoothingOff ()
@vcall 93 None SetNonManifoldSmoothing (Int32,)
@vcall 94 Int32 GetNonManifoldSmoothing ()
@vcall 95 None NonManifoldSmoothingOn ()
@vcall 96 None NonManifoldSmoothingOff ()
@vcall 97 None SetGenerateErrorScalars (Int32,)
@vcall 98 Int32 GetGenerateErrorScalars ()
@vcall 99 None GenerateErrorScalarsOn ()
@vcall 100 None GenerateErrorScalarsOff ()
@vcall 101 None SetGenerateErrorVectors (Int32,)
@vcall 102 Int32 GetGenerateErrorVectors ()
@vcall 103 None GenerateErrorVectorsOn ()
@vcall 104 None GenerateErrorVectorsOff ()
@vcall 61 Int32 RequestData (Ptr{vtkInformation}, Ptr{Ptr{vtkInformationVector}}, Ptr{vtkInformationVector})
@mcall None vtkWindowedSincPolyDataFilter_eq (Void,) _ZN29vtkWindowedSincPolyDataFilteraSERKS_ "libvtkGraphics"
